### ISSUE TITLE
Unable to use TypeAlias

### ISSUE THREAD

**Issue by siddharthrajaraja** [python/typing#1002]
When I try to lint with mypy I get this :
`error: Name 'typing_extensions.TypeAlias' is not defined`
this has been automatically generated inside gen folder when I convert `xx.proto` file to `xx_pb.py` files

**Comment by srittau** [comment]
Maybe @nipunn1313 has some insight what could be wrong here.

**Comment by hauntsaninja** [comment]
What mypy version are you using? Try 0.930

**Comment by nipunn1313** [comment]
It requires mypy 0.930

if you can’t resolve:

What version of mypy, mypy_protobuf, and python are you using?

**Comment by siddharthrajaraja** [comment]
I used python 3.8.x , mypy 0.930 and my_protobuf 3.1.0 @nipunn1313

**Comment by siddharthrajaraja** [comment]
@nipunn1313 , it will be good if you help me out with exact versions needed to resolve this issue

**Comment by nipunn1313** [comment]
Hmm.

Ok here's a hypothesis.
What version of typing_extensions do you have?
```
 pip3 show typing_extensions
```

It looks like it was added with https://github.com/python/typing/commit/6d287f054b4f535a8b0ff1c249a28795894690d0 in 3.7.4.2 (which released July 2020). Is it possible you have a version older than that installed?

If this is the case leading to the issue, I think the more permanent solution is to add it to the setup requirements for mypy-protobuf (https://github.com/dropbox/mypy-protobuf/blob/main/setup.cfg#L19), and the documentation.

Sorry for the trouble - hoping you can help validate if this hypothesis and see if it helps with the issue.

**Comment by hauntsaninja** [comment]
Hmm, not sure the actual version of typing_extensions should matter (at least at type check time, which OP's error definitely is);  mypy should just be looking at the typeshed stubs.

(In fact, mypy thinks typing_extensions is part of the standard library, so you can actually type check without having it installed, like in the days before modular typeshed)

If OP could provide a script that reproduces the error, ideally from a fresh virtual environment, that would be very helpful!

**Comment by siddharthrajaraja** [comment]
We can mark this closed as I changed the mypy version to latest and it worked for me. Thanks everyone.
