### ISSUE TITLE
MutableMapping.setdefault() is buggy, needs overload for one-argument case

### ISSUE THREAD

**Issue by Akuli** [python/typing#1034]
> I think https://github.com/python/typeshed/blob/61d876e4ea62c42599dbaa59471576d6eda0e04d/stdlib/typing.pyi#L480 is buggy. It needs an overload for the case where the second argument is not specified.

_Originally posted by @JelleZijlstra in https://github.com/python/typing/discussions/1033#discussioncomment-1986359_

(Edit by Akuli: link to a specific commit instead of master)

**Comment by JelleZijlstra** [comment]
This is a typeshed issue. I opened python/typeshed#6941 to address it.

**Comment by Akuli** [comment]
Lol, I forgot that the discussions aren't in typeshed :)
