### ISSUE TITLE
Idea: safe and unsafe strings

### ISSUE THREAD

**Issue by Akuli** [python/typing#1044]
Many security bugs happen because a programmer assumed that user input is not malicious. I think it would be possible to protect against this with typing.

For example, consider the following buggy pseudo-code:

```python3
class Cursor:
    def execute(self, sql, *format_params): ...

def add_request_handler(request_handler): ...

@add_request_handler
def request_handler(param):
    cursor.execute(f"select * from table where foo = '{param}'")
```

My idea is to add a new type, `UnsafeStr`, that makes type checkers warn about code like this. With type annotations, the code would become:

```python3
class Cursor:
    def execute(self, sql: str, *format_params: UnsafeStr): ...

def add_request_handler(request_handler: Callable[[UnsafeStr], None]): ...

@add_request_handler
def request_handler(param: UnsafeStr):
    cursor.execute(f"select * from table where foo = '{param}'")
```

Here:
- Type of `param` is `UnsafeStr`.
- Type of the f-string is `UnsafeStr`, because it contains another `UnsafeStr` string-formatted into it.
- It is an error to call `cursor.execute` with `UnsafeStr` as the first argument.

The correct code below passes `str` as the first argument to `cursor.execute`, and doesn't cause type checker errors:

```python3
@add_request_handler
def request_handler(param: UnsafeStr):
    cursor.execute("select * from table where foo = %s", param)
```

This would be correct as well:

```python3
def quote(string: UnsafeStr) -> str: ...

@add_request_handler
def request_handler(param: UnsafeStr):
    cursor.execute(f"select * from table where foo = {quote(param)}")
```

Making this work requires some special-casing from type checkers, but doesn't seem too bad:
- `UnsafeStr` is not a subtype of `str`, and can't be converted to `str` implicitly. But `str` is a subtype of `UnsafeStr`.
- If `user_input` is an UnsafeStr, you shouldn't be able to just do `str(user_input)` and hide the bugs from code reviewers. You should instead need an explicit cast, like `cast(str, user_input)`.
- When it is reasonable to do string operations with unsafe strings, type checkers and typeshed should make it possible, and the result should be an unsafe string.

I believe this would prevent a lot of vulnerabilities, even things like the log4j vulnerability. The bug in log4j was that it trusted strings that were already formatted to contain user input.

**Comment by hauntsaninja** [comment]
There's been discussion of this recently in typing-sig, see https://docs.google.com/document/d/1fbAbA2MCoAcSO1c8gecmUJYZ-Q0utT3CmaXlQ3IhzZw/edit

**Comment by AlexWaygood** [comment]
> There's been discussion of this recently in typing-sig, see https://docs.google.com/document/d/1fbAbA2MCoAcSO1c8gecmUJYZ-Q0utT3CmaXlQ3IhzZw/edit

Though note that the consensus on typing-sig is that `Literal[str]` is a bad way to spell the concept of a "safe string"; there's currently an ongoing bikeshedding debate about what a better spelling would be.

https://mail.python.org/archives/list/typing-sig@python.org/thread/VB74EHNM4RODDFM64NEEEBJQVAUAWIAW/

**Comment by hauntsaninja** [comment]
Further discussion on this topic should go to typing-sig. https://www.python.org/dev/peps/pep-0675/
