### ISSUE TITLE
typing-extensions became typing_extensions package name at 4.0.0 transition

### ISSUE THREAD

**Issue by ralphie0112358** [python/typing#1066]
typing-extensions became typing_extensions package name at 4.0.0 transition.  This is messing with some of our internal tooling.

*My guess* this is related to shifting from setup.cfg to pyproject.toml [project], but i am not sure.  Probably this is no fault of this project and some issue with downstream build tooling.  Hopefully someone smarter than me will know where to to direct the attention to this issue.

```
ubuntu@ip-172-31-0-86:~/dev/temp$ python3.9 --version
Python 3.9.9
```

You can see 3.10.0.2 package name is typing-extensions and the latest (or really >4.0.0) is typing_extensions.

```
ubuntu@ip-172-31-0-86:~/dev/temp$ python3.9 -m venv t310
ubuntu@ip-172-31-0-86:~/dev/temp$ t310/bin/pip install typing-extensions==3.10.0.2
Collecting typing-extensions==3.10.0.2
  Using cached typing_extensions-3.10.0.2-py3-none-any.whl (26 kB)
Installing collected packages: typing-extensions
Successfully installed typing-extensions-3.10.0.2
WARNING: You are using pip version 21.2.4; however, version 22.0.3 is available.
You should consider upgrading via the '/home/ubuntu/dev/temp/t310/bin/python3.9 -m pip install --upgrade pip' command.
ubuntu@ip-172-31-0-86:~/dev/temp$ cat t310/lib/python3.9/site-packages/typing_extensions-3.10.0.2.dist-info/METADATA | grep Name
Name: typing-extensions
```

```
ubuntu@ip-172-31-0-86:~/dev/temp$ python3.9 -m venv t40
ubuntu@ip-172-31-0-86:~/dev/temp$ t40/bin/pip install typing-extensions
Collecting typing-extensions
  Using cached typing_extensions-4.0.1-py3-none-any.whl (22 kB)
Installing collected packages: typing-extensions
Successfully installed typing-extensions-4.0.1
WARNING: You are using pip version 21.2.4; however, version 22.0.3 is available.
You should consider upgrading via the '/home/ubuntu/dev/temp/t40/bin/python3.9 -m pip install --upgrade pip' command.
ubuntu@ip-172-31-0-86:~/dev/temp$ cat t40/lib/python3.9/site-packages/typing_extensions-4.0.1.dist-info/METADATA | grep Name
Name: typing_extensions
```

Thanks in advance for your attention.

**Comment by JelleZijlstra** [comment]
Generally, hyphens and underscores are equivalent in distribution names. What do you propose we do? If we change it back, we'll presumably break people's tooling again with the next release.

**Comment by ralphie0112358** [comment]
> Generally, hyphens and underscores are equivalent in distribution names. What do you propose we do? If we change it back, we'll presumably break people's tooling again with the next release.

Your code looks good.  you have the name with `_` in setup.cfg before and name with `_` now with pyproject.toml.  I would expect the tooling to have the same behavior and result with the `-`.  I'm fine to direct this ticket to some downstream tooling, it should behave consistently.  Maybe python build package.

**Comment by ralphie0112358** [comment]
It could also be an issue with flit?  This is where I was hoping some core developer might have some insight.
```
# Build system requirements.
[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"
```

**Comment by srittau** [comment]
I personally prefer dashes over underscores in distribution names (and looking at dependencies in my projects, this seems to be generally the case), so I wouldn't mind renaming it back to `typing-extensions`, but I can also live with `typing_extensions` being kept as distribution name.

**Comment by gvanrossum** [comment]
Doesn't it make more sense for the distribution name to match the package/module name exactly? This has always confused me (especially when some tools don't mind but others seem to do).

**Comment by srittau** [comment]
Thanks for reporting the issue. In retrospect it's a bit unfortunate that we didn't catch the distribution name change, but now that it has changed, it would be more hassle to change it back.

**Comment by JelleZijlstra** [comment]
Agree. In the future let's just consistently name it `typing_extensions`.
