### ISSUE TITLE
4.1.0 error after relase in 2022.02.13 NameError: name '_UnpackAlias' is not defined

### ISSUE THREAD

**Issue by yt605155624** [python/typing#1073]
File "/workspace/tools/venv/lib/python3.7/site-packages/typing_extensions.py", line 143, in _collect_type_vars
     not isinstance(t, _UnpackAlias)
 NameError: name '_UnpackAlias' is not defined

**Comment by JelleZijlstra** [comment]
Thanks @yt605155624 for the report! Could you share the code that led to this error? I'd like to understand how our CI missed this case.

**Comment by carlogrisetti** [comment]
@JelleZijlstra I have a TravisCI build failing due to this issue. It only happens on Python 3.7 and the stack starts at `from typing import Protocol` in `importlib_metadata` module
Another traceback is `from pytest import console_main`

**Comment by JelleZijlstra** [comment]
Thanks! I see you're using 3.7.1 there; let me see if the version of 3.7 makes a difference.

**Comment by carlogrisetti** [comment]
That was unintentional, TravisCI chose 3.7.1 when asked to test on 3.7 so I suppose this issue will arise in many other builds all over the GitHubverse :)
You could temporarily yank 4.1.0 waiting for a 4.1.1 release if times are not compact enough, otherwise I suppose that you'll receive a lot of complaints tomorrow with the start of the work week.

Regards!

**Comment by JelleZijlstra** [comment]
typing.OrderedDict was new in 3.7.2, I suspect that has something to do with it. Unfortunately pyenv wasn't able to build 3.7.1 for me, but 3.7.10 is fine for me locally.

Sounds like Travis needs to update their 3.7 installation :)

But I'll release 4.1.1 later today to fix this.

**Comment by JelleZijlstra** [comment]
We confirmed that it fails on 3.7.1. To make sure we don't get any other similar issues, I'm thinking of running CI on the .0 versions of all supported Python versions. That way, we run the earliest and latest bugfix release of each version, which will hopefully be enough to catch this sort of thing in general.

**Comment by JelleZijlstra** [comment]
I just released https://pypi.org/project/typing-extensions/4.1.1/ with the fix. Thanks for reporting this bug!

**Comment by yt605155624** [comment]
Thanks for your for your timely fix and release!
