### ISSUE TITLE
Missing CHANGELOG and README.rst is sdist

### ISSUE THREAD

**Issue by hegjon** [python/typing#1094]
README and CHANGELOG is missing in sdist. The [MANIFEST.in](https://github.com/python/typing/blob/master/typing_extensions/MANIFEST.in) includes them:

`include CHANGELOG LICENSE README.rst`

We would like to continue to re-distribute them in Fedora packages https://src.fedoraproject.org/rpms/python-typing-extensions

**Comment by hegjon** [comment]
The unit test have also been removed from 4.x.x release, would it make more sense to base the RPM package on the source code from a git tag?

**Comment by srittau** [comment]
I'm not familiar with how flit works, but missing `README` and `CHANGELOG` definitely look like bugs to me. Also, `pyproject.toml` contains an explicit `readme.text` key, although I think it should use the contents of `README.rst` instead.

On the other hand I'm not a fan of including tests in the distribution package. If you want to use the tests, I would indeed recommend to use the git tag.
