### ISSUE TITLE
how to manage typing install with a multiple-python-versions setup?

### ISSUE THREAD

**Issue by alexanderLinear** [python/typing#1107]
"For package maintainers, it is preferred to use typing;python_version<"3.5" if your package requires it to support earlier Python versions. This will avoid shadowing the stdlib typing module when your package is installed via pip install -t . on Python 3.5 or later."

In a local testing system i have multiple versions of python side to side. modules will be available and useable by all of them.
Especially there are versions 2.x and 3.x living side to side.

What are the recommended methods for managing typing presence, precedence and usage with this setup?

**Comment by JelleZijlstra** [comment]
The `typing` installable module was only needed for long-dead versions of Python and is no longer supported.

In general, each Python version should have its own site-packages directory with third-party packages, some of which may not be the same across Python versions.

**Comment by alexanderLinear** [comment]
e.g. ROS kinetic is much bound to Python 2.6 - that far as i know.
there always might be reasons for doing maintenance to a system build upon that stack. (without breaking all other Python installs on the same machine by installing it with default "sharing".)

**Comment by alexanderLinear** [comment]
maybe this will do the job / follow the idea of a Python version selective install:
https://stackoverflow.com/questions/10919569/install-a-module-using-pip-for-specific-python-version
