### ISSUE TITLE
Convert typing-extensions README to Markdown?

### ISSUE THREAD

**Issue by srittau** [python/typing#1149]
* All the other non-docs files in this repository are already in Markdown format.
* Markdown is more accessible and more popular than ReST.
* Markdown is more readable as source, which is important since the file is shipped as part of the package and likely to be read this way.
* We don't need the advanced features of ReST in the README.

**Comment by JelleZijlstra** [comment]
Sure, go ahead!

I think keeping the docs as RST is useful so it's easy to copy from or to PEPs and the Python docs, but that doesn't apply to the README.

**Comment by srittau** [comment]
Definitely. The docs benefit greatly from ReST, especially from the crosslinking features and Python extensions.
