### ISSUE TITLE
Annotate new typing-extensions release with correct Requires-Python

### ISSUE THREAD

**Issue by jtratner** [python/typing#1151]
It looks like newest version of typing-extensions drops support for python3.6 - this is totally reasonable!

However, the newest release of typing-extensions did _not_ use the `Requires-Python:` metadata attribute, meaning that it gets pulled in incorrectly by pip when trying to install with older versions.

I'm not sure if it's possible to edit the package metadata after the fact, but it'd solve so many issues for us if you could add that specifier.  What happens now is that every build on python3.6 that did not pin typing-extensions specifically to 4.1.1 now blows up because it installs 4.2 by accident.

Here's the core metadata specification that describes how Requires-Python works: https://packaging.python.org/en/latest/specifications/core-metadata/#requires-python

And looking at pyproject.toml it _looks_ like it has the right requires-python, but somehow pip still installs it wrong?

```
›› pip --version
pip 21.3.1 from ../myvenv/lib/python3.6/site-packages/pip (python 3.6)
›› pip install typing-extensions
Collecting typing-extensions
  Downloading typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Installing collected packages: typing-extensions
Successfully installed typing-extensions-4.2.0
(myvenv) jtratner on C13586jtratner in parsnips_project/on dev
›› pip show typing-extensions
Name: typing_extensions
Version: 4.2.0
Summary: Backported and Experimental Type Hints for Python 3.7+
Home-page:
Author:
Author-email: "Guido van Rossum, Jukka Lehtosalo, Łukasz Langa, Michael Lee" <levkivskyi@gmail.com>
License:
Location: ...myvenv/lib/python3.6/site-packages
Requires:
Required-by:
```

**Comment by JelleZijlstra** [comment]
Sorry for missing that! We can release 4.2.1 with this change and yank 4.2.0. Would you be able to write a PR to fix the metadata?

**Comment by jtratner** [comment]
@JelleZijlstra - Would you be able to point me to how you release the package? Happy to put up PR and see if I can fix problem.

I'm slightly worried I posted something as a general problem that's just a problem with my set up.

**Comment by jtratner** [comment]
I just looked at the metadata for this and it seems like it's set up correctly, so I think I was wrong about this. Going to close this for now because I think I'm wrong about this.

```
›› cat ~/Downloads/typing_extensions-4.2.0/PKG-INFO
Metadata-Version: 2.1
Name: typing_extensions
Version: 4.2.0
Summary: Backported and Experimental Type Hints for Python 3.7+
Keywords: annotations,backport,checker,checking,function,hinting,hints,type,typechecking,typehinting,typehints,typing
Author-email: "Guido van Rossum, Jukka Lehtosalo, Łukasz Langa, Michael Lee" <levkivskyi@gmail.com>
Requires-Python: >=3.7
```

**Comment by jtratner** [comment]
@JelleZijlstra would you be able to post how you deploy this so I can see if I catch anything while debugging?

**Comment by JelleZijlstra** [comment]
https://github.com/python/typing/blob/master/CONTRIBUTING.md#workflow-for-pypi-releases

**Comment by jtratner** [comment]
Thanks @JelleZijlstra (and apologies for adding noise to your day)! In my continuing odyssey to understand why this is occurring, seems like the appropriate requires-python is listed on pypi as well!

<img width="551" alt="Screen Shot 2022-04-18 at 2 26 49 PM" src="https://user-images.githubusercontent.com/1598379/163880604-ef9d3091-7dc3-4e05-b696-6f03593ac700.png">

**Comment by JelleZijlstra** [comment]
I tried locally with pip 21.3.1 on 3.6 and it didn't install 4.2.0. I don't know what's different about your system.

**Comment by jtratner** [comment]
@JelleZijlstra again thanks for your time :) Definitely on my end

**Comment by JelleZijlstra** [comment]
No problem, glad to help. If you figure it out, that could help other users running into this too.

(I noticed my previous messages may have sounded curt; that wasn't my intention.)
