### ISSUE TITLE
Correct “Home” link on pypi `README.rst` ↦ `README.md`

### ISSUE THREAD

**Issue by raabf** [python/typing#1152]
On the pypi distributon page of typing-extensions https://pypi.org/project/typing-extensions/ there is an “Home” link within the “Project links” section on the left site bar.

This “Home” link currently point to 

    https://github.com/python/typing/blob/master/typing_extensions/README.rst

which is an invalid link resulting in an 404, because the file `README.rst` got renamed to `README.md` within the repository. Would be nice if the link could be corrected.

**Comment by srittau** [comment]
Thank you for pointing this out. This should be fixed with the next upload which includes #1150.

**Comment by JelleZijlstra** [comment]
hm, maybe we should put a README.rst back in the repo pointing to the README.md? It may be a while before the next release, and it's not great to have the PyPI link be broken.
