### ISSUE TITLE
4.2.0 is categorized as a minor update but breaks downstream

### ISSUE THREAD

**Issue by lbergelson** [python/typing#1158]
The 4.2.0 release is classified as a minor update (4.1 -> 4.2) so it is automatically picked up by dependency management tools like conda.  However, it contains breaking changes that are incompatible with python 3.6.  This causes tools relying on it to break in confusing ways.

**Comment by hauntsaninja** [comment]
4.2.0 is released with Requires-Python 3.7, so package managers shouldn't automatically be picking it up on 3.6

**Comment by lbergelson** [comment]
Interesting.  Conda doesn't seem to be respecting that.

**Comment by lbergelson** [comment]
Maybe the existence of that annotation is newer than the version of conda in our docker images.

**Comment by lbergelson** [comment]
As far as I can tell we're using the most up to date version of miniconda which supports python 3.6.  It doesn't seem like it understands that toml file.  
Now that we understand what's going on we should be able to downgrade manually.  

It doesn't seem like the toml is sufficient protection, particularly in the case of outdated versions that also by definition use outdated tooling.  It would probably be safer to do like your read the docs site says and bump the major version when making breaking changes.

**Comment by hauntsaninja** [comment]
The TOML file isn't the protection; the actual protection comes from METADATA included in the wheel, as per https://peps.python.org/pep-0345/#requires-python and subsequent PEPs

**Comment by lbergelson** [comment]
Huh, yeah, I see the wheel has that specified. Is it possible that conda  relies on the classifiers instead of the python requirements?

I see is still has this:
```
Classifier: Programming Language :: Python :: 3.6
```

**Comment by hauntsaninja** [comment]
Yeah, we removed the classifier yesterday. If that is what Conda is looking at (which would be surprising to me), we could potentially yank 4.2.0 and make a new release.

I think Conda might just have its own thing: https://github.com/conda-forge/typing_extensions-feedstock
In particular I see this was committed yesterday: https://github.com/conda-forge/typing_extensions-feedstock/commit/8878e8d5c20f00e01fbfe4c52915b894862ecd53

But I just don't know that much about Conda — maybe @synapticarbors could confirm whether there's any action to be taken on typing-extensions' side?

**Comment by lbergelson** [comment]
Ok, I've tracked down the problem.  It seems like the [conda-forge bots](https://github.com/conda-forge/typing_extensions-feedstock/commit/ecf0646b5fa5982a956cac53ba11634a69fa7da9)  treated this as a minor release and automatically updated the recipe.  They are apparently not smart enough to understand `Requires-Python` in the metadata.  

Someone [manually updated it](laterhttps://github.com/conda-forge/typing_extensions-feedstock/issues/29) after the fact.  I'm not sure why we're still resolving the busted thing. 

Anyways, thank you for you help and clarifying what's going on.

**Comment by lbergelson** [comment]
Oh, heh, you wrote the same comment a minute before me!  It seems like what you're doing is probably right and we got bitten by a gap in the automated system downstream.  (I still think it should be 5.0 though... 😄  )

**Comment by lbergelson** [comment]
I'm going to close this since it seems like I misunderstood where the problem is.  Thank you @hauntsaninja for your investigation!

**Comment by synapticarbors** [comment]
Jumping into this late, but I just wanted to add some info. Basically the conda-forge update bot doesn't know anything about dependencies. It mostly just updates the version and the sha256 and then makes updates to the conda-forge build protocol. I usually manually check dependency changes, but missed the 3.7 requirement, and since it didn't cause an import error it looked ok. We do have the option to run `pip check` as part of the testing, which I think should have picked this up.
