### ISSUE TITLE
Type annotations missing for `assert_never`?

### ISSUE THREAD

**Issue by bluenote10** [python/typing#1176]
According to tracking issue https://github.com/python/mypy/issues/5818, `assert_never` was introduced in `typing_extensions` version 4.1.0. At runtime, this clearly seems to work, which I can verify via:

```sh
python -c "from typing_extensions import assert_never"
```

However if I type check the code with mypy it complains at the line of the import:

```
error: Module "typing_extensions" has no attribute "assert_never"
```

I'm not sure if this an issue with `typing_extensions` or mypy though.

In any case, `assert_never` is supposed to have runtime behavior (to raise an assertion), i.e., it is not something that is supposed to be hidden behind a `TYPE_ASSERTION` barrier.

**Comment by AlexWaygood** [comment]
This should work fine if you upgrade to mypy 0.950 :)

**Comment by AlexWaygood** [comment]
The issue is that mypy uses `typing_extensions.pyi` in typeshed for `typing_extensions`, so if something is missing from the typeshed stub, mypy doesn't know about it, even if it exists at runtime. Mypy <=0.942 uses an out-of-date version of the typeshed stub.

**Comment by bluenote10** [comment]
Indeed, works fine with mypy 0.950, thanks and sorry for the noise!

**Comment by AlexWaygood** [comment]
> Indeed, works fine with mypy 0.950, thanks and sorry for the noise!

No worries!
