### ISSUE TITLE
Allow for a recursive data type

### ISSUE THREAD

**Issue by Hu1buerger** [python/typing#1177]
Assume the following datatype of a search tree node.

```python
class STNode(typing.NamedTuple):
    left: STNode
    value: int
    right: STNode

    @staticmethod
    def empty():
        return STNode(None, None, None)
```

Which should match the recursive datatype:

```haskell
data STNode = STNode STNode Int STNode | None
```

or 

```dart
class STNode<T>{
  STNode.leaf(this.value): left = null, right = null;
  STNode(this.left, this.value, this.right);
  
  final STNode<T>? left;
  final T value;
  final STNode<T>? right;
}
```

**Expected Behavior**
I would expect that `left: STNode`  and vice versa for right would be syntactically and semantically valid. 

**Actual Behavior**
The python interpreter raises a NameError for STNode. 

**Your Environment**
Python3.8

**Comment by hauntsaninja** [comment]
Use `from __future__ import annotations` (or quote the type as in https://peps.python.org/pep-0484/#forward-references)
