### ISSUE TITLE
Split typing_extensions into a separate repository?

### ISSUE THREAD

**Issue by srittau** [python/typing#1182]
Currently this repository does multiple things:

* Host typing\_extensions.
* Host the docs.
* Host the dicsussion forum.
* Host typing feature discussions.

While there is of course the general theme of "basic typing related stuff", I think that typing\_extensions is the odd one out here. Its code is basically completely separate from the rest of the repository, tags for typing\_extensions make no sense for the rest of the repository (and vice versa), and the issues are quite technical, compared to the more soft "general" issues.

There also have been complaints about notification spam, 

I think it would ease maintenance to separate those repositories. For example, it could reduce notification spam for people not interested in typing\_extensions.

**Comment by gvanrossum** [comment]
Sounds like a good idea (even though I don't have any of those complaints myself and would probably subscribe to the typing_extensions repo as well).

**Comment by JelleZijlstra** [comment]
Agree that this would be useful. Specifics:

- I'd want to make the new repo `python/typing_extensions`. I believe we need SC approval to add a new repo to the Python org.
- We can use `git filter-branch` magic to preserve history in the new repo.
- The same people can keep commit access to both repos for now. (Though I'd be open to giving more people involved in the typing community access to python/typing in particular.)

**Comment by srittau** [comment]
> * I'd want to make the new repo `python/typing_extensions`. I believe we need SC approval to add a new repo to the Python org.

Could you or @gvanrossum look into this as core developers?

> * We can use `git filter-branch` magic to preserve history in the new repo.

We should also be able to create an empty repository, add that as an origin of a locally checked out copy, and push. This would essentially duplicate the history between both repositories, keeping history and SHAs intact. Unless I'm missing something.

> * The same people can keep commit access to both repos for now. (Though I'd be open to giving more people involved in the typing community access to python/typing in particular.)

+1

**Comment by gvanrossum** [comment]
I asked the SC (https://github.com/python/steering-council/issues/126).

**Comment by srittau** [comment]
Since the SC gave its approval, what's the best way forward? Once the repository has been created, I can set it up and create the necessary PRs, but I'm perfectly fine with someone else doing the work. :) Should we use filter-branch as @JelleZijlstra suggested or use the repo split as suggested by me?

**Comment by JelleZijlstra** [comment]
https://github.com/python/typing_extensions now exists. Notes on what I did:

- Used `git filter-repo` to exclude everything but `typing_extensions/` and `.github/` and move the directory to the top level
- Renamed the main branch to `main` since that's the new norm
- Got CI working again on the new repo
- Filed #1189 here to remove typing-extensions from this repo
- Transferred all open issues with the `topic-typing-extensions` tag to the new repo
- Gave @srittau and the python/typing team write access to the new repo (the team includes Guido, Łukasz and a few other people).

I think that's all that needs to be done, but let me know if I missed something.

Should we announce the new repo somewhere, e.g. on typing-sig?

**Comment by srittau** [comment]
Thanks, @JelleZijlstra! I think an announcement would be a good idea.

**Comment by srittau** [comment]
I've bulk transferred all closed issues as well, only a few old PRs cannot be moved. I suggest we remove the typing-extensions label as well to avoid confusion, even if it would affect those old PRs.

**Comment by JelleZijlstra** [comment]
I also added @hauntsaninja to the new repo and sent an email to typing-sig for visibility. I think that's all, so I'll close the issue.

**Comment by Gobot1234** [comment]
I think the GitHub info also needs updating to remove the mention of typing_extensions

**Comment by srittau** [comment]
Thanks! I've updated the information.
