### ISSUE TITLE
How do I type hint a question that returns a zip object?

### ISSUE THREAD

**Issue by nguyenlethaihoang** [python/typing#1278]
I've got a function that takes an arbitrary amount of lists (or any iterables, for that matter) and sorts them as one. The code looks like this:
![123](https://user-images.githubusercontent.com/81892257/199731608-d231f5c5-ff04-4bbe-94a8-ad0fab3d22c4.png)
How can I accurately type hint the function output?

**Comment by srittau** [comment]
This question is better asked over at our [discussions](https://github.com/python/typing/discussions/categories/q-a).

**Comment by nguyenlethaihoang** [comment]
> How can I accurately type hint the function output?

Thanks
