### ISSUE TITLE
Extending the return type of a function depending on boolean flags

### ISSUE THREAD

**Issue by not-my-profile** [python/typing#1318]
Some web APIs let you choose precisely which information you want to retrieve via parameters. Writing overloads and intersection classes for such APIs by hand quickly becomes unfeasible, as illustrated by the following example:

```python
from typing import Literal, TypedDict, overload

class _BaseInfo(TypedDict):
    base: str

class _BaseInfoExtraA(TypedDict):
    a_1: str
    a_2: str

class _BaseInfoExtraB(TypedDict):
    b: int

## start boring code ##
@overload
def foo(get_a: Literal[False] = ..., get_b: Literal[False] = ...) -> _BaseInfo : ...

class _BaseAndA(_BaseInfo, _BaseInfoExtraA): ...
class _BaseAndB(_BaseInfo, _BaseInfoExtraB): ...

@overload
def foo(get_a: Literal[True] = ..., get_b: Literal[False] = ...) -> _BaseAndA : ...

@overload
def foo(get_a: Literal[False] = ..., get_b: Literal[True] = ...) -> _BaseAndB : ...

class _BaseAndAB(_BaseInfo, _BaseInfoExtraA, _BaseInfoExtraB): ...

@overload
def foo(get_a: Literal[True] = ..., get_b: Literal[True] = ...) -> _BaseAndAB : ...
## end boring code ##

def foo(get_a: bool = False, get_b: bool = False):
    """
    :param get_a: Additionally return the fields from `_BaseInfoExtraA`.
    :param get_b: Additionally return the fields from `_BaseInfoExtraB`.
    """
    raise NotImplementedError()
```

This approach requires $2^n$ overloads for every function with $n$ boolean flags. Writing these overloads by hand therefore obviously isn't feasible for functions with many such flags, e.g. for 10 such flags you would need $2^{10}=1024$ overloads. So I am wondering if there already exists tooling to generate such code or what a good approach for creating such tooling would be. 

I think ideally the generated code would be in a separate `.pyi` file, but I am unsure about two things:

* I think static type checkers for Python don't support using multiple `.pyi` files for the same Python module, so the `.pyi` file would need to additionally contain type stubs for all other APIs defined in the `.py` file. I know that Mypy and Pyright provide CLIs to generate stubs but I'd rather use a more stable API for a tool. Afaik mypy however doesn't have a public API for stubgen and I think the code generator should ideally not depend on Node.js.
* How to denote which overloads should be generated. I am thinking a decorator would make sense e.g. `@gen_overload('get_a', _BaseInfoExtraA)`. The decorator of course wouldn't generate anything but only be there to be recognized by the code generator (which would have to parse the `.py` file). To support more complex cases where the extended type is nested in other types there could be a third parameter:
   ```python
   @gen_overload('get_a', extra=_BaseInfoExtraA, target=_BaseInfo)
   def foo(get_a: bool = False): -> list[_BaseInfo]:
        raise NotImplementedError()
   ```
   Does that make sense? I am not too happy with the name `gen_overload` since it's a bit unspecific.
* Ideally `_BaseInfo`, `_BaseInfoExtraA` and `_BaseInfoExtraB` would also be annotated with `@typing.type_check_only`, however that decorator isn't available on runtime so it couldn't be placed in the `.py` file.

CC: @AlexWaygood, @JelleZijlstra, @srittau, @hauntsaninja, @erictraut

**Comment by erictraut** [comment]
Are you stuck with this API pattern, or do you have the ability to switch to something better? An API that includes a separate bool parameter for every piece of data sounds like a really cumbersome and hard-to-maintain API even without static typing.

If I were stuck with such an API, I think I'd avoid using overloads and simply create a `TypedDict` with the `total` set to False. It would then be up to the caller to verify that the information is present in the dictionary before using it.

**Comment by not-my-profile** [comment]
I want to create accurate Python bindings for the  MediaWiki HTTP API, which makes extensive use of such flags, e.g. [api.php?action=query&prop=info](https://www.mediawiki.org/w/api.php?action=help&modules=query%2Binfo) has 14 such flags, [api.php?action=query&meta=siteinfo](https://www.mediawiki.org/w/api.php?action=help&modules=query%2Bsiteinfo) even has 24 flags. I just realized that overloads aren't feasible anyway for functions with so many flags because $2^{24} = 16777216$ and it takes a couple hundred bytes of Python code for each overload and we certainly don't want a `.pyi` file that is several gigabytes large.

So yes I'll have to go with the `total=False` approach. I think it would be nice if the Python typing ecosystem had something other than overloads that would work here ... I guess the decorator would need to be provided by `typing` and implemented by static type checkers, something like:

```python
@typing.extend_return_type_depending_on_flags(
    _BaseInfo,
    get_a = _BaseInfoExtraA,
    get_b = _BaseInfoExtraB,
)
def foo(get_a: bool = False, get_b: bool = False) -> list[_BaseInfo]:
     raise NotImplementedError()
```

**Comment by not-my-profile** [comment]
Closing this since I realized that the MediaWiki page props can in turn be arbitrarily combined so there are like $2^{34}$ possible return types ... without even taking the prop-specific parameters into account. The complexity of the MediaWiki API is truly beyond the Python type system ... maybe it could be accurately modeled in TypeScript since TypeScript has a Turing-complete type system ... but I don't think the Python type system should gain so much complexity.
