### ISSUE TITLE
Type hinting a non-iterator (non-consumable) iterable

### ISSUE THREAD

**Issue by GideonBear** [python/typing#1319]
I want to annotate a function taking an iterable, that is used multiple times. For example:
```py
def func(thing: Iterable[str]) -> None:
    for _ in range(10):
        for x in thing:
            do_thing(x)
```
`Iterator` is a valid `Iterable`, but passing an `Iterator` to the function will lead to bugs (as it's consumed completely the first time, so empty on all next iterations).
This could potentially be annotated using something like `Intersection[Iterable[str], Not[Iterator]]` if #213 is accepted, but that's still a workaround.
It would be great if there was a type that allows any `Iterable` that cannot be consumed, like a list, but not the iterator of a list.

When searching, the only thing I found was [an unanswered SO question](https://stackoverflow.com/questions/49724778/type-hinting-a-non-generator-non-consumable-iterable).

**Comment by not-my-profile** [comment]
You can use `typing.Callable` as a workaround:

```python
def func(get_iter: Callable[[],  Iterator[str]]):
    for _ in range(10):
        for x in get_iter():
            do_thing(x)

my_strings = ['foo', 'bar']
func(lambda: iter(my_strings))
```

**Comment by GideonBear** [comment]
> You can use `typing.Callable` as a workaround:

@not-my-profile That works, but that would require some really weird, non-intuitive and unneeded things from the callers side. I would prefer putting `thing = tuple(thing)` in the function if a workaround is needed.

**Comment by not-my-profile** [comment]
Right, that also works, however keep in mind that `tuple(thing)` is much less efficient than `iter(thing)` if the thing is large, since the former has to allocate memory for the whole thing.

**Comment by gvanrossum** [comment]
Why can't you just use `Sequence[str]`?

**Comment by GideonBear** [comment]
> Why can't you just use `Sequence[str]`?

Because not all `Iterable`s are `Sequence`s. The function should accept any `Iterable`, as long as it's not an `Iterator`.
For example, a `Set` is an `Iterable`, but not a `Sequence`.
It's pretty easy to work around this, but this is something with a legitimate use that's (AFAIK) not yet possible.

**Comment by gvanrossum** [comment]
Yeah, the practical solution is Sequence|Set|Mapping. The needed negation is years off.

**Comment by antonagestam** [comment]
I'm guessing a protocol that only defines `__iter__` would work well?

**Comment by hauntsaninja** [comment]
That won't work because most iterators are also iterables, e.g. `iter(iter(iter(iter([1,2,3]))))` is totally fine, but OP doesn't want that.

If you want something that is both an sequence and a set, I usually use `typing.Collection`. These have `__len__` so they're probably not going to be consumable.

**Comment by GideonBear** [comment]
> That won't work because most iterators are also iterables, e.g. `iter(iter(iter(iter([1,2,3]))))` is totally fine, but OP wants to exclude e.g. list_iterator.

Sorry, I don't get what you mean. I want to exclude any `Iterator` (which includes `iter(x)`), but include any `Iterable`.

> If you want something that is both an sequence and a set, I usually use `typing.Collection`. These have `__len__` so they're probably not going to be consumable.

That's a good solution, but doesn't include everything, unfortunately. For example, a `KeysView`/`ValuesView` is not a `Collection`, but it is an `Iterable`.
Technically, you could make a `Collection` that's also an `Iterator`, so it could even accept types that aren't compatible. I could even see the use in making a class like that.

**Comment by gvanrossum** [comment]
> Sorry, I don't get what you mean. I want to exclude any `Iterator` (which includes iter(x)), but include any `Iterable`.

Our type system doesn't allow you to express that -- it's like asking for any `Animal` except `Cat`. Adding an "except" clause like that to the type system would be a very difficult operation.

Since there's no solution, I'm going to close this as "won't fix".
