### ISSUE TITLE
Allow newtyping `Never`

### ISSUE THREAD

**Issue by not-my-profile** [python/typing#1322]
For example I'd like to be able to do the following:

```python
from typing import NewType, Never, Union

AllSubmodules = NewType('AllSubmodules', Never)
AllSubmodulesRecursively = NewType('AllSubmodulesRecursively', Never)

def module_spec(
    module: str,
    submodule: Union[str, type[AllSubmodules], type[AllSubmodulesRecursively]],
):
    if isinstance(submodule, str):
        return module + '+' + submodule
    elif submodule == AllSubmodules:
        return module + '+*'
    else:
        return module + '+**'

print(module_spec('bar', 'baz')) # bar+baz
print(module_spec('bar', AllSubmodules)) # bar+*
print(module_spec('bar', AllSubmodulesRecursively)) # bar+**
```

The newtypes in this example are only ever passed directly and never instantiated, so newtyping `Never` seems to be the best way to express this. Attempting to pass `Never` as the second argument to `NewType` is however currently forbidden by type checkers with:

> Expected class as second argument to NewType (Pyright)
> error: Argument 2 to NewType(...) must be subclassable (got "Any") (Mypy)

Prior art: Rust allows it's [never type](https://doc.rust-lang.org/std/primitive.never.html) to be newtyped with e.g. `struct Foo(!);` ... although I cannot think of a use case for this in Rust. In Python types can however be compared during runtime, so there is a good use case as demonstrated by my above example.

Sidenote: In Rust you could just define:

```rust
enum Submodule {
    Specific(String),
    All,
    AllRecursively,
}
```

Since Python doesn't have built-in support for algebraic data types `Union[str, type[AllSubmodules], type[AllSubmodulesRecursively]]` seems to me like a good way to model the same in Python.

CC: @AlexWaygood, @JelleZijlstra, @srittau, @hauntsaninja, @erictraut, @gvanrossum

**Comment by hauntsaninja** [comment]
`type[Never]` doesn't really make sense to me, let alone NewType of Never.

Are you just trying to make a singleton? That's currently best done using an enum or a dedicated class object (where the class has a similar name to the instantiated singleton). See https://peps.python.org/pep-0661/#use-a-single-valued-enum

**Comment by not-my-profile** [comment]
`type[X]` as a parameter type just means that you can pass `X` but not instances of X. I think `type[AllSubmodules]` and `type[AllSubmodulesRecursively]` in my example make perfect sense: you can pass `AllSubmodules` or `AllSubmodulesRecursively` ...  what is unclear about this to you?

I think `AllSubmodules = NewType('AllSubmodules', Never)` is much better than

```python
class _SubmoduleType(Enum):
    AllSubmodules = 'AllSubmodules'
AllSubmodules = _SubmoduleType.AllSubmodules
```

for cases where you do not need an enum type. Especially because we cannot completely hide the "private" enum type since it will still show up in the tooltips from language servers such as Pyright and autogenerated documentation such as [pydoc](https://docs.python.org/3/library/pydoc.html), e.g:

```
DATA
    AllSubmodules = <_SubmoduleType.AllSubmodules: 'AllSubmodules'>
```

leaking such a private type in the API documentation is very much confusing to API users.

**Comment by not-my-profile** [comment]
I just realized that using Never newtypes for a singleton isn't ideal since it doesn't allow e.g. a custom `__str__` implementation for the type, which is possible using the `enum.Enum` or the `Sentinel` approach from [PEP 661](https://peps.python.org/pep-0661/).

You are correct to note that I'm just trying to make a singleton, although I do not want to use `Enum` because as I just mentioned we cannot prevent the leaking of the enum type in documentation. PEP 661 – Sentinel Values, which you linked, seems really interesting but it [unfortunately does not support value-specific type signatures](https://peps.python.org/pep-0661/#specific-type-signatures-for-each-sentinel-value) because of concerns [voiced on the mailing list](https://mail.python.org/archives/list/typing-sig@python.org/thread/NDEJ7UCDPINP634GXWDARVMTGDVSNBKV/#LVCPTY26JQJW7NKGKGAZXHQKWVW7GOGL) that `Literal` special casing would be difficult to implement. @erictraut could you comment on that?

Personally I really think the Python standard library should provide some facility to define a singleton type in a single line of code that can be used with `Literal[...]`.

**Comment by not-my-profile** [comment]
Closing this in favor of taleinat/python-stdlib-sentinels/issues/11. You are all welcome to join the discussion there (I'm not tagging all of you again there, since I don't want to spam you guys any more^^).

**Comment by AlexWaygood** [comment]
> (I'm not tagging all of you again there, since I don't want to spam you guys any more^^)

FYI I'm subscribed to all notifications on this repo, and I suspect all of the other "typing regulars" are as well, so I doubt there's much need to manually tag us in feature requests here :)

**Comment by JelleZijlstra** [comment]
More strongly, please do not ping lots of people when you open an issue, unless you have some very specific reason. As Alex said, many of us will see the issue anyway, and we already get plenty of notifications from GitHub.
