### ISSUE TITLE
Bare Union, Callable and Tuple should not be classes

### ISSUE THREAD

**Issue by gvanrossum** [python/typing#133]
There is no reason for "bare" Union, Callable or Tuple (i.e. without [...]) to be a class. You shouldn't ever write `isinstance(x, Union)` for example, and in their bare form these are not acceptable as annotations either.

**Comment by agronholm** [comment]
I've been using Callable like that. What's wrong with doing so? Should I import Callable from `collections.abc` then? Or always use Callable[..., Any]?

**Comment by gvanrossum** [comment]
Hm, that's a good point. Pretty much anything you can do with collections.abc.X should be possible with typing.X. (This does not apply to things that aren't defined in collection.abc though, so this is not the case for Union, Tuple or List etc.)
