### ISSUE TITLE
typing.Pattern and re.Pattern accept different sets of arguments

### ISSUE THREAD

**Issue by PythonCoderAS** [python/typing#1332]
I accidentally wrote this code: 
```py
from re import Pattern
from typing import Union

def func(pat: Pattern[Union[str], None] = None): ...
```
This is obviously wrong, but Python made no complaint. Changing the imports: 
```py
from typing import Union, Pattern

def func(pat: Pattern[Union[str], None] = None): ...
```
I now get an error: 
```py
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[7], line 3
      1 from typing import Union, Pattern
----> 3 def func(pat: Pattern[Union[str], None] = None): ...

File /usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/typing.py:312, in _tp_cache.<locals>.decorator.<locals>.inner(*args, **kwds)
    310 except TypeError:
    311     pass  # All real errors (not unhashable args) are raised below.
--> 312 return func(*args, **kwds)

File /usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/typing.py:1144, in _SpecialGenericAlias.__getitem__(self, params)
   1142 msg = "Parameters to generic types must be types."
   1143 params = tuple(_type_check(p, msg) for p in params)
-> 1144 _check_generic(self, params, self._nparams)
   1145 return self.copy_with(params)

File /usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/typing.py:231, in _check_generic(cls, parameters, elen)
    229 alen = len(parameters)
    230 if alen != elen:
--> 231     raise TypeError(f"Too {'many' if alen > elen else 'few'} arguments for {cls};"
    232                     f" actual {alen}, expected {elen}")

TypeError: Too many arguments for typing.Pattern; actual 2, expected 1
```

I wonder why this is the case.

**Comment by JelleZijlstra** [comment]
`re.Pattern` is a PEP 585 alias, and those accept any arguments without checking them, for simplicity of implementation. `typing.Pattern` is implemented in the Python code in `typing.py` and does check its arguments. You'll see the same with `list` vs. `typing.List`.

**Comment by Kentzo** [comment]
@JelleZijlstra Am I understanding is right that aliases are less type-safe than aliased?

**Comment by hauntsaninja** [comment]
(this is a somewhat tongue-in-cheek response)

Define "type-safe" ;-) Using PEP 585 aliases will cause your program to crash strictly less often from TypeErrors. Since annotations shouldn't really affect runtime behaviour those TypeErrors usually aren't concealing further TypeErrors.

If you're using static type checking your static type checker will alert you to the incorrect annotation; if you're using runtime type checking, they should often be able to do this too.

**Comment by Kentzo** [comment]
idk but these are not "aliases" as they do not match the behavior to a T. Had I faced this I'd be surprised too as this is not documented as far I can tell.

**Comment by PythonCoderAS** [comment]
I think one of the things that tripped me up is that Pycharm is not erroring out at these. Time to file another bug report there.
