### ISSUE TITLE
Module resolution order as per PEP 561

### ISSUE THREAD

**Issue by not-my-profile** [python/typing#1334]
[PEP 561 currently states the following](https://peps.python.org/pep-0561/#type-checker-module-resolution-order) module resolution order:

> 1. Stubs or Python source manually put in the beginning of the path. Type checkers SHOULD provide this to allow the user complete control of which stubs to use, and to patch broken stubs/inline types from packages. In mypy the `$MYPYPATH` environment variable can be used for this.
> 2. User code - the files the type checker is running on.
> 3. Stub packages - these packages SHOULD supersede any installed inline package. They can be found at `foopkg-stubs` for package `foopkg`.
> 4. Inline packages - if there is nothing overriding the installed package, and it opts into type checking, inline types SHOULD be used.
> 5. Typeshed (if used) - Provides the stdlib types and several third party libraries.

Unless I am missing something the 4th step really should be named "packages with `py.typed` marker files" because it is totally possible to distribute a package with e.g. the following files:

```
mypackage
├── __init__.py
├── __init__.pyi
└── py.typed
```

And type checkers will recognize `__init__.pyi` within the 4th step of the above module resolution order but this is not an "inline package" since the types are not defined inline in `__init__.py` but instead in a separate type stub file `__init__.pyi`.

This appears to be an oversight in the PEP ... so I think the wording of the 4th step should be amended to reflect the standard practiced by type checkers.

**Comment by srittau** [comment]
Cc @ethanhs

**Comment by ethanhs** [comment]
Yes, the wording should be as you suggest. Would you like to submit a PR to the PEPs repo?

**Comment by not-my-profile** [comment]
Yeah I'll do that, I'll ping you in the PR when I open it :)
