### ISSUE TITLE
Cannot extend all protocols

### ISSUE THREAD

**Issue by SimpleArt** [python/typing#1343]
Related: #561

Previously subclassing `typing.Iterable` with `typing.Protocol` raised an error because `typing.Iterable` was not an actual protocol. This specific problem was fixed but there are other protocols which are not actual protocols, such as `typing.AbstractSet`.

My specific use-case is creating particularly spurred by the following line:

https://github.com/python/cpython/blob/144aaa74bbd77aee822ee92344744dbb05aa2f30/Lib/_collections_abc.py#L9

For example, if I wanted to extend `collections.abc.Set` to include the missing methods mentioned, I would approach it something like this:

```python
# protocols.py
import typing


# Created for consistency and `isinstance` usage.
# Causes the mentioned error.
class AbstractSet(typing.AbstractSet, typing.Protocol):
    ...
```

```python
# collections_abc.py
import protocols
import collections.abc

# Created to provide default implementations.
class AbstractSet(collections.abc.Set, protocols.AbstractSet):
    ...
```

It seems to me that the current fix for users is to simply not subclass the protocols and write out the entire protocol themselves.

**Comment by SimpleArt** [comment]
I just realized that:

- `typing.AbstractSet` and similar are deprecated.
- They were intended to be generic versions of their counterparts, not protocols.

So if you want protocols, you'll need to fully implement them from scratch.

**Comment by JelleZijlstra** [comment]
Yes, in general only the very simple (1-2 methods) abstract types were made into protocols. The more complex ones (Sequence, Mapping, etc.) aren't.
