### ISSUE TITLE
Type-hint instances of types passed as TypeVarTuple?

### ISSUE THREAD

**Issue by harenbrs** [python/typing#1347]
Say I have a function like this that tries to convert a given value to any of a list of given classes:

```python
def convert(obj: Any, *to_classes):
    for class_ in to_classes:
        try:
            return class_(...)
        except:
            pass
```

Can `TypeVarTuple` be used to annotate `*to_classes` along with the corresponding return type? I tried the following:

```python
Ts = TypeVarTuple('Ts')

def convert(obj: Any, *to_classes: Unpack[Ts]) -> Union[Unpack[Ts]]:
    for class_ in to_classes:
        try:
            return class_(...)
        except:
            pass
```

but that results in hints like `Type[A] | Type[B]` rather than `A | B` (for passed types `A`, `B`). Is there some way to resolve to instances of the passed types?

**Comment by erictraut** [comment]
I don't think there's a way to do this with `TypeVarTuple`, but you can use an unpacked `tuple` instead.

```python
from typing import Any, TypeVar, Unpack
T = TypeVar("T")

def convert(obj: Any, *to_classes: Unpack[tuple[type[T], ...]]) -> T | None:
    for class_ in to_classes:
        try:
            return class_(...)
        except:
            pass

x = convert(1, int, str)
reveal_type(x)  # int | str | None
```

(Note: This causes the latest version of mypy to crash, but it works fine in pyright.)

**Comment by harenbrs** [comment]
Brilliant, works perfectly. Thanks!
