### ISSUE TITLE
Add covariant/contravariant/invariant properties to a `TypeVar` for binding different `TypeVar`s

### ISSUE THREAD

**Issue by erezinman** [python/typing#1354]
When constructing a complex interface, one sometimes wish to use all the variants of the same `TypeVar`. For example:

```python
T = TypeVar('T')
T_co = TypeVar('T_co', covariant=True)
T_cont = TypeVar('T_cont', contravariant=True)

class Task(Generic[T]):
    
    def run(self, var: T) -> T:
        pass
    
    def run_multiple(self, *others: 'Task[T]') -> Iterable[T_co]:
        pass

    def chain(self, other: 'Task[T_cont]') -> 'Task[T_cont]':
        pass
```

AFAIK, there's no way to relate the different variables. My suggestion is to add variations of the same `TypeVar`. Best described in code:
```python

T = TypeVar('T')
T_co = T.cov
T_cont = T.cont
```

Or even without renaming:
```python

T = TypeVar('T')

class Task(Generic[T]):
    
    def run(self, var: T) -> T:
        pass
    
    def run_multiple(self, *others: 'Task[T]') -> Iterable[T.cov]:
        pass

    def chain(self, other: 'Task[T.cont]') -> 'Task[T.cont]':
        pass
```

That is, I suggest adding the following properties/members to each `TypeVar`: `T.inv` or `T.invariant`, `T.cont` or `T.contravariant`, and `T.cov` or `T.covariant`. This is backward compatible since if one defines `T_co = TypeVar('T_co', covariant=True)` then `T = T_co.inv` will have the same meaning as before. 

Moreover, to simplify the syntax, `TypeVar` could be extended with the `__pos__`, `__neg__` and `__inv__`  dunder functions as shortcuts. The above example using these shortcuts will be:

```python

T = TypeVar('T')

class Task(Generic[T]):
    
    def run(self, var: T) -> T:
        pass
    
    def run_multiple(self, *others: 'Task[T]') -> Iterable[+T]:
        pass

    def chain(self, other: 'Task[-T]') -> 'Task[-T]':
        pass
```

It should be noted that this is in compliance with the current syntax. For example:

```python
>>> Generic[TypeVar('T', covariant=True), TypeVar('S', contravariant=True), TypeVar('H')]
typing.Generic[+T, -S, ~H]
```

**Comment by erezinman** [comment]
A different example (and maybe more correct), could be:

```python
class Sequence(Collection[T]): ...

class List(Sequence[+T]): ...
```

(Similar to this [example](https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)#Data))

**Comment by erictraut** [comment]
I think you may misunderstand how TypeVars and variance work. A TypeVar's variance must be the same everywhere it's used within the class, function or type alias it is scoped to. It can't be invariant in some places, covariant in some places, and contravariant in other places. It therefore doesn't make sense to "relate" different type variables.

You may want to re-read PEP 483 and 484 for more details about how variance works. Many users find the concept of variance confusing. You may also find draft PEP 695 interesting. It proposes to eliminate the need to specify variance and have the type checker infer the variance from the type variable's usage.

**Comment by erezinman** [comment]
@erictraut You may be correct, I will. Thanks.
