### ISSUE TITLE
allow `typing.Annotated` to be generic in its metadata

### ISSUE THREAD

**Issue by DominiqueGarmier** [python/typing#1386]
I am currently using `typing.Annotated` to annotate `torch.Tensor` shapes. And I have the following usecase

```python
from typing import Annotated

x: Annotated[torch.Tensor, dtype, d1, d2] = ...
```

Note that `dtype`, `d1`, `d2` don't have to be types (as an example dtypes aren't types in pytorch). However to avoid code duplication it would be nice to allow syntax like:

```python
Tensor: TypeAlias = Annotated[torch.Tensor]
x: Tensor[dtype, d1, d2] = ...

# with
Tensor[dtype, d1, d2] == Annotated[torch.Tensor, dtype, d1, d2]
```

I currently achieve this using a mypy-plugin and a custom implementation of `Tensor`. Perhaps in the future we would like to allow non-type generics in general. [PEP646](https://peps.python.org/pep-0646/#summary-examples) mentions some of the same ideas.

**Comment by erictraut** [comment]
This proposal doesn't compose well with other type features, so I think it would be a hard sell to get the Python static typing community to adopt it. Here are some cases where it would introduce ambiguities in the type system.

1. Generic type aliases. A type alias can be generic if one or more type variables are used in its definition. The number of type parameters then determines how many type arguments are expected when specializing the type alias. If you add one or more type variables to your example, it becomes unclear how the resulting use of the type alias would be interpreted. Presumably, the first _n_ arguments to the alias would map to real type arguments and any subsequent ones would be interpreted as additional `Annotated` arguments?

```python
MyDict: TypeAlias = Annotated[dict[_K, _V]]
x: MyDict[str, str, "another"[
```

2. Variadic type variables. PEP 646 introduced `TypeVarTuple` which accept a varying number of type arguments. 

```python
MyAlias: TypeAlias = Annotated[MyVector[*Ts]]
x: MyAlias[str, str, float, float, "another"] # Not clear how this should be interpreted by a type checker
```

3. Default type arguments. PEP 696 (which is still in draft form) proposes to add default values for type variables. 

```python
_TStr = TypeVar("_TStr", default=str)
MyAlias: TypeAlias = Annotated[dict[_K, _TStr]]
v1: MyAlias[str, "another"] # Not clear how this should be interpreted by a type checker
```

4. Unions. A type alias can contain unions. It's unclear what happens in this case.

```python
MyAlias: TypeAlias = Annotated[torch.Tensor] | float | Annotated[str]
x: MyAlias["a", "b"] # Not clear what this means
```

There are probably other complications that I'm not thinking of currently, but I think the above list is sufficient to show how this proposal probably won't work.

**Comment by DominiqueGarmier** [comment]
Yes, that makes sense. I haven't though about mixing type and non-type generics. Thanks for your explanation!
