### ISSUE TITLE
pip install error version 3.10.0.0

### ISSUE THREAD

**Issue by matheus-mloptimize** [python/typing#1403]
Hi, guys! I was trying to install the package through pip install and when I set the package version 3.10.0.0 it happened this message:

"ERROR: Could not find a version that satisfies the requirement typing==3.10.0.0 (from versions: 3.5.0b1, 3.5.0, 3.5.0.1, 3.5.1.0, 3.5.2.2, 3.5.3.0, 3.6.1, 3.6.2, 3.6.4, 3.6.6, 3.7.4, 3.7.4.1, 3.7.4.3)"

I took this version from pypi.org (https://pypi.org/project/typing/)

I fixed my problem choose the 3.7.4.3 package version. It's just to report the error.

**Comment by hauntsaninja** [comment]
`typing` has been in the standard library since Python 3.5, so you should never need to install https://pypi.org/project/typing/

If you're using Python 3.4 I *strongly* recommend upgrading, that version has been dead for over four years.

**Comment by matheus-mloptimize** [comment]
Thanks, @hauntsaninja!
