### ISSUE TITLE
[BUG] `Union` should expand `TypeVarTuple`.

### ISSUE THREAD

**Issue by randolf-scholz** [python/typing#1442]
```python
from typing import TypeVarTuple, Union
import random

Ts = TypeVarTuple("Ts")

def random_item(*items: *Ts) -> Union[*Ts]:
    """Chooses a random input"""
    return random.choice(items)

reveal_type(random_item(1, "apple", None))  # should be int | str | None
```

However, `Union[*Ts]` simplifies to `*Ts` which is a `typing._UnpackGenericAlias`.

**Comment by AlexWaygood** [comment]
Please clarify whether you believe there is a bug in the specification, a bug in a specific type checker, or a bug in the behaviour at runtime

**Comment by randolf-scholz** [comment]
Nevermind, `pyright` seems to check this with proper configuration. I would suggest appending something like this as example to the `TypeVarTuple`-PEP.
