### ISSUE TITLE
Fix the broken mess that is the way python typing is touted.

### ISSUE THREAD

**Issue by DiscordLiz** [python/typing#1469]
[Since I was asked to bring this here instead.](https://github.com/microsoft/pyright/issues/5933)

1. People are building things on top of typing that aren't typing
2. There is no single spec for typing, there's a collection of peps that type checkers dont adhere to, but instead make their own decisions on while claiming to be a type checker for python.
3. When people who find typing obnoxious get told just don't use it, they ignore that the ecosystem is pushing it. IDEs used to handle autocomplete and suggested parameters from docstrings and AST, now they don't and use typing.
4. When people who want typing to follow the ideas of type theory and get the benefits of doing so, they get told python typing won't ever be sound, go use another language.
5. It's an echo chamber because you push out anyone who actually wants to improve typing for people who want a good type system because it might be "too noisy" to people who don't.

So fix it. Stop pushing typing on people who don't want it, and make it actually work properly for those who do.

**Comment by JelleZijlstra** [comment]
I don't think anything productive will come out of this issue.

**Comment by AlexWaygood** [comment]
FYI, purely from a pragmatic point of view, you're pretty unlikely to persuade anybody of your point of view if you start telling unpaid volunteers on the internet, whom you've never met, that the ecosystem they've invested large amounts of their free time into improving is a "broken mess" and that it's an urgent priority for them to fix it.
