### ISSUE TITLE
`Unused` type ?

### ISSUE THREAD

**Issue by TruncatedDinosour** [python/typing#1499]
hello

i run into problems sometimes when i have multiple unused arguments, for example : 

```py
    def get_func(
        self,
        clipboard: Any,
        selection_data: Any,
        info: Any,
        data: Any,
    ) -> None:
        """gets clipboard"""
        selection_data.set("BYTES", 8, data)

    def clear_func(self, clipboard: Any, data: Any) -> None:
        """clears clipboard"""
```

and linters dont like this, so maybe `typing` could have an `Unused` type ?

i mean currently ion have a type but i have this : 

```py
from typing import Any


class Unused:
    def __init__(self, *args: Any) -> None:
        del args

  def get_func(
        self,
        clipboard: Any,
        selection_data: Any,
        info: Any,
        data: Any,
    ) -> None:
        """gets clipboard"""
        Unused(clipboard, info)
        selection_data.set("BYTES", 8, data)

  def clear_func(self, clipboard: Any, data: Any) -> None:
        """clears clipboard"""
        Unused(clipboard, data)
```

which works fine, but maybe it should b a type like `Unused[int]` or `Unused[Any]` or smt

**Comment by erictraut** [comment]
It is very common in Python code for parameters to go unused, so I'm surprised that linters would flag that as a potential error. Which linter are you using, and is this rule enabled by default?

In any case, this doesn't seem to be related to static typing, so it probably doesn't make sense to add it to the static type system. It could be supported by linters as a (non-typing) annotation using the `Annotated` mechanism described in [PEP 593](https://peps.python.org/pep-0593/). Linter authors would need to agree on a standard for this.

**Comment by hauntsaninja** [comment]
I agree with Eric that this doesn't belong in the type system. While `Annotated` is fine, I'm unsure why this needs a special mechanism at all. Your `unused` trick already just works. And it's unclear to me why having special cased symbols or annotations would be better than `# noqa: unused-arg` or whatever.

(Note that if you have an unused argument, but you'd like a type checker to complain if someone tries to pass it, annotating it as `Never` will usually do the trick)

**Comment by TruncatedDinosour** [comment]
> It is very common in Python code for parameters to go unused, so I'm surprised that linters would flag that as a potential error. Which linter are you using, and is this rule enabled by default?
> 
> In any case, this doesn't seem to be related to static typing, so it probably doesn't make sense to add it to the static type system. It could be supported by linters as a (non-typing) annotation using the `Annotated` mechanism described in [PEP 593](https://peps.python.org/pep-0593/). Linter authors would need to agree on a standard for this.

im using the pyright linter, but ye, i guess o

**Comment by erictraut** [comment]
> im using the pyright linter, but ye, i guess o

I'm the author of pyright, so I can speak to this issue. First, I don't consider pyright a linter. It's a type checker. Second, pyright never emits an error for unused parameters. It does emit a "tagged" hint that tells your editor to display unused variables as "grayed out". (It emits these tagged hints only if the editor indicates that it supports them.) For example, here is how VS Code displays these:

![image](https://github.com/python/typing/assets/7040122/73e23b25-a1f9-4a39-bc29-183782e33c12)

Some editors unfortunately display these tagged hints the same as other diagnostics. I consider that a bug (or at least a design flaw) in those editors. If you're using one of those editors, you may want to disable tagged hints and/or report the issue to the maintainers of your editor.

**Comment by TruncatedDinosour** [comment]
> > im using the pyright linter, but ye, i guess o
> 
> I'm the author of pyright, so I can speak to this issue. First, I don't consider pyright a linter. It's a type checker. Second, pyright never emits an error for unused parameters. It does emit a "tagged" hint that tells your editor to display unused variables as "grayed out". (It emits these tagged hints only if the editor indicates that it supports them.) For example, here is how VS Code displays these:
> 
> ![image](https://user-images.githubusercontent.com/7040122/278827432-73e23b25-a1f9-4a39-bc29-183782e33c12.png)
> 
> Some editors unfortunately claim that they support these tagged hints but then display them the same as other diagnostics. I consider that a bug (or at least a design flaw) in those editors. If you're using one of those editors, you may want to disable tagged hints and/or report the issue to the maintainers of your editor.

a

well idk, it still annoys me seeing those things, it makes me feel like the code has a warning or smt, and when i run pyright it also throws tht and i hate tht so i hack around it sometimes, oh well tho

![image](https://github.com/python/typing/assets/71613062/ae14be32-f577-40ce-a1df-dba00d7cc440)

great work btw

**Comment by gvanrossum** [comment]
“Bye lol”

**Comment by TruncatedDinosour** [comment]
> “Bye lol”

hm ?

**Comment by TruncatedDinosour** [comment]
i mean theres no interest in implementing this feature in `typing` and i do agree tht this isnt related to typing, but its the thing tht made most sense at the time for me, so i see no point in discussing this further

idk where else itd make sense

til then ill probably continue using `del x` or `Unused(x)` or smt, would b nice if python had smt like `(void)x` tho

**Comment by erictraut** [comment]
> it still annoys me seeing those things

I'd find that annoying too. My point is that this is a problem with the way your editor is working (or is configured), not with pyright or with the type system. You should look to address the underlying problem, not complicate the Python type system as a workaround. I understand that one's choice in editors is very personal, but you might want to try switching editors if your current one is annoying you.

**Comment by TruncatedDinosour** [comment]
> > it still annoys me seeing those things
> 
> I'd find that annoying too. My point is that this is a problem with the way your editor is working (or is configured), not with pyright or with the type system. You should look to address the underlying problem, not complicate the Python type system as a workaround. I understand that one's choice in editors is very personal, but you might want to try switching editors if your current one is annoying you.

ye, ofc, i should change tht, welp, thanks for responding, have a rest of ur day

**Comment by vitaly-krugl** [comment]
@hauntsaninja  wrote:
> I agree with Eric that this doesn't belong in the type system. While `Annotated` is fine, I'm unsure why this needs a special mechanism at all. Your `unused` trick already just works. And it's unclear to me why having special cased symbols or annotations would be better than `# noqa: unused-arg` or whatever.
> 
> (Note that if you have an unused argument, but you'd like a type checker to complain if someone tries to pass it, annotating it as `Never` will usually do the trick)

I tried `Never` with PyCharm, but it still displayed the "unused parameter" warning. So, this didn't suppress the warning:
```
from typing import Never

def mark_test_complete(self, node: WorkerController, item_index: int,
                           duration: Never):
```
It's just a shame that we have to resort to executing unnecessary statements, such as `del duration` or `assert duration is duration`, etc., just to suppress specific "unused parameter" warnings in some popular IDEs. I wouldn't want to suppress all "unused parameter" warnings since it might hide errors, only suppress the ones that I determined are legitimately unused.

**Comment by TruncatedDinoSour** [comment]
> @hauntsaninja wrote:
> 
> > I agree with Eric that this doesn't belong in the type system. While `Annotated` is fine, I'm unsure why this needs a special mechanism at all. Your `unused` trick already just works. And it's unclear to me why having special cased symbols or annotations would be better than `# noqa: unused-arg` or whatever.
> > (Note that if you have an unused argument, but you'd like a type checker to complain if someone tries to pass it, annotating it as `Never` will usually do the trick)
> 
> I tried `Never` with PyCharm, but it still displayed the "unused parameter" warning. So, this didn't suppress the warning:
> 
> ```
> from typing import Never
> 
> def mark_test_complete(self, node: WorkerController, item_index: int,
>                            duration: Never):
> ```
> 
> It's just a shame that we have to resort to executing unnecessary statements, such as `del duration` or `assert duration is duration`, etc., just to suppress specific "unused parameter" warnings in some popular IDEs. I wouldn't want to suppress all "unused parameter" warnings since it might hide errors, only suppress the ones that I determined are legitimately unused.

eh i honestly see no point in arguing this, its eh, if u wanna u can fork the linters u use and change them, although discussing here is probably not gonna change anything as the developers r not fond of adding this so eh
