### ISSUE TITLE
Allow type-hints for Exception arguments (BaseException.args)

### ISSUE THREAD

**Issue by aha79** [python/typing#1519]
The constructor of Exception (and BaseException) takes a variable number of arguments. These are accessible as `Exception.args`. It would be nice to be able to type-hint exception arguments

Currently the exception arguments are of unknown type within 'except': Example:
     
     class ItemNotFoundError(Exception):
          def __init__(self, pos: int, item: Item): 
                super().__init__(pos, item)
     

    try:
        ...
    except ItemNotFoundError as e:
        pos, item = e.args     # unpack arguments  ==> type information is lost 
       # Note: mypy and pylance assume `args` to be `tuple[Any,...]`
(See also example in https://docs.python.org/3/tutorial/errors.html#handling-exceptions)

Even built in Exceptions have typed arguments:

https://docs.python.org/3/library/exceptions.html#OSError
https://docs.python.org/3/library/exceptions.html#SyntaxError

I wished we could write something like this

     class ItemNotFoundError(Exception[int, Item]):   # <= would be nice to be able to do this
          def __init__(self, pos: int, item: Item): 
                super().__init__(pos, item)

This would allow for cleaner API design where exceptions (as part of the API contract) clearly spectify the payload they carry with them,

**Comment by erictraut** [comment]
You can simply add a type annotation to your exception class.

```python
class ItemNotFoundError(Exception):
    args: tuple[int, Item]

    def __init__(self, pos: int, item: Item):
        super().__init__(pos, item)
```
