### ISSUE TITLE
Switch to `main`?

### ISSUE THREAD

**Issue by srittau** [python/typing#1539]
Just to repeat my arguments from python/typeshed#8956:

> I don't want to go into the political reasons for renaming the branch, but in my opinion there is a clear push to standardize on the new name main. I believe there was also a SC decision that all projects under the python org should eventually change to that name, although we haven't been approached about this. But CPython has switched (and the stub_uploader always used main). Selfishly, I also renamed the branches in most of my projects, with typeshed being one of the last still using master.

**Comment by gvanrossum** [comment]
Yeah, I’m for it.

**Comment by JelleZijlstra** [comment]
Let's do it. @srittau if you have the right permissions, go ahead, otherwise I'll do it when I get a chance.

**Comment by gvanrossum** [comment]
There are a few other repos too, typing, and mypy.

**Comment by srittau** [comment]
It is done. I also checked the readthedocs settings, but it seems that nothing needs to be changed. I also found no references to "master" in the source (except to typeshed's master, for which I will send a PR shortly).

**Comment by srittau** [comment]
>  I also checked the readthedocs settings, but it seems that nothing needs to be changed.

And it seems I was wrong. Fixed the build on readthedocs.
