### ISSUE TITLE
PR preview

### ISSUE THREAD

**Issue by srittau** [python/typing#1583]
Per Guido:

> We should have a workflow to preview the Sphinx-generated HTML, as we have for CPython.

This seems to be fairly easy: https://docs.readthedocs.io/en/stable/pull-requests.html. I'll investigate.

**Comment by srittau** [comment]
The preview build works, but it's not reported back to GitHub yet: https://typing--1578.org.readthedocs.build/en/1578/.

**Comment by srittau** [comment]
The preview build is now linked in a PR under "Checks". When clicking "Details" on the readthedocs check, you'll get sent to the preview build. It would be nicer to have a link directly in the PR comments, but I think this will do for now.

**Comment by JelleZijlstra** [comment]
Thank you!
