### ISSUE TITLE
Outdated stub package guidance

### ISSUE THREAD

**Issue by WMOkiishi** [python/typing#1603]
The guidance for distributing stub packages on the "Type Stubs" page ([link](https://typing.readthedocs.io/en/latest/source/stubs.html#distribution)) still recommends using the `types-<package>` naming convention. If I've understood recent updates (see #1577) correctly, this is (now?) only preferred for typeshed stub distributions. This section is why I published the stub package I maintain with the `types-` prefix, so, it should probably be changed if that's not the way things are meant to be done.

**Comment by hauntsaninja** [comment]
Thanks, opened a PR to fix this.

It's always been the case that `types-` was meant to indicate typeshed stubs, we've just not done a good job of communicating that / what we really wanted was namespaces on PyPI.
