### ISSUE TITLE
Abstract classmethod returning object of type cls: "is not a supertype of its class"

### ISSUE THREAD

**Issue by NiklasRosenstein** [python/typing#1611]
In https://github.com/python/typing/issues/254 there's an example for describing when a `@classmethod` returns an instance of the corresponding class:

```py
from typing import TypeVar

_T = TypeVar("_T")

class Foo:
    @classmethod
    def create(cls: type[_T]) -> _T:
        return cls()
```

> https://mypy-play.net/?mypy=latest&python=3.12&gist=5f7aa98d4f4d7842154638aa553d77ff

But the same concept when using `@abstractclassmethod` does not work:

```py
from typing import TypeVar
from abc import ABC, abstractclassmethod

_T = TypeVar("_T")

class Foo(ABC):
    @abstractclassmethod
    def create(cls: type[_T]) -> _T:
        return cls()
```

> https://mypy-play.net/?mypy=latest&python=3.12&gist=ad4ddcab59b5860cd87309cc0576b2e0

The error:

```
main.py:8: error: The erased type of self "Type[builtins.object]" is not a supertype of its class "__main__.Foo"  [misc]
Found 1 error in 1 file (checked 1 source file)
```

> Mypy 1.8.0

**Comment by hauntsaninja** [comment]
`@abstractclassmethod ` has been deprecated since Python 3.3
