### ISSUE TITLE
Extra key of TypedDict

### ISSUE THREAD

**Issue by STofone** [python/typing#1645]
I am using pyside6 webview as gui(use typescript). It makes me feel like the Python is very backwards when i receive data from typescript. Any type in ts use flexibile key can not be support by TypedDict and have to use raw dict.
I think it also happened when using django.
The last time i get this feeling is when i use java springboot to receive data from frontend and have to use Map.
As a dynamically typed language, python lose its flexibility.
[relative issue](https://github.com/python/mypy/issues/4617)
[discuss from discuss.python.org](https://discuss.python.org/t/add-to-typeddict-new-argument-for-extra-keys/32526)
```typescript
type JSONContent = {
  type?: string
  attrs?: Record<string, any>
  content?: JSONContent[]
  marks?: {
    type: string
    attrs?: Record<string, any>
    [key: string]: any
  }[]
  text?: string
  [key: string]: any
}
```

**Comment by PIG208** [comment]
You might be interested in [PEP-728](https://discuss.python.org/t/pep-728-typeddict-with-typed-extra-items/45443/83), which is partially inspired by TypeScript's Index Signatures.

**Comment by STofone** [comment]
> You might be interested in [PEP-728](https://discuss.python.org/t/pep-728-typeddict-with-typed-extra-items/45443), which is partially inspired by TypeScript's Index Signatures.

Thanks, this is exactly what i want.

**Comment by STofone** [comment]
> You might be interested in [PEP-728](https://discuss.python.org/t/pep-728-typeddict-with-typed-extra-items/45443), which is partially inspired by TypeScript's Index Signatures.

Thanks, this is exactly what i want.
