### ISSUE TITLE
Incorporate PEP 483 into the spec

### ISSUE THREAD

**Issue by carljm** [python/typing#1666]
I don't know if this was already considered and rejected (I didn't find an existing issue about it), but I noticed today that some key concepts and terms used in the typing spec (e.g. the consistent-with relation) don't seem to be clearly defined anywhere in the spec.

I think the way to address this that would be most in the spirit of the current spec would be to incorporate PEP 483 (possibly with some edits) into the spec. As far as I can see, it wasn't included in the original PEP-concatenation that formed the initial spec; was that intentional?

**Comment by JelleZijlstra** [comment]
I think I didn't include it because PEP 483 is marked Informational, so it shouldn't be normative. I agree that it would be good to include concepts like "consistent-with" in the spec, but I don't know if PEP 483 is the right formalization to use at this point.

**Comment by superbobry** [comment]
PEP-484 omits quite a few details. For example, it only partially defines is-consistent-with.  I would recommend adopting (or starting with) the definitions in http://bit.ly/python-subtyping by @kmillikin instead.

**Comment by carljm** [comment]
> PEP-484 omits quite a few details

I assume you mean 483 here?

I initially suggested 483 because I thought it might be less controversial, given it is already an accepted PEP. But personally, I like the clarity of the kmillikin spec quite a lot and would be happy to use it as a starting point.

**Comment by superbobry** [comment]
Yes, I did mean PEP-483, although the above is true for PEP-484 as well :)

**Comment by carljm** [comment]
I think this can be considered a duplicate of #1534
