### ISSUE TITLE
Provide typing.Index?

### ISSUE THREAD

**Issue by ncoghlan** [python/typing#171]
The typing module offers `typing.SupportsInt` https://docs.python.org/3/library/typing.html#typing.SupportsInt to indicate acceptance of any object that implements `__int__`.

Would it make sense to offer a typing.Index type to be able to describe interfaces like range and slice definition, sequence indexing and sequence repetition which accept any object with an `__index__` method, but not objects like float, which implement a lossy `__int__` representation?

**Comment by gvanrossum** [comment]
It would probably make some sense eventually, but in practice the int type
is good enough for 99.99% of the cases encountered. (Basically I'm just
triaging this as really low priority -- it's easy enough to add in the
future.)

**Comment by ilevkivskyi** [comment]
Note that there is now `typing.SupportsIndex` in Python 3.8.

**Comment by gvanrossum** [comment]
So we can close this.
