### ISSUE TITLE
Allow multiple `TypeVarTuple` in Generic Classes when they are wrapped.

### ISSUE THREAD

**Issue by randolf-scholz** [python/typing#1754]
[According to the spec, this is not allowed:
](https://typing.readthedocs.io/en/latest/spec/generics.html#multiple-type-variable-tuples-not-allowed)

```python
class Array(Generic[*Ts1, *Ts2]): ...  # Error
```
Since it leads to ambiguity (what is `Array[int, str, bool]`?). However, this ambiguity is not present when the `TypeVarTuples` themselves are wrapped in tuples, for example:

```python
class TupleDict(Mapping[tuple[*Xs], tuple[*Ys]]):
    """Dictionary that maps tuples to tuples."""
```

or

```python
from typing import Callable, Generic, TypeVar, TypeVarTuple

X = TypeVar("X")
Y = TypeVar("Y")
Xs = TypeVarTuple("Xs")
Ys = TypeVarTuple("Ys")

class Function(Generic[X, Y]):
    def __call__(self, x: X) -> Y: ...

class CartesianProductOfFunctions(Function[tuple[*Xs], tuple[*Ys]]):
    def __init__(self, fns: list[Callable]):
        self.fns = fns

    def __call__(self, xs: tuple[*Xs]) -> tuple[*Ys]:
        return tuple(f(x) for f, x in zip(self.fns, xs))
```

Code sample in [pyright playground](https://pyright-play.net/?code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAqiApgGoCGIBArggDbEA0UA4sSsSEgMbNEJlKzAMLk6dcgCMGAKFCQo3MOOLcYSMCgDOAOindM2XPgCy5BMnQyZADSgBeQiQogAFACIb7gJQyAmg5OAi4efj62WoH8glS0DB42WuF%2BkY7RLjT0xKFJvtbcElqRAGLUKGoaKK5sHFzcANo2zH4Aut4AXDJQ3VAAJsTAUAD6Q9xidCOuWsR0wMwAHu1QNt5QALQAfFB%2BSzp71jIF5EVQonjEWkjkKAAK4L3UagDywKXl6pparm8VmvUwcWI9QAVIkWswAVkQSkWm1Oj0%2BgNhkNUEgYJNprNmMBtEs6EgtDB6qJxFIGHCugiepjgDocakoPTrAj%2BoMRmNxBiZnMoPMtEtIQwQWDVptYIDoVoWvCqd0QMQASAUOKsq5gK55qtgLhGQtMMqAF5IBBTbl07QLLTePKszD9FDqeCuXpLXo8ImCoGgqUQiXAmFtdZbN1qf5%2BsG%2BqH%2BqXSylyhXUJV9fKFSKZBgAEXdrjMFlQaDDUYjKqF0dhHTjUHc1azvxQlDgsAAFuR8BBzJFPZ2wCWLjpq%2B4ZEA)

So, what I mean is that while a generic class should be allowed to contain only a single unpacked variadic type, but it should be allowed to hold arbitrarily many non-unpacked variadic types.

**Comment by JelleZijlstra** [comment]
This is still ambiguous. If you write `TupleDict[int, str, bool]`, which elements go to the key type and which go to the value type?

**Comment by randolf-scholz** [comment]
@JelleZijlstra 

`TupleDict.__class_getitem__` should expect precisely two inputs, which are both compatible with `tuple`, so `TupleDict[int, str, bool]` should be an error. An admissible parametrization would be `TupleDict[tuple[int], tuple[str, bool]]`, or  `TupleDict[tuple[int, str], tuple[bool]]` for instance.

**Comment by JelleZijlstra** [comment]
That's not how generics work.

**Comment by randolf-scholz** [comment]
Essentially duplicate of #548.
