### ISSUE TITLE
Proper annotation for instance/classmethod using as callback

### ISSUE THREAD

**Issue by mkurnikov** [python/typing#176]
I'm implementing runtime type checker for the module classes. I have a problem with annotating class/instance methods. 

Suppose I have a class with a method: 
```
class Foo():
	def mymethod(self, x: int, y: int) -> int:
		return x + y
```

And I define a function which expects to have `mymethod()` as passed callback: 
```
def myfunc(cb):
	pass
```

Should I annotate callback with `self` type, like `Callable[[Foo, int, int], int]`, or without it like `Callable[[int, int], int]`? Same thing with classmethod. 

Currently, `inspect.signature()` defines method like that: 

```
In [3]: import inspect

In [4]: str(inspect.signature(Foo().mymethod))
Out[4]: '(x:int, y:int) -> int'
```

so in order to properly check it, I need to do:

```
sign = inspect.signature(argument)
parameters = list(sign.parameters.items())

if inspect.ismethod(argument): 
    parameters.insert(0, ('self', Parameter('self', Parameter.POSITIONAL_ONLY,
                                            annotation=type(argument.__self__))))
```

Is it OK? Am I missing something here? 
It would be nice to have a separate class `Method` to be more clear about the nature of the callback. Signature could be left the same, like `Method[[Foo, int, int], int]`.

UPD. This also plays nicely with the fact that `self` and `cls` attributes will be unannotated in most cases. IDE (and runtime checker) could then cast first argument to `method.__self__` by itself and check it properly.

**Comment by gvanrossum** [comment]
You should definitely annotate myfunc() with `Callable[[int, int], int]`. That is, assuming it calls its cb argument as `cb(0, 0)`.

Since inspect.signature() returns the right thing, I'm a little at a loss here about what your question is -- can you show more of your code so I understand what you are looking for?

**Comment by mkurnikov** [comment]
Ok, in that case, I guess, my suggestion doesn't make much sense. I annotated bounded callbacks with the class as a first argument, which was wrong. With that, I wanted to separate the function 
```
def func(obj: Foo, x: int) -> int: pass
```
and method
```
class Foo(): def myfunc(self, x: int) -> int: pass
```
since for me signatures were the same. 
Thank you for the answer. I'm closing the issue.

**Comment by gvanrossum** [comment]
Glad that works for you!

**Comment by mkurnikov** [comment]
I still want to add `Method` as a subclass for the `Callable`. Mind if I won't create new issue and explain here?

This is the context of the problem: 
I want to restrict a possible `Callable` for the callback to only methods of the current class. I have a `Spider` class, which has generator method, that yields `Request` objects with callbacks. 

```
class MySpider(Spider):
	def parse(self, response):
		...
		yield Request(url, callback=self.parse_article)
		...
```
In `Request` constructor I perform this check to impose the restriction: 
```
inspect.ismethod(callback) and issubclass(callback.__self__.__class__,
                                                                    Spider):
            self.callback = callback
```

Pycharm (as expected) shows an error at `callback.__self__`, because it doesn't know whether it's a method or a function. 

I would be happy, if we would add `Method` class, with signature `Method[Spider][ standard_callable_signature ]` specifically for this case. The notation is a little bit ugly, though, but it's pretty rare use case, so I guess we could tolerate it. 

Even just a subclass `Method` without any additional implementation will do the work. At the very least IDE could perform `inspect.ismethod()` check automatically and impose that restrictions on static analysis phase.

**Comment by gvanrossum** [comment]
I still fail to understand why you want to restrict the callback that way. What's special about methods of the current class (or subclasses) that you want to restrict this? Are you going to reference `callback.__self__` later on? It feels limiting, and it would make it impossible to pass e.g. a lambda or partial that calls a method with some other argument already filled in.

Note that subclassing Callable in typing.py would be complicated, because of the special signature of Callable itself.

**Comment by gvanrossum** [comment]
Are you still interested in pursueing this? Or can we close it?
