### ISSUE TITLE
Signature of ItemsView in typing.py does not match that in typeshed's typing.pyi

### ISSUE THREAD

**Issue by gvanrossum** [python/typing#177]
This came up in https://github.com/python/typing/issues/136#issuecomment-174519086.

There seems to be a bug in the definition of ItemsView in typing.py: it has three type parameters, but its unclear what they mean. When looking at the corresponding definition in typeshed, it actually makes more sense:
```
class MappingView(Sized):
    def __len__(self) -> int: ...

class ItemsView(AbstractSet[Tuple[_KT_co, _VT_co]], MappingView, Generic[_KT_co, _VT_co]):
    def __contains__(self, o: object) -> bool: ...
    def __iter__(self) -> Iterator[Tuple[_KT_co, _VT_co]]: ...
```
Here MappingView is not generic (since Sized isn't), and ItemsView has only two parameters, clearly meant for keys and values, and clarified by the `__contains__` and `__iter__` signatures.

I think we should follow this example.

**Comment by gvanrossum** [comment]
I think this was fixed by my fix for #115. The mapping view objects are now defined as follows:
```
class MappingView(Sized, Iterable[T_co], extra=collections_abc.MappingView):
    pass


class KeysView(MappingView[KT], AbstractSet[KT],
               extra=collections_abc.KeysView):
    pass


class ItemsView(MappingView[Tuple[KT, VT_co]],
                Set[Tuple[KT, VT_co]],
                Generic[KT, VT_co],
                extra=collections_abc.ItemsView):
    pass


class ValuesView(MappingView[VT_co], extra=collections_abc.ValuesView):
    pass
```

(The `Generic[KT, VT_col]` base in ItemsView is technically redundant, but it's there as an example. It should have no effect.)

**Comment by ilevkivskyi** [comment]
I have a questions here. What is the reason to have `Set` in bases for `ItemsView`, probably it should be `AbstractSet`. At least in `collections.abc` both `ItemsView` and `KeysView` inherit from `collections.abc.Set`. Therefore in both cases it is reasonable to use `typing.AbstractSet` which is a generic version of `collections.abc.Set`.

**Comment by gvanrossum** [comment]
Good catch! Probably a sleepy copy/paste from collections.abc. Will fix.
