### ISSUE TITLE
Idenity Type

### ISSUE THREAD

**Issue by julien-blanchon** [python/typing#1777]
I'm trying to type such functions:

```python
def identity[T](*args: T) -> T:
    # Modify the arguments in some way but keep the same type
    ...
    new_args = args
    # Return the modified arguments
    return new_args
```
I would like to be able to have such behaviour:

```python
new_a, new_b, new_c = identity(a, b, c)
```

With a, b and c of type different A, B, C

```[tasklist]
### Tasks
```

**Comment by JelleZijlstra** [comment]
This is already possible:

```python
def identity[*Ts](*args: *Ts) -> tuple[*Ts]:
    return args
```

https://pyright-play.net/?strict=true&code=GYJw9gtgBALgngBwJYDsDmUkQWEMogCmAboQIYA2A%2BvAoQFCMAmhwmLKMS8A2gFQAVAM4BdABR8yINEIBcUQUICUUALQA%2BWAFcEFQv2EjZ9KKYKEYWkCihSZjMgBooAI2cBjKAF52hTtzgxACIyIOcARgiAOgAGJXoiUkoaREIxMnjE8mpaNJdMkmyUujF3eKA
