### ISSUE TITLE
Question about Tuple with ellipsis

### ISSUE THREAD

**Issue by mkurnikov** [python/typing#180]
Does `Tuple` support form of `Tuple[int, str, ...]` with more than one parameter before the ellipsis? It seems that it's not, currently. 

```
class TupleMeta(TypingMeta):
    ...
    def __getitem__(self, parameters):
        if self.__tuple_params__ is not None:
            raise TypeError("Cannot re-parameterize %r" % (self,))
        if not isinstance(parameters, tuple):
            parameters = (parameters,)
        if len(parameters) == 2 and parameters[1] == Ellipsis:
            parameters = parameters[:1]
            use_ellipsis = True
            msg = "Tuple[t, ...]: t must be a type."
        else:
            use_ellipsis = False
            msg = "Tuple[t0, t1, ...]: each t must be a type."
        parameters = tuple(_type_check(p, msg) for p in parameters)
        return self.__class__(self.__name__, self.__bases__,
                              dict(self.__dict__), parameters,
                              use_ellipsis=use_ellipsis, _root=True)
```

I guess, Ellipsis-related check has to be implemented somehow like this: 
```
    if parameters[-1] == Ellipsis:
        parameters = parameters[:-1]
        use_ellipsis = True
```

**Comment by gvanrossum** [comment]
PP 484 is clear on the matter; only one type is allowed (and required) t appear before the ellipsis:

> * Tuple, used by listing the element types, for example
>   ``Tuple[int, int, str]``.
>   Arbitrary-length homogeneous tuples can be expressed
>   using one type and ellipsis, for example ``Tuple[int, ...]``.

**Comment by AlfreG** [comment]
Dear all,
I am puzzled about this, why prior assignment of type is giving me this error while explicit annotation worked?

test.py:5: error: Unexpected "..."
    YY = tuple[int, ...]_

```
from typing import Tuple
YY = tuple[int, ...]

def it_works_fine(par: tuple[int, ...] = (1, 1,) ) -> bool:
    """."""
    return par == (1,1, )

def doesnt_work(par: YY = (1,1,) ) -> bool:
    return par == (1,1, )

def doesnt_work_neither(par: tuple[int, ...] = (1, 1,)  ) -> YY:
    return par
```

**Comment by srittau** [comment]
@AlfreG Your question is probably better suited for our discussion forum: https://github.com/python/typing/discussions

**Comment by luckydonald** [comment]
@srittau I love that you dig this ticket out after 5 years for that comment.

Careful, even if it reads like that, the non-working `Tuple[int, int, str, ...]` can't be written as `Tuple[int, ...]` but you will need `Tuple[Any, ...]` instead.

**Comment by srittau** [comment]
I have no idea what happened here. My answer was clearly not meant for this issue, but I'm not sure which issue it was meant for.

**Comment by erictraut** [comment]
FWIW, if [PEP 646](https://www.python.org/dev/peps/pep-0646/) is accepted, it will enable tuple types like this to be expressed as follows:

`tuple[int, int, Unpack[tuple[str, ...]]]`

(or if the nicer syntax for `Unpack` is approved)
`tuple[int, int, *tuple[str, ...]]`

Mypy doesn't yet contain support for PEP 646, but if you're interested in playing around with it, pyright and pyre both implement the latest draft of the PEP.

**Comment by JelleZijlstra** [comment]
The nicer syntax was approved but will only be in Python 3.11. We'll backport Unpack support to older versions in typing-extensions.

**Comment by erictraut** [comment]
That's great news about the new syntax being approved. Do you recall where you saw that? I'm interested in the details. I presume that the more general syntax change proposed in [PEP 637](https://www.python.org/dev/peps/pep-0637/) was not accepted.

**Comment by JelleZijlstra** [comment]
https://github.com/python/steering-council/issues/59#issuecomment-1016202935
