### ISSUE TITLE
Clarify signification of `Annotation`

### ISSUE THREAD

**Issue by Viicos** [python/typing#1805]
https://github.com/python/typing/pull/1669 Clarified usage of `Final` in dataclasses. The following section was added:

https://github.com/python/typing/blob/42e9118068944e63f4c321f26e4f37f5d77a6d59/docs/spec/qualifiers.rst?plain=1#L179-L181

I believe `Annotation` means `Annotated`? If so, I can open a PR fixing this.

---

Ideally we could also update the [conformance tests](https://github.com/python/typing/pull/1741) to add an extra `final_annotated: Annotated[Final[int], ...]`. It will be interesting to see the output, as mypy seems [to reject it](https://mypy-play.net/?mypy=latest&python=3.12).

**Comment by JelleZijlstra** [comment]
Good call, that should say `Annotated`. And yes, the conformance test suite should be expanded to cover those, and mypy should be fixed to follow the spec here.

**Comment by erictraut** [comment]
The conformance tests [already cover this case](https://github.com/python/typing/blob/01a3dd5b55458625f59ab9c872ca935c1a0f040d/conformance/tests/qualifiers_annotated.py#L99), and mypy's nonconformance [has already been noted](https://github.com/python/typing/blob/01a3dd5b55458625f59ab9c872ca935c1a0f040d/conformance/results/mypy/qualifiers_annotated.toml#L4).
