### ISSUE TITLE
Conformance tests: PEP 702

### ISSUE THREAD

**Issue by InSyncWithFoo** [python/typing#1821]
PEP 702's `@deprecated` has been [a part of the specs](https://typing.readthedocs.io/en/latest/spec/directives.html#deprecated) for a while now, yet there aren't any conformance tests for it. Is it simply because no one have volunteered to do so (in which case I'll be interested in submitting a PR), or are such tests not stored in this repository?

**Comment by erictraut** [comment]
Good catch. I didn't realize these were missing from the conformance suite.

The [@deprecated](https://typing.readthedocs.io/en/latest/spec/directives.html#deprecated) directive doesn't provide core type checking functionality. It's more of a linter or language server feature, but it is still part of the typing spec, so it makes sense to have tests for it.

AFAIK, pyright is currently the only one of the four major type checkers that implements PEP 702.

You're welcome to submit a PR for this, or I'm happy to do so. If you do it, please follow the guidance for conformance tests and use the existing tests as a template. The tests should stick to only the parts that are found in the typing spec, and comments in the test should quote the spec as appropriate.
