### ISSUE TITLE
Need a solution for long signatures in Python 2

### ISSUE THREAD

**Issue by gvanrossum** [python/typing#186]
See https://github.com/python/mypy/issues/1102. I propose to go with this form:
```python
def whatever(
         arg1,  # type: int 
         arg2,  # type: int
         arg3,  # type: int
         arg4,  # type: str
         arg5,  # type: str
         arg6,  # type: str
         ):
    # type: (...) -> float
    # this is not a type comment (note that "..." above is literal)
    return (arg1 + arg2 + arg3 +
            float(arg4) + float(arg5) + float(arg6))
```
(We'll keep the other form too, since it is fine for short signatures.)

**Comment by vlasovskikh** [comment]
Would it be valid to annotate just a few arguments? Only the return type?

**Comment by gvanrossum** [comment]
Yes to both. The proposed semantics of `# type: (...) -> blah` match nicely with that.

In fact it should also be possible to just annotate some arguments and not give the signature at all -- that's like leaving the "-> blah" out from the PY3 form.

However you shouldn't annotate individual arguments *and* have explicit types in the latter; this is invalid:
```
def foo(a # type: int
    ):
    # type: (int) -> int
    pass
```

**Comment by gvanrossum** [comment]
Fixed in the PEP by https://hg.python.org/peps/rev/81c177edf735. Implemented in PyCharm (but not yet in mypy).

**Comment by gvanrossum** [comment]
Also a6e763a936577b7e64f296b1c681298076877b1d in the typing repo.
