### ISSUE TITLE
Be able to handle str/bytes in Python 2/3 code

### ISSUE THREAD

**Issue by brettcannon** [python/typing#19]
In Python 2/3 code, what str and bytes represent can be considered somewhat muddled depending under what interpreter you are executing (and unicode should be simply left out). I'm not sure if the preferred approach is to have tools like mypy assume str means unicode in Python 2 and str in Python 3 and bytes means Python 3 bytes of to have typing.py have Str and Bytes types to make it abundantly clear. Since function annotations are Python 3 syntax I'm assuming the tools will be more-or-less be assuming Python 3 semantics, but it might be good to state upfront that's the expectation when specified in Python 2/3 code. Going with the former approach does mean the usefulness to Python 2-only code is diminished since the concept of native strings becomes hard to express. The latter solution has the annoyance of not using the built-in types.

**Comment by ambv** [comment]
One thing we started doing at Facebook is this:
```
# s/str(/bytes(/g

from __future__ import unicode_literals
str = type('str')

# s/unicode(/str(/g
```

This code won't behave __exactly__ the same in all circumstances (for instance while indexing bytes) but it covers enough cases to be usable (with tests!). Puts Python 3 syntax first, which I like.

**Comment by gvanrossum** [comment]
Honestly I don't see anything actionable for the PEP in this issue. The PEP is for Python 3. What to do for Python 2 is up to mypy.

**Comment by ambv** [comment]
Fair enough. Closing for now. @brettcannon, sorry!

**Comment by vlasovskikh** [comment]
@gvanrossum In the context of the newly-added comment-based syntax for Python 2.7 + Python 3 should we reopen this issue? It's not clear how to annotate text/bytes types in the standard way.

**Comment by gvanrossum** [comment]
We have a huge discussion on the mypy tracker about this too. It's not at all clear what to do...

**Comment by gvanrossum** [comment]
I propose to do only one thing in PEP 484 and typing.py: add a new type alias `Text`. On Python 3 this is an alias for `str`; on Python 2 it is `unicode`.

**Comment by JukkaL** [comment]
That seems reasonable for 3.5.2. It's at least a strict improvement over what we have now.

**Comment by vlasovskikh** [comment]
I agree with @JukkaL. The discussion in python/mypy/issues/1141 will take some time to come up with a general satisfactory solution. Meanwhile people will be able to experiment with text / binary types for Python 2 and 3 using the updated `typing` module.

**Comment by gvanrossum** [comment]
OK, I've added Text to both versions and to the stdlib and the PEP.

I'll close this issue now, since the full spec is probably going to be a separate PEP.

**Comment by gvanrossum** [comment]
FWIW I think this has been superseded by https://github.com/python/typing/issues/208
