### ISSUE TITLE
Inheritance issues with generic collections

### ISSUE THREAD

**Issue by bintoro** [python/typing#202]
I have a problem with how `__extra__` is currently inherited:

```python
>>> class CustomMapping(typing.Mapping): ...
... 
>>> issubclass(dict, CustomMapping)
True
```

```python
>>> class CustomDict(typing.Dict): ...
... 
>>> issubclass(dict, CustomDict)
True
```

This can't be right.

My initial impression is that `__extra__` should only be propagated on parameterization, not when subclassing, and that the concrete types `List`, `Dict`, etc. should have their own extras (`list`, `dict`, and so on). Thoughts? A tentative patch is [here](https://github.com/python/typing/compare/master...bintoro:extra-inheritance).

Another thing: The module distributed on PyPI still has the issue where a generic doesn't include itself in the subtype's MRO during parameterization. This was fixed for Python 3.5.1 in aab2c59. It would be great if we could get a more recent revision on PyPI as well.

3.5.1:

```python
>>> issubclass(Iterable[int], Iterable)
True
```

3.5.0:

```python
>>> issubclass(Iterable[int], Iterable)
False
```

And finally, a question: The `collections` ABC replacements do not provide the abstract (or any other) methods of the originals. In particular, `Iterable` is technically not abstract at all. Is this intentional or just a temporary state of affairs?

**Comment by gvanrossum** [comment]
- I'll look over your patch.
- I'll see if I can release a 3.5.1 version -- it looks like 3.5.2 is still a while away.
- It's probably an oversight that Iterable isn't abstract; or perhaps there was a technical issue.

**Comment by gvanrossum** [comment]
Updated the typing gpackage to 3.5.1. Please verify that it's to your
liking.

**Comment by bintoro** [comment]
> Updated the typing gpackage to 3.5.1.

Thanks!

As for the abstract methods, adding `__iter__` to `Iterable` seems to have no ill effects.

`Container`, `Awaitable`, and `AsyncIterable` and their derivatives are also affected — in other words everything that doesn't inherit from `Sized` or `Hashable`.

One option is to just copy everything over during class construction:

```python
 class GenericMeta(TypingMeta, abc.ABCMeta):
 
     def __new__(cls, name, bases, namespace,
                 tvars=None, args=None, origin=None, extra=None):
+        if extra and origin is None:
+            for methodname in getattr(extra, '__abstractmethods__', ()):
+                if methodname in extra.__dict__:
+                    namespace.setdefault(methodname, extra.__dict__[methodname])
+
         self = super().__new__(cls, name, bases, namespace, _root=True)
```

**Comment by gvanrossum** [comment]
I would like to go slow here. I have other priorities (see https://github.com/python/typing/issues/203#issuecomment-211181165). I will eventually get to this but I'm not sure I want to rush anything into 3.5.2 beyond what's already on deck.
