### ISSUE TITLE
Add typing.Text?

### ISSUE THREAD

**Issue by matthiaskramm** [python/typing#204]
See https://github.com/python/mypy/issues/1141 and https://groups.google.com/forum/#!topic/python-ideas/gA1gdj3RZ5g

Having `typing.Text` as an alias for (on Python 2) `Union[str, unicode]` and for (on Python 3) `Union[bytes, str]` would simplify some stubs in typeshed. (And allow typeshed stubs to be shared between Python 2 and 3)

However, there are concerns that people would use typing.Text in `*.py`, not just `*.pyi`, thus weakening the type-checking static analysis tools can do. (And the distinction between unicode and str in Python 2 programs is critical when porting to Python 3)

**Comment by gvanrossum** [comment]
I don't think any of the proposals on the table includes Text being `Union[bytes, str]` in Python 3. The two types are intentionally different, and AFAIK all proposals have `Text = str` in Python 3 (TBH if I had to do it over I would have renamed str to text in Python 3, ten years ago). In Python 2 I currently have `Text = str` but arguably the better type there would be `basestring`, once I add the proper methods to it (I have a PR out but it's a big refactor and I'm worried it would break something: https://github.com/python/typeshed/pull/138).

**Comment by vlasovskikh** [comment]
`typing.Text` has been already added with another meaning, see https://github.com/python/typing/commit/6da9fc25d0d3a6d7ca1b7dc88c987b67c400240d. See #19.

**Comment by matthiaskramm** [comment]
Interesting. In that case, I believe typeshed should start using `Union[Text, bytes]` in a few places, particularly in `2to3/`.

**Comment by gvanrossum** [comment]
I can believe that. (But why not AnyStr?)

**Comment by matthiaskramm** [comment]
`AnyStr` is a type parameter, which doesn't work in all cases. (Typical example is a function with two arguments, and they both can either be str or unicode, but don't have to have the same type)

**Comment by gvanrossum** [comment]
OK, go ahead and make the changes you think are necessary, or send them to me as PRs. This should be pretty uncontroversial.

**Comment by gvanrossum** [comment]
typing.Text now exists everywhere.
