### ISSUE TITLE
Consider a refinement for class variable declarations

### ISSUE THREAD

**Issue by gvanrossum** [python/typing#209]
In mypy we are proposing to implement strict Optional checking per PEP 484, with one exception.

https://github.com/python/mypy/issues/1450

> The one exception will be in the case of instance variables defined in the class body. These variables may be assigned None while having a non-Optional type, provided that they are initialized to a non-None value by the end of `__init__`. They may be initialized in `__init__` itself, or in any method on self that `__init__` calls, or in `__new__`. Mypy will not check these variables for use before assignment to a non-None value in `__init__` or called methods, though it may make sense to add that at some point in the future.

> The purpose of this exception is to allow variables to be typed in a common place rather than scattered around `__init__`.

I think this is a good idea and we should update PEP 484 to follow this.

**Comment by porglezomp** [comment]
I saw on #1450 there was some concern about writing code that relied on control flow analysis; this seems like exactly the sort of rule that would require control flow analysis to do correctly.

**Comment by gvanrossum** [comment]
Hey, did you delete your comment or is there a GitHub glitch? I can't see
it on the website.

On Thu, May 5, 2016 at 8:56 PM, Caleb Jones <notifications@github.com>
wrote:

> I saw on #1450 there was some concern about writing code that relied on
> control flow analysis; this seems like exactly the sort of rule that would
> require control flow analysis to do correctly.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/python/typing/issues/209#issuecomment-217342441>
>



-- 
--Guido van Rossum (python.org/~guido)

**Comment by porglezomp** [comment]
I deleted it since it wasn't really relevant to the specification of the types, it was more an implementation concern, and I don't think it's a relevant concern here, since other features already require it.

**Comment by gvanrossum** [comment]
I'm closing this; it looks like the PEP already has the right words:

> 
> In non-stub code, there is a similar special case::
> ```
>   from typing import IO
> 
>   stream = None  # type: IO[str]
> ```
> Type checkers should not complain about this (despite the value
> ``None`` not matching the given type), nor should they change the
> inferred type to ``Optional[...]`` (despite the rule that does this
> for annotated arguments with a default value of ``None``).  The
> assumption here is that other code will ensure that the variable is
> given a value of the proper type, and all uses can assume that the
> variable has the given type.
>
