### ISSUE TITLE
SWIG generator of PEP-484 type hint stub files

### ISSUE THREAD

**Issue by mcepl** [python/typing#220]
I know this is probably wrong place to ask, so I am expecting to be redirected somewhere else, but it would be awfully nice to have a tool, which would be able to generate ``*.pyi`` files for the Python bindings generated by [SWIG](http://swig.org).

**Comment by gvanrossum** [comment]
You'd have to open a SWIG feature request. (Or contribute one yourself.)

This is a special case though of something we are keeping track of here: https://github.com/python/mypy/issues/1240 -- for example we've actually got a use case for a similar thing for Protocol Buffers (protobuf).

**Comment by mcepl** [comment]
I have asked for it on the SWIG list already (http://thread.gmane.org/gmane.comp.programming.swig/21112), but I just thought that you may be able to push from the other side as well ;).

**Comment by gvanrossum** [comment]
Presumably you wouldn't be happy running stubgen on the SWIG output (plus
that currently doesn't add any types to the output).

**Comment by mcepl** [comment]
Not sure what you mean as ``SWIG output``. Generated C code? binary module? stubgen from 0.4.1 doesn't seem to react to either of these

**Comment by gvanrossum** [comment]
Oh, sorry. Doesn't it generate Python glue? If it's just generating C, it
looks like stubgen it supposed to handle those, IIUC by importing them and
then introspecting the module __dict__. I've not tried this myself though.

**Comment by mcepl** [comment]
It doesn't. It basically generates the C code (see attached) which compiles to Python-compatible binary module. Anyway, I will continue to pursue this on the Swig list.

**Comment by mcepl** [comment]
Just for the record, there is https://github.com/swig/swig/issues/735
