### ISSUE TITLE
Union runtime check fails for xml.etree.cElementTree.Element

### ISSUE THREAD

**Issue by OrenLeaffer** [python/typing#229]
```py
from typing import *
from xml.etree.cElementTree import Element
T = Union[Element, Optional[str]]
```

Under python 2, this fails at runtime, but it works for static type checking. Currently the best workaround seems to be to define T in a `if False:` block, which allows the static check to pass without causing runtime errors.

**Comment by gvanrossum** [comment]
What error do you get?

**Comment by kirbyfan64** [comment]
```
Traceback (most recent call last):
  File "y.py", line 3, in <module>
    T = Union[Element, Optional[str]]
  File "/usr/local/lib/python2.7/dist-packages/typing.py", line 549, in __getitem__
    dict(self.__dict__), parameters)
  File "/usr/local/lib/python2.7/dist-packages/typing.py", line 479, in __new__
    params.append(_type_check(p, msg))
  File "/usr/local/lib/python2.7/dist-packages/typing.py", line 298, in _type_check
    raise TypeError(msg + " Got %.100r." % (arg,))
TypeError: Union[arg, ...]: each arg must be a type. Got <built-in function Element>.
```

**Comment by ddfisher** [comment]
I don't think this is a Python 2 issue in particular, though -- it just so happens that only the Python 2 version of xml.etree.cElementTree.Element exhibits this problem.

**Comment by kirbyfan64** [comment]
Probably a horrible idea...but what if `typing._type_check` just has a list of "special cases", a list of functions that look like they're types. Then it could do an identity check (NOT equality) for each of them.

**Comment by gvanrossum** [comment]
Can you see if this is already fixed with the latest python2/typing.py from the githubcom/python/typing repo?

**Comment by OrenLeaffer** [comment]
I tried the file you mentioned and ran into the same issue.

In the particular use I'm dealing with, I am able to get away with importing Element from ElementTree instead of cElementTree, which seems like a plausible workaround for this case. Though it is technically incorrect, since the returned object is not actually an instance of ElementTree.Element.

The only way I can figure out how to access the actual type of the object returned by xml.etree.cElementTree.Element() is by calling type() on the returned object.

**Comment by gvanrossum** [comment]
Probably `_type_check()` should just allow anything that's callable. It's just meant to quickly diagnose some obviously bad calls like `Union[1, '']`, and a false positive is much more annoying than a false negative (which a real type checker presumably would catch).
