### ISSUE TITLE
clarification around Python 2.7 per-argument type comments

### ISSUE THREAD

**Issue by ddfisher** [python/typing#237]
After implementing per-argument type comments in the mypy (and the typed_ast library it uses), there are a few points in the PEP that might be worthy of clarification/further specification.

1) It doesn't make sense for an argument to have both a type annotation and a type comment, but I don't think the PEP mentions that that is disallowed.  It probably should.

2) My reading of the PEP suggests this is already the case, but it could be worth being explicit that you don't _have_ to specify a return type to use per-argument type comments.

3) Would it be acceptable to only allow per-argument type comments _after_ an argument's associated comma, if any?
E.g. this is acceptable:

``` py
def f(x,  # type: int
      y   # type: str
     ):
    pass
```

but this would not be:

``` py
def f( x  # type: int
     , y  # type: str
     ):
    pass
```

The first form is generally considered more Pythonic, and supporting the second form would add significant implementation complexity.

**Comment by gvanrossum** [comment]
> 1) It doesn't make sense for an argument to have both a type annotation and a type comment, but I don't think the PEP mentions that that is disallowed. It probably should.

Agreed. The PEP already says this, but pretty weakly: "To specify the return type use the ellipsis syntax."

> 2) My reading of the PEP suggests this is already the case, but it could be worth being explicit that you don't have to specify a return type to use per-argument type comments.

That same sentence was meant to also cover this. :-) Agreed it's too subtle.

> 3) Would it be acceptable to only allow per-argument type comments after an argument's associated comma, if any?

Also agreed. This was implicit in the example. :-)

Do you want to make a PR for the PEP?

**Comment by ddfisher** [comment]
Will do, thanks!
