### ISSUE TITLE
Sequence example in List documentation does not typecheck

### ISSUE THREAD

**Issue by Michael0x2a** [python/typing#238]
The [documentation for the `List` type][0] uses the following example to help demonstrate when to use `Sequence` vs `List`:

```python
T = TypeVar('T', int, float)

def vec2(x: T, y: T) -> List[T]:
    return [x, y]

def slice__to_4(vector: Sequence[T]) -> List[T]:
    return vector[0:4]
```

However, the `slice__to_4` function is does not actually typecheck since there's no guarantee that a slice of a sequence will return a `List` -- for example the vector could be a numpy array or a custom subclass of `collections.abc.Sequence` with an unusual `__getitem__`. Mypy correctly catches this error and complains about an "Incompatible return value type".

The documentation should probably be updated to use an example that _does_, though I'm not sure what exactly that example might look like? Maybe replace `slice__to_4` with something like this?

```python
def keep_positives(vector: Sequence[T]) -> List[T]:
    return [item for item in vector if item > 0]
```

Paging @gnprice, since he helped spot this.

  [0]: https://docs.python.org/3/library/typing.html#typing.List

**Comment by gvanrossum** [comment]
Good catch, but the place to report this is bugs.python.org... Does PEP 484
also have this error?

On Thursday, June 23, 2016, Michael Lee <notifications@github.com> wrote:

> The documentation for the List type
> <https://docs.python.org/3/library/typing.html#typing.List> uses the
> following example to help demonstrate when to use Sequence vs List:
>
> T = TypeVar('T', int, float)
> def vec2(x: T, y: T) -> List[T]:
>     return [x, y]
> def slice__to_4(vector: Sequence[T]) -> List[T]:
>     return vector[0:4]
>
> However, the slice__to_4 function is does not actually typecheck since
> there's no guarantee that a slice of a sequence will return a List -- for
> example the vector could be a numpy array or a custom subclass of
> collections.abc.Sequence with an unusual __getitem__. Mypy correctly
> catches this error and complains about an "Incompatible return value type".
>
> The documentation should probably be updated to use an example that *does*,
> though I'm not sure what exactly that example might look like? Maybe
> replace slice__to_4 with something like this?
>
> def keep_positives(vector: Sequence[T]) -> List[T]:
>     return [item for item in vector if item > 0]
>
> Paging @gnprice <https://github.com/gnprice>, since he helped spot this.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/python/typing/issues/238>, or mute the thread
> <https://github.com/notifications/unsubscribe/ACwrMn0lLUexWH_yULX9PCRWMd5MCSBqks5qO0VygaJpZM4I9a32>
> .
>


-- 
--Guido (mobile)

**Comment by Michael0x2a** [comment]
I checked -- it doesn't look like PEP 484 has the bug. I refiled the bug report here: http://bugs.python.org/issue27402

Should I close this issue?

**Comment by gvanrossum** [comment]
Yeah, no need to keep two issues open for one thing.
