### ISSUE TITLE
Add decorator- and docstring-based approaches to PEP 482

### ISSUE THREAD

**Issue by ilevkivskyi** [python/typing#245]
While updating and cleaning up the README.rst I have found that all TODO items are either outdated or have an issue on this tracker or on mypy tracker. Except for this one, I just copy it here, so that it is not lost.

"State of the art: should we list decorator-based approaches
(PyContracts?) and docstring-based approaches?  **TODO:** Łukasz to
update PEP 482."

**Comment by ambv** [comment]
Alright, will update.

**Comment by srittau** [comment]
This issue looks obsolete to me.
