### ISSUE TITLE
Should we discuss "scope" of type variables in PEP 484?

### ISSUE THREAD

**Issue by ilevkivskyi** [python/typing#249]
I did not find any discussion about the "visibility" of type variables. For example, here
```python
from typing import TypeVar, Generic

T = TypeVar('T')

def fun_1(x: T) -> T:
    ...
def fun_2(x: T) -> T:
    ...

class MyClass(Generic[T]):
    def meth_1(self, x: T) -> T:
        ...
    def meth_2(self, x: T) -> T:
        ...
```
I think the type variable ``T`` could take different values in ``fun_1`` and ``fun_2``, but it is always the same for ``meth_1`` and ``meth_2``. I could imagine more complex examples with deeply nested classes and functions. Although it might be obvious for some people, maybe we should discuss "scoping rules" for type variables in the PEP?

**Comment by gvanrossum** [comment]
I don't think we need to explain that type variables follow Python's normal scope rules, so I presume you're just talking about whether inside a class that's generic in T, *all* uses of T refer to the T in the class definition. I think that's the only thing that makes sense, as your example shows -- for `meth_1` and `meth_2` the argument is constrained by the "value" for T that applies to the instance. E.g. in
```python
a = MyClass()  # type: MyClass[int]
a.meth_1(x)  # For some x
```
the type of `x` must be compatible with `int`.

If you think the PEP doesn't clarify this sufficiently please suggest some text.

I guess there are some edge cases worth ruling about, e.g. a generic class nested in another generic class can't use the same type vars, unless the inner class definition is inside a function -- I learned this by experimenting with mypy but it all seems reasonable.

**Comment by ilevkivskyi** [comment]
> I guess there are some edge cases worth ruling about, e.g. a generic class nested in another generic class can't use the same type vars, unless the inner class definition is inside a function

I wanted to discuss such edge cases, and maybe something simpler like "non-generic class attributes should not contain free type variables (probably unless it is inside another class if it is generic)" mentioned in https://github.com/python/mypy/issues/1903

I am going to make a PR to python/peps beginning of next week. @gvanrossum , do you have additional suggestions on the rules/corner cases that should be mentioned?

**Comment by gvanrossum** [comment]
I will be happy to review what you write, I don't believe I have anything
specific to add at this point.
