### ISSUE TITLE
Shouldn't typing also have Coroutine?

### ISSUE THREAD

**Issue by gvanrossum** [python/typing#251]
PEP 492 introduces a [few new ABCs](https://www.python.org/dev/peps/pep-0492/#list-of-high-level-changes-and-new-protocols): Awaitable, Coroutine, AsyncIterable, AsyncIterator. PEP 484 lists [three of these](https://www.python.org/dev/peps/pep-0484/#annotating-generator-functions-and-coroutines): Awaitable, AsyncIterable, AsyncIterator. What happened to Coroutine? A Coroutine is an Awaitable that also supports send(), throw() and close().

It seems a simple oversight. Let's fix it before 3.5.3 comes out.

@1st1 do you remember any of this? Do you recall a reason to leave out Coroutine?

**Comment by 1st1** [comment]
> @1st1 do you remember any of this? Do you recall a reason to leave out Coroutine?

No, I suspect it was left out by mistake.

**Comment by gvanrossum** [comment]
OK, I'll just add it then.

**Comment by thehesiod** [comment]
it would be neat if we could specify the parameters to the coroutine as well...something like:

```python
async def dummy(dummy_param: int) -> Awaitable[None]:
    return

async needs_typing(co_method: Coroutine[int]):
    await co_method(1)

await needs_typing(dummy)
```

**Comment by ilevkivskyi** [comment]
@gvanrossum 
I see that you have assigned this issue to yourself, but if you don't mind, I would like to do this (in ``python/typing`` and in ``python/peps``). Just a small clarification: should order of type variables be the same as for ``Generator``? So that:
```python
class Coroutine(Awaitable[ret_type_co], Generic[yield_type_co, send_type_contra, ret_type_co]):
    ...
```

**Comment by gvanrossum** [comment]
I'm fine with you doing this, but I had thought that Coroutine would have
only one parameter (the return type). I guess this means we'll need to look
at some example code to see how it would be used.

**Comment by ilevkivskyi** [comment]
In principle a normal coroutine defined with ``async def`` has a trivial ``.send()`` method that only accepts ``None`` and raises ``StopIteration``. However, one could make a coroutine "manually" by instantiating a non-abstract subclass of ``collections.abc.Coroutine``. Such "manually created" coroutine could have a non-trivial ``.send()`` method. But I agree with you that this use case is probably rare. I do not have a preference here. @1st1 what do you think?

**Comment by ilevkivskyi** [comment]
@gvanrossum Yet another option would be to make ``Coroutie`` a special form. So that ``Coroutine[[X, Y], Z]`` is essentially equivalent to ``Callable [[X, Y], Awaitable[Z]``.

**Comment by gvanrossum** [comment]
Oh, no! I think after all it should indeed mimic Generator.
