### ISSUE TITLE
Proposal: Reiterable[T]

### ISSUE THREAD

**Issue by jstasiak** [python/typing#260]
Sometimes when dealing with an object the only requirement is for said object to be able to be iterated multiple times, for example in a situation like this:

```python
def process_loop(messages: Iterable[Message], handlers: XXX[Handler]) -> None:
    for message in messages:
        for handler in handlers:
            handler.handle(message)
```

I usually use ``Sequence`` or just ``List`` in such cases but even ``Sequence`` is too restrictive - dictionary keys/values/items views and sets are iterable multiple times but aren't sequences, I imagine there are more cases like this in the standard library and in third party code.

Therefore I'd like to propose what follows:

* Add something along the lines of:
```python
class Reiterable(Iterable[_T_co], Generic[_T_co]):
    pass
```
* Inherit some classes in typeshed from ``Reiterable[T]``, not ``Iterable[T]``
* Document it for what it is - a promise that something is iterable multiple times, mypy can't actually make sure of that

I'm happy to do all the necessary work to make this happen.

Some discussions on a similar topic:

* http://www.gossamer-threads.com/lists/python/python/382571
* https://mail.python.org/pipermail/python-dev/2003-October/038969.html

**Comment by NeilGirdhar** [comment]
When I suggested this, there was also a long discussion: https://mail.python.org/pipermail/python-ideas/2013-September/023239.html

Recently, Guido mentioned it: https://mail.python.org/pipermail/python-ideas/2016-July/041167.html

I'm really hoping this will be an ABC.

**Comment by gvanrossum** [comment]
The pythonic issue is http://bugs.python.org/issue27598, with recommended name Collection. Hopefully we'll get to it before 3.6 beta 1, and then we'll also add it to typing.py.

**Comment by gvanrossum** [comment]
Closing in favor of Collection.

**Comment by NeilGirdhar** [comment]
@gvanrossum Regarding the addition of `Collection` in preference to `Reiterable`:  Is it the case that `ValuesView` is not a `Collection`?  Because `ValuesView` is typically reiterable.

**Comment by gvanrossum** [comment]
IMO MappingView should be reclassified as a Collection, since it implements `__len__` and all its subclasses implement `__iter__` and `__contains__`. We need separate patches for _collections_abc.py (in the CPython hg repo) and typing.py (here).

**Comment by NeilGirdhar** [comment]
Okay, that makes sense.
