### ISSUE TITLE
Subclasses of typing.Sequence (&c) pretend to be superclasses of all registered members of abc.Sequence (&c)

### ISSUE THREAD

**Issue by sixolet** [python/typing#268]
Check this out yo:

```
In [1]: from typing import Sequence
In [2]: class DumbSeq(Sequence): pass
In [3]: issubclass(tuple, DumbSeq)
Out[3]: True
```

This has to do with the implementation of `GenericMeta`, where our `__subclasscheck__` ends with this line:

```python
        return issubclass(cls, self.__extra__)
```

And for the container classes in `typing`, they're defined to have the `collections.abc` classes as their `__extra__`.

Pondering a fix to suggest.

**Comment by gvanrossum** [comment]
Before you ponder much more, maybe the only open PR addresses this?
https://github.com/python/typing/pull/207

**Comment by sixolet** [comment]
Yup looks like.

**Comment by gvanrossum** [comment]
Also, this looks similar: https://github.com/python/typing/issues/202

**Comment by sixolet** [comment]
Also correct.  I'd close this as a duplicate.

**Comment by gvanrossum** [comment]
In particular, you were apparently testing with an outdated version of typing.py. :-(
