### ISSUE TITLE
A way to spell "SelfType", the type of self

### ISSUE THREAD

**Issue by gvanrossum** [python/typing#271]
See https://github.com/python/mypy/issues/1212. The proposal does not require changes to typing.py but it could benefit from words in PEP 484 requiring that this works.

The idea is simple: in an instance method, you can add a type annotation for `self` which is a type variable, and make the return type use that same type variable, e.g.

``` python
T = TypeVar('T', bound='Copyable')
class Copyable:
    def copy(self: T) -> T:
        # return a copy of self
class C(Copyable): ...
c = C()
c2 = c.copy()  # type here should be C
```

It should also work for class methods, using `Type[]`, e.g.

``` python
T = TypeVar('T', bound='C')
class C:
    def factory(cls: Type[T]) -> T:
        # make a new instance of cls
class D(C): ...
d = D.factory()  # type here should be D
```

Note that the Python 2 annotation syntax already supports this, e.g.

``` python
T = TypeVar('T', bound='Copyable')
class Copyable:
    def copy(self):
        # type: (T) -> T
        # etc.
```

(IOW if you have a method with `self` and three arguments, you can give it either 3 or 4 arguments in the `# type:` comment, and if 4, the first will be used for `self`. Ditto for class methods.)

**Comment by ilevkivskyi** [comment]
I think this is a good idea. As I understand, not much should be changed in PEP 484. The main part would be to implement this in mypy. I could not help with mypy now, but I would like to make a PR with changes in the PEP text.

**Comment by gvanrossum** [comment]
Thanks -- though I may hold off on merging the PEP change until I've
double-checked with @JukkaL that this can actually be implemented in mypy.

**Comment by ilevkivskyi** [comment]
OK, here is the PR https://github.com/python/peps/pull/89
