### ISSUE TITLE
Clarify what unparameterized Tuple means

### ISSUE THREAD

**Issue by gvanrossum** [python/typing#284]
Currently when you annotate something as `Tuple`, mypy interprets this as a 0-length tuple. I don't like this. PEP 484 is silent on the matter, but in analogy of `List` I'd like it to mean `Tuple[Any, ...]`, which is also equivalent to `tuple` (lowercase 't').

**Comment by ilevkivskyi** [comment]
Absolutely +1 on this. I will be glad to make a PR to ``python/peps`` on this.

**Comment by gvanrossum** [comment]
OK, please go ahead with the PEP 484 PR. (I also couldn't find where it says that `List` means `List[Any]` -- it says something about subclassing without specifying parameters, but that's not relevant -- I'm just talking about using `List` in type annotations. That meaning is uncontroversial, but if it isn't said somewhere it still ought to be mentioned.
