### ISSUE TITLE
All geneneric types should be indexable.

### ISSUE THREAD

**Issue by ilevkivskyi** [python/typing#298]
Now one can write ``Dict[T, int][str]``, while ``Callable[[T], int][str]`` raises an error. However, most of the arguments for allowing indexable generics also apply for ``Union, Tuple, Callable``, etc. Actually, these types are also generic in the sense that they could depend on other types or type variables (for example ``Callable`` takes two types ``str`` and ``int``, and returns a new type ``Callable[[str], int]``).

@gvanrossum If you agree, then you can assign this issue to me.

**Comment by gvanrossum** [comment]
I think this may be getting into the territory of
https://github.com/python/mypy/issues/606. It's vigorously debated!
