### ISSUE TITLE
Allow keyword syntax for NamedTuple

### ISSUE THREAD

**Issue by ilevkivskyi** [python/typing#302]
It was proposed by Guido to add the following syntax:

``` python
Point = typing.NamedTuple('Point', x=int, y=int)
p = Point(x=1, y=2)
p.x
```

I also like it. Probably, we should also support it for `TypedDict`.

**Comment by JukkaL** [comment]
Seems reasonable, though if `NamedTuple` already supports keyword arguments, there may be some ambiguity. And this is a Python 3.6+ only feature.
