### ISSUE TITLE
Union[int, long] seems common in Python 2, perhaps create a typing.Integer for it?

### ISSUE THREAD

**Issue by gpshead** [python/typing#309]
typing.Integer would simply = int in Python 3.

I don't believe SupportsInt is really the same thing.  Correct me if I'm wrong.

**Comment by kirbyfan64** [comment]
In the vein of `AnyStr`, maybe `AnyInt` would be a better name?

**Comment by gvanrossum** [comment]
But even in Python 2 there's little reason to use long except for legacy
reasons. Or is this for protobuf?

**Comment by JukkaL** [comment]
I don't see a good reason to use `Union[int, long]` even in Python 2, as `long` is defined as an alias for `int`, so the union is exactly the same type as plain `int`. Extract from `__builtin__.pyi`:

```
long = int
```

Maybe somebody might want to use this for documentation purposes, but that looks pretty unusual and in that case the user is free to define the alias in an internal library module.

**Comment by JelleZijlstra** [comment]
Closing this as Python 2 is EOL and there hasn't been much interest in this issue.
