### ISSUE TITLE
get_type_hints raises AttributeError instead of TypeError

### ISSUE THREAD

**Issue by bakkerthehacker** [python/typing#313]
From what I can tell, the [code here](https://hg.python.org/cpython/file/tip/Lib/typing.py#l1419) is a typo

> `if isinstance(object, type):`

This causes `get_type_hints` to raise 

```
AttributeError: 'int' object has no attribute '__code__'
```
instead of 
```
TypeError: 123 is not a module, class, method, or function.
```

**Comment by gvanrossum** [comment]
I think you meant this line (1419 in typing.py): https://hg.python.org/cpython/file/default/Lib/typing.py#l1419

In this GitHub repo that's https://github.com/python/typing/blob/master/src/typing.py#L1419

That indeed looks fishy! 'object' should be 'obj'.

Can you should a tiny example that exhibits the error you reported?

**Comment by bakkerthehacker** [comment]
```
from typing import get_type_hints
get_type_hints(123)
```

**Comment by gvanrossum** [comment]
@ilevkivsky -- do you agree?

**Comment by ilevkivskyi** [comment]
@gvanrossum @bakkerthehacker Yes, sorry, I made that stupid typo. I will make a PR very soon.
