### ISSUE TITLE
refleak in typing.py

### ISSUE THREAD

**Issue by gvanrossum** [python/typing#323]
This is a proxy for http://bugs.python.org/issue28649, which is discussing a reference leak (real or perceived) caused (most likely) by the use of lru_cache. There's a small fix there that we should apply here (if it gets applied to CPython): http://bugs.python.org/review/28649/#ps19113; and another at http://bugs.python.org/review/28649/. Also I think the fixes should be back-ported (the Python 2 version uses its own cache implementation which presumably should also be cleared when testing for refleaks).

**Comment by ilevkivskyi** [comment]
@gvanrossum I think we should also apply http://bugs.python.org/review/28649/#ps19114 to avoid problems in the future.

**Comment by ilevkivskyi** [comment]
@gvanrossum Oh, sorry, you already mentioned this one. :-) Will submit a corrected patch now.

**Comment by gvanrossum** [comment]
(Sorry, I updated the first comment in place. It's race conditions all the
way down today it seems. :-)

**Comment by gvanrossum** [comment]
Note that we have at least 5 PRs related to this issue (now all merged): #324, #325, #326, #327, #328. Wow.

**Comment by ilevkivskyi** [comment]
The original refleak is fixed and it looks like there are no signs of other leaks almost one month since the release, so that I think this issue could be closed now.
