### ISSUE TITLE
Error when using Generic and __slots__

### ISSUE THREAD

**Issue by valtron** [python/typing#332]
```python
from typing import Generic, TypeVar

class C(Generic[TypeVar('T')]):
	__slots__ = ('potato',)

# ValueError: 'potato' in __slots__ conflicts with class variable
C[int]
```

This is because bare `C` is created with a class member descriptor `potato`, and instantiating it tries to create a class with all the attributes in `C`.

**Comment by gvanrossum** [comment]
@ilevkivskyi Assuming we can fix this I think a case could be made to put this fix in the rc1.
