### ISSUE TITLE
Document convention of leading __ for positional-only args

### ISSUE THREAD

**Issue by gvanrossum** [python/typing#336]
In mypy we now support specifying positional-only arguments using two leading underscores:
- https://github.com/python/mypy/issues/516 (issue)
- https://github.com/python/mypy/pull/2497 (fix)

We should document this convention in PEP 484.

@sixolet want to propose a PR to the PEP (in the python/peps repo)? Or is this already covered in your extended proposals?

**Comment by sixolet** [comment]
It's not otherwise covered, and I'll prepare a separate PR to doc it 📜
