### ISSUE TITLE
Should NamedTuple rely on dict being oredered?

### ISSUE THREAD

**Issue by ilevkivskyi** [python/typing#339]
Currently, ``NamedTuple`` relies on the fact that ``dict`` is ordered in Python 3.6. However, (if I remember correctly) it was decided at some point that the ordered nature of ``dict`` is a CPython implementation detail. The question is should we explicitly use an ``OrderedDict`` instead?

**Comment by gvanrossum** [comment]
How exactly does it depend on that? IIRC you can trust that the namespace arg to `__new__` is ordered -- either it's a dict and the dict implementation is ordered, or else it's an OrderedDict.

**Comment by ilevkivskyi** [comment]
@gvanrossum It actually depends on ``__annotations__`` being ordered. The point is that if one writes:
```python
class C:
    x: int
    y: str
```
then ``x`` and ``y`` don't appear in the class namespace. Actually, now I am thinking maybe it makes sense to require ``__annotations__`` to be ordered? (Fortunately, PEP 526 is still provisional, so that it could be updated.)

**Comment by gvanrossum** [comment]
Yes, esp. since there are no code changes needed.
