### ISSUE TITLE
Maintain documentation in this repository instead of in the stdlib

### ISSUE THREAD

**Issue by brettcannon** [python/typing#342]
Since the stdlib typically gets overwritten by @gvanrossum on occasion with a file copy from this repo, then it might make sense to also maintain the docs here so they stay in sync with the in-development module code. This might also come into play if there's ever a desire to have Python 2-specific docs.

The impetus of asking this is http://bugs.python.org/issue29002.

**Comment by gvanrossum** [comment]
I'm -0. Having things in a separate repo is a pain, but the actual code *needs* to be separately distributed via PyPI anyway. For the docs it's less clear. We've managed the same thing for asyncio.

Perhaps it would be good enough if there were some Python 2 specific docs in the mypy docs?

How would we build the docs here? If there's an easy solution that doesn't require copying a lot of files I could go to +0.

**Comment by kirbyfan64** [comment]
> I'm -0. ... I could go to +0.

Is there a difference outside the world of floating point negative zero weirdness?

**Comment by brettcannon** [comment]
The file is just Sphinx-based rST so it shouldn't be more than copying the single `typing.rst` file from the stdlib and specifying the right Sphinx settings, but I haven't verified this.

**Comment by gvanrossum** [comment]
Another complication is that the docs are actually slightly different per Python version (e.g. the 3.5 docs shouldn't mention the PEP 526 notation).

I'm going to close this since I don't think we should do this.

**Comment by brettcannon** [comment]
Basically you would need to maintain branches that correspond to Python versions, but I understand not wanting the hassle (although this does suggest that we should probably decide if we are going to have other projects be maintained externally like this and if so how best to handle it for the next time).
