### ISSUE TITLE
Write down steps for a release

### ISSUE THREAD

**Issue by gvanrossum** [python/typing#343]
I just did a new release but accidentally named it 3.5.3.0 instead of 3.6.0. I suppose this is fine since we're very likely going to release Python 3.5.3 with the exact same version, but it's not what I meant to do -- it's just too late to fix now and I can't be bothered.

I propose to put the instructions at the top of setup.py. They should also include using twine (which I had forgotten about).

Something like:

- bump version in setup.py to x.x.x.0 (matching highest Python 3 version to which it is equal, so the next one should really be 3.6.1.0)
- run tests in src with Python versions 3.2, 3.3, 3.4, 3.5, 3.6, 3.7
- run tests in python2 with latest Python 2.7
- python3 setup.py sdist
- twine upload dist/...  (forget about twine register -- it's not needed)
- try a Python 2 install + test
- try a Python 3 install + test
- git tag (tag equals to version)
- git push
- announce

Should also explain/repeat the policy that we only do typing.py releases to PyPI that match an official Python release of the latest 3.x version. This is mainly because we want everyone to feel the pain of adding new features to typing.py rather than making this an incentive to stick with Python 3.4.

And finally clarify what the 4th digit is for. It always ought to be 0, but it isn't always because sometimes we screw up the PyPI release. This happened twice for 3.5.2 hence the 3.5.2.2 version -- PyPI refuses to overwrite a version number you've used before.

**Comment by ilevkivskyi** [comment]
These steps are now listed in README, so I think this can be closed.
