### ISSUE TITLE
Add typing.Deque

### ISSUE THREAD

**Issue by gvanrossum** [python/typing#353]
See http://bugs.python.org/issue29011 and commit https://hg.python.org/cpython/rev/dfefbf6f6c73 -- this was committed to the stdlib for 3.5-3.7 already, so should be copied into the typing repo and backported to Python 2.

**Comment by ilevkivskyi** [comment]
OK, will do this soon. By the way, 3.5.3 and 3.4.6 are released, so that other PRs could me merged (it will be easier for me to avoid conflicts with fixes for #351 and #352).

**Comment by gvanrossum** [comment]
Yes, I know the others can be merged. I would prefer to fix *this* one first since Raymond already landed it downstream.

**Comment by ilevkivskyi** [comment]
> I would prefer to fix this one first since Raymond already landed it downstream.

Sure, here is the PR #354
