### ISSUE TITLE
Need to spell out syntax for `a, b, *c = ...  # type: ...`

### ISSUE THREAD

**Issue by gvanrossum** [python/typing#363]
In analogy to the syntax for `*args` in function definitions, mypy's old parser requires:
```python
a, b, *c = 0, 0  # type: int, int, *List[int]
```
but the new parser omits the star from the annotation:
```python
a, b, *c = 0, 0  # type: int, int, List[int]
```
The PEP doesn't say which it should be. I propose the latter (since the analogy with function definitions is flawed anyway -- it would have to be `*int`).

See also https://github.com/python/mypy/pull/2722/files

**Comment by ilevkivskyi** [comment]
I vote for the second option. It seems more intuitive to me.
