### ISSUE TITLE
Drop Python 3.2 support?

### ISSUE THREAD

**Issue by ilevkivskyi** [python/typing#374]
From what I read on https://docs.python.org/devguide/index.html#branchstatus, Python 3.2 reached its EoL one year ago (February 2016). Maybe it is time to drop support for 3.2 in typing?

I am asking because I have noticed that there are several places in both ``typing.py`` and ``test_typing.py`` where 3.2 is special-cased. Dropping 3.2 support will allow to simplify code.

**Comment by JelleZijlstra** [comment]
Neither pip nor setuptools even support 3.2 any more, so I think there's little point in continuing to support it in typing.

**Comment by gvanrossum** [comment]
Agreed. Please update the classifiers in setup.py.

**Comment by ilevkivskyi** [comment]
OK, this is fixed by https://github.com/python/typing/commit/f264669254f0e6121f683e74e2947aa6e4b43b6f
