### ISSUE TITLE
get_type_hints in case of type hint comments return empty

### ISSUE THREAD

**Issue by gaborbernat** [python/typing#379]
Hello, 

So as far as I understand, these two definitions are both valid:

``` python

def test_param_init_return_str(param: int) -> str:
    """ Test one init param and return value is str.

    :param param: parameter to increase
    :return: increase value with one
    """
    return str(param + 1)


def test_param_init_return_str_comment(param):  # type: (int) -> str
    """ Test one init param and return value is str.

    :param param: parameter to increase
    :return: increase value with one
    """
    return str(param + 1)
```

[get_type_hints ](https://docs.python.org/3/library/typing.html#typing.get_type_hints) for the second returns empty though. Any plans to support that too?

**Comment by gvanrossum** [comment]
No, this is intentional.

**Comment by gaborbernat** [comment]
@gvanrossum why is that?

**Comment by gvanrossum** [comment]
Because type comments, unlike function annotations, are not preserved in any way at runtime, so there is no place for get_type_hints() to find them (short of reparsing the source, which would be a major project and be very slow).

**Comment by gaborbernat** [comment]
I see, thank you.
