### ISSUE TITLE
Optional and other type tests in 3.6 Union

### ISSUE THREAD

**Issue by hsolbrig** [python/typing#389]
In 3.5, I was able to test for optional and parameter types by:
```python
from typing import Union, Optional

def is_optional(t):
   return issubclass(type(None), t)

def is_valid(e, t):
   return issubclass(type(e), t)

is_optional(Union[int, str])
> False
is_optional(Union[int, str, None])
> True
is_valid("abc", Union[int, str])
> True
is_valid(["abc"], Union[int, str])
> False
```
The issubclass method is no longer allowed in 3.6.  How do I accomplish the equivalent in 3.6 on?

**Comment by ilevkivskyi** [comment]
In general, it is difficult to make runtime type checks reliable enough. This is why it was decided, to remove this functionality (and some other) in favour of _static_ type checkers like mypy, pytype, etc. This also allowed to make ``typing`` module faster.

Instead, a set of tools is being developed now in #377 that will allow users to build efficiently their own _runtime_ checks tuned to their specific needs. The set of tools will contain functions like ``is_union_type``, ``is_generic_type``, ``get_args``, etc. For example, using such tools one could define:
```python
from typing_inspect import is_union_type, get_args

def is_optional(tp):
    return is_union(tp) and type(None) in get_args(tp)
```
There was also a related discussion at http://bugs.python.org/issue29262

If you are interested in quick workarounds, then you could use the private typing API, but this is **not recommended**, for example something like:
```python
import typing
def is_optional(tp):
    return type(tp) is typing._Union and type(None) in tp.__args__
```
