### ISSUE TITLE
Proposal: `Self`, an alias for the implementing type

### ISSUE THREAD

**Issue by johnthagen** [python/typing#401]
I've been working a lot in [Rust](https://www.rust-lang.org/)  lately (and really enjoying it). They have a special type: [`Self`](https://doc.rust-lang.org/reference.html#self-types) 

> The special type `Self` has a meaning within traits and impls. In a trait definition, it refers to an implicit type parameter representing the "implementing" type. In an impl, it is an alias for the implementing type. For example, in:

```rust
pub trait From<T> {
    fn from(T) -> Self;
}

impl From<i32> for String {
    fn from(x: i32) -> Self {
        x.to_string()
    }
}
```

> The notation `Self` in the impl refers to the implementing type: `String`.

I believe this concept could help [the current less-than-ideal situation of forward references](https://www.python.org/dev/peps/pep-0484/#forward-references) in Python where "Self" types are named explicitly as strings, but most other type hints are not.

The current example:
```python
class Tree:
    def __init__(self, left: 'Tree', right: 'Tree'):
        self.left = left
        self.right = right
```

Could then be made more consistent:
```python
from typing import Self
class Tree:
    def __init__(self, left: Self, right: Self):
        self.left = left
        self.right = right
```

And a factory function could be changed from:
```python
class Tree:
    def tree_builder() -> 'Tree':
        ...
```

To:
```python
from typing import Self
class Tree:
    def tree_builder() -> Self:
        ...
```

CC @vlasovskikh from PyCharm team for any input.

**Comment by ilevkivskyi** [comment]
This is already implemented, see:

https://www.python.org/dev/peps/pep-0484/#annotating-instance-and-class-methods

and

http://mypy.readthedocs.io/en/latest/generics.html#generic-methods-and-generic-self

**Comment by ilevkivskyi** [comment]
OK, maybe it is not _exactly_ what you are asking for, but self-types plus forward references, cover all your use cases (also there is a proposal to make annotations strings automatically, so that the problem with forward references will be solved by #400)

**Comment by johnthagen** [comment]
Thanks for the info, I hadn't thought about using a `TypeVar`, but yeah I was looking specifically for a solution that didn't require as much extra boilerplate for every type.

**Comment by gvanrossum** [comment]
Is this really a big enough problem that we need to find a solution? I
think we have bigger fish to fry.

**Comment by gvanrossum** [comment]
Let's just close this, we won't do more about this and certainly not following Rust's example.

**Comment by johnthagen** [comment]
As a historical note, the `Self` type was [added in Python 3.11](https://docs.python.org/3/whatsnew/3.11.html#whatsnew311-pep673) with [PEP 673](https://peps.python.org/pep-0673/).
