### ISSUE TITLE
Let's release typing 3.6.1 to PyPI

### ISSUE THREAD

**Issue by gvanrossum** [python/typing#403]
I don't believe a 3.5.4 release is planned soon. I propose that we release the typing.py that went into 3.6.1 as typing-3.6.1 to PyPI. The 3.5.4 release should have an identical version but from now on the typing version number will start with 3.6. Does this make sense?

It looks like myself, @JukkaL, @ambv and @vlasovskikh have PyPI push permissions. @ambv I feel you have the least rusty PyPI skills (though there is little to it now we have twine).

If we haven't written up the release process in detail somewhere we should -- I hate having to remember this. Maybe a comment in the setup.py would be the right place?

Once this is out (inc. tags) we can merge #397 and https://github.com/python/mypy/pull/3041.

**Comment by ambv** [comment]
I can do this tomorrow!

**Comment by gvanrossum** [comment]
Thank you thank you thank you!

**Comment by ambv** [comment]
This is on Python 3.2.6:
```
.........................ssss.ss...s.....................s...........s.....................................EE......................ss...s.s....sss.s....s..........................................................
======================================================================
ERROR: test_generic_forward_ref (test_typing.GenericTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ambv/Dropbox/Python/typing/src/test_typing.py", line 892, in test_generic_forward_ref
    {'x': List[List[CC]]}
  File "/Users/ambv/Dropbox/Python/typing/src/typing.py", line 649, in inner
    return cached(*args, **kwds)
  File "/Users/ambv/.venvs/typing32/lib/python3.2/functools.py", line 189, in wrapper
    cache_popitem(0)    # purge least recently used cache entry
  File "/Users/ambv/.venvs/typing32/lib/python3.2/collections.py", line 126, in popitem
    del self.__map[key]
KeyError: (typing.Callable, (_ForwardRef('T'), _ForwardRef('T')))

======================================================================
ERROR: test_generic_hashes (test_typing.GenericTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ambv/Dropbox/Python/typing/src/test_typing.py", line 819, in test_generic_hashes
    self.assertEqual(mod_generics_cache.B.A[B.A[str]],
  File "/Users/ambv/Dropbox/Python/typing/src/typing.py", line 649, in inner
    return cached(*args, **kwds)
  File "/Users/ambv/.venvs/typing32/lib/python3.2/functools.py", line 189, in wrapper
    cache_popitem(0)    # purge least recently used cache entry
  File "/Users/ambv/.venvs/typing32/lib/python3.2/collections.py", line 126, in popitem
    del self.__map[key]
KeyError: (typing.Tuple, (_ForwardRef('T'),))

----------------------------------------------------------------------
Ran 211 tests in 0.101s

FAILED (errors=2, skipped=18)
```

Should I release with this? I vote "yes" along with officially dropping 3.2 support. It's a pain to set up these days:
* you need to find a way to install this Python version on latest macOS
* you need to pin to a version of `virtualenv` from 2015 and a version of `pip` from 2015
* because of the above, you cannot simply use `tox` (it depends on a single version of `virtualenv` so you either get 3.2 support or 3.6 support)

BTW, I updated README.rst with some information on how to set up a proper local testing environment for everything.

**Comment by ilevkivskyi** [comment]
The error is really strange (something with LRU cache). By the way there is an issue for dropping 3.2 support https://github.com/python/typing/issues/374.

Somehow 3.2 is quite different from other Python 3 versions, I remember introducing special code many times to support especially this version, but there are very few special-casing for other versions. I also vote for dropping 3.2 support.

**Comment by ambv** [comment]
The failures indeed go away if I remove `lru_cache` usage. But then a different test fails that does expect the cache to be there (doing `is` comparisons).

Looks like mypy itself does not attempt to run under 3.2.

Alright, so I'm going to make a call here and release without the 3.2 trove classifier, leaving the 3.2 breakage unsolved.

**Comment by ambv** [comment]
Released: https://pypi.python.org/pypi/typing/3.6.1

**Comment by gvanrossum** [comment]
SGTM. For Python 3.2 people can use the previous version (3.5.3).

**Comment by gvanrossum** [comment]
Did you do some basis testing of the release?

**Comment by ambv** [comment]
Yes, any `pip install mypy` on Python 3.3 and 3.4 now will trigger downloading `typing==3.6.1`. I did that on a virtualenv, and ran mypy successfully over a few runs.

I'll think about a more standard post-release test procedure.

**Comment by ilevkivskyi** [comment]
Thank you Łukasz!
