### ISSUE TITLE
NamedTuple __doc__ contains generated value even when specified explicitly

### ISSUE THREAD

**Issue by Stiivi** [python/typing#404]
When creating a named tuple subclass, the `__doc__` string contains generated value instead the one provided:

```python
from typing import NamedTuple

class Thing(NamedTuple):
    """This is a thing"""
    value: int

print(Thing.__doc__)
```

Prints `Thing(value,)` instead of expected `This is a thing`.

**Comment by JelleZijlstra** [comment]
This is actually fixed in master (probably by @ilevkivskyi's change to allow methods):

```
In [3]: class F(typing.NamedTuple):
   ...:     "hello"
   ...:     x: int
   ...:     

In [4]: F.__doc__
Out[4]: 'hello'
```
So it should work if you upgrade to 3.6.1 (which was just released) or to the pypi version of typing that will hopefully be released very soon.

**Comment by ilevkivskyi** [comment]
Yes, I verified this works on master, therefore I think there is no reason to keep this open.
Only mypy fix is needed.
