### ISSUE TITLE
Unable to declare types of objects contained within a numpy array

### ISSUE THREAD

**Issue by henryJack** [python/typing#410]
Hi, There seems to be an issue assigning element types to a numpy array. This function works fine...

```
def function(matrix: np.ndarray):
    determinant = matrix.det
```

However this function,

```
def function(matrix: np.ndarray[float]):
    determinant = matrix.det
```

returns an error `TypeError: 'type' object is not subscriptable`

I'm not sure if this is a bug or an suggested enhancement!

**Comment by ilevkivskyi** [comment]
This is not really a ``typing`` problem. ``numpy`` does not provide generic versions of their classes, maybe only in custom stubs. For such cases you could just enclose the type in quotes:
```python
def function(matrix: 'np.ndarray[float]'):
    determinant = matrix.det
```
All static type checkers will still understand this.

**Comment by henryJack** [comment]
Okay Brilliant, thanks for the reply!

**Comment by ilevkivskyi** [comment]
> I am struggling to find out exactly what the single quotes around the type does in this situation. From what I can see this is a forward "forward reference"?

Essentially, quotes are used in all situations where you use _something_ only for the sake of static type checking, and want to "hide" this _something_ from Python runtime.

**Comment by ilevkivskyi** [comment]
I am closing this since it seems that the original question is answered now. Feel free to reopen if you have further concerns/questions.

**Comment by henryJack** [comment]
The answer was very helpful. Thanks for taking the time to answer!

**Comment by SyedMuhammadMujtabaZaidi** [comment]
fuck off
