### ISSUE TITLE
ECMAScript 2015

### ISSUE THREAD

**Issue by 24RaquelL** [python/typing#414]
How do you declare a variable named progress without a value?

**Comment by JelleZijlstra** [comment]
I hope you're aware that this repo is about typing in Python, not ECMAScript?

**Comment by ilevkivskyi** [comment]
I am not sure what this question is about, but in _Python 3.6_ you could write:
```python
progress: float
```

**Comment by 24RaquelL** [comment]
@JelleZijlstra @ilevkivskyi thank you for responding and for your help.                                                       
 I did happen to find the answer.  And also did input in the wrong area. It's for javascript  not Python.                                                                                                     
  Answer:   let progress;                                                                                                                               I
