### ISSUE TITLE
Add runtime support for optional types

### ISSUE THREAD

**Issue by ilevkivskyi** [python/typing#420]
While working on ``-strict-optional`` mode in mypy, I noticed patterns like this many times:
```python
def func(x: Optional[X]) -> Optional[Y]:
    if x is None:
        return None
    # do some stuff with 'x'
```
The most recent example appeared in https://github.com/python/mypy/issues/3295. I could imagine this pattern (monadic behaviour) is quite common. If one uses "error as value" (i.e. passing ``None`` instead of using an exception), then the above pattern is necessary for "piping". Maybe we could provide a decorator that will automatically add such behaviour to a function, schematically:
```python
def maybe(func):
    def inner(*args):
        if None in args:
            return None
        return func(*args)
    return inner

@maybe
def convert_to_str(x):
    return 'converted: ' + str(x)
```
The decorator is very simple, but the thing it does looks very common.

**Comment by davidfstr** [comment]
@ilevkivskyi I'm not convinced this pattern is common enough to put in the `typing` module. Seems like something you'd put in your own codebase.

**Comment by srittau** [comment]
This also looks unrelated to typing, more something I'd expect in `functools`. I'm closing this here for now.
