### ISSUE TITLE
official api method to check if a Type is parametrized or not

### ISSUE THREAD

**Issue by smarie** [python/typing#423]
Hello there,

I am relying on PEP484 in a declarative parser/converter registry project, where the user can e.g. say "please parse a `Dict[str, Tuple[pd.Dataframe, pd.Series]]` from this directory".
In several places in the code I end up having to check if a given `Type` is parametrized or not, and find its 'base' non-parametrized type.

At present there is an unofficial way to do that : check if the  `cls.__origin__` field exist and is not `None`. Maybe this should be worth putting in the official API with a couple methods such as `is_parametrized`,  and `get_base_type`. What do you think ?

Thanks for this great tool

**Comment by smarie** [comment]
Also I forgot to mention that checking if a `Type` is generic is also tricky. Of course you can use `issubclass(cls, Generic)` but is does not work with all types : for example `issubclass(Any, Generic)` raises a `TypeError`.
So here again, a simple `is_generic` method in the API would help (or, making `issubclass` work for all types)

**Comment by markshannon** [comment]
`issubclass` is for testing whether a *class* is a sub-class of another. If you want to check whether a *type* is a subtype of another you will need to use a type-checker.

**Comment by smarie** [comment]
Thanks @markshannon  ; not sure I understand your answer since a couple of sources on the internet seem to say that the class/type difference [does not exist anymore](http://stackoverflow.com/questions/35958961/class-vs-type-in-python?answertab=votes#tab-top). But anyway this is not my point - my point here is that, as users, we should be able to access to higher-level information in a quite stable way (such as knowing if a typing type is generic, knowing its parameters if it is parametrized, etc.). Since I started my development a couple months ago, the internal way to represent types in typing module has changed quite a bit (the most important change being 2589b22bfa2823f5f5563e9c5bd6d43cd13efef8, but it is not the only one - for example a parametrized `Tuple` parameters used to be stored in `__tuple_params__`, now they are in `__args__`, etc.). 

And it might change again in the future, for sure - that's reflecting how dynamic the language is :+1: . However the concepts of generic type, parametrized type, and parameters are probably stable now - hence the suggestion to provide a few stable documented methods in the API to access this information.

Kind regards

**Comment by JelleZijlstra** [comment]
This looks like a use case for typing_inspect (#377).

**Comment by ilevkivskyi** [comment]
@smarie 
The ``typing`` module still has the [provisional status](https://docs.python.org/3/glossary.html#term-provisional-api), so that there may be changes in API until Python 3.7 is released next year. The ``typing_inspect`` sub-project (see #377 mentioned by @JelleZijlstra ) is designed exactly for your needs. It will be released as a _separate_ package on PyPI within few days. When the API stabilizes, it will be made a part of the ``typing`` module.

**Comment by smarie** [comment]
This is great, thanks a lot @ilevkivskyi ! I'll have a try when it's ready.

**Comment by ilevkivskyi** [comment]
The ``typing_inspect`` is now published as a separate package:
https://pypi.python.org/pypi/typing-inspect
https://github.com/ilevkivskyi/typing_inspect

Please try it and comment on the API. After the API is settled, some introspection functions may be added directly to ``typing``.

**Comment by smarie** [comment]
Thanks for the proposal @ilevkivskyi ; I'll have more time to have a look in the upcoming weeks and try to provide constructive feedback.

**Comment by smarie** [comment]
So I finally found some time to try. It works, https://github.com/smarie/python-parsyfiles/issues/4 is now closed on my side.
