### ISSUE TITLE
Add typing.generics module for generic versions of stdlib classes

### ISSUE THREAD

**Issue by ilevkivskyi** [python/typing#425]
I have seen many situations where it was necessary to annotate something with a class that is generic in typeshed, but not  generic at runtime. Typical examples are ``OrderedDict[KT, VT]``, ``PathLIke[AnyStr]``, ``Queue[T]``, ``Future[T]``, etc. Now one should use "forward references" for this:
```python
def func(input: 'Queue[int]') -> int:
    ...
```
Generic versions of all these classes can be defined as one-liners using the _internal_ ``__extra__`` API. Then the corresponding typeshed stub will be just:
```python
from collections import OrderedDict as OrderedDict
from queue import Queue as Queue
...
```

**Comment by gvanrossum** [comment]
I'm not sure what's wrong with the forward reference form? I'd hate the typing module to start depending on everything, like `six.moves`. Maybe it's time to make such classes generic in the stdlib though? What's the downside there?

**Comment by ilevkivskyi** [comment]
> I'm not sure what's wrong with the forward reference form?

Just an inconvenience that mypy can't detect where forward reference is needed. And then it could crash at runtime.

> Maybe it's time to make such classes generic in the stdlib though? What's the downside there?

I think it would be even better from convenience point of view. Possible downside is that generic classes are slower with ``isinstance()`` and ``issubclass()`` (mostly because they are ABCs).

**Comment by markshannon** [comment]
Performance.

```python
>>> list.mro()
[<class 'list'>, <class 'object'>]
>>> typing.List.mro()
[typing.List, <class 'list'>, typing.MutableSequence, <class 'collections.abc.MutableSequence'>, typing.Sequence, <class 'collections.abc.Sequence'>, typing.Reversible, <class 'collections.abc.Reversible'>, typing.Collection, <class 'collections.abc.Collection'>, <class 'collections.abc.Sized'>, typing.Iterable, <class 'collections.abc.Iterable'>, typing.Container, <class 'collections.abc.Container'>, typing.Generic, <class 'object'>]
```
That's a lot of extra stuff to wade through to find a method.

**Comment by JukkaL** [comment]
I think that a better option would be for mypy to give an error if user incorrectly doesn't use a forward reference for some type.

**Comment by ilevkivskyi** [comment]
> I think that a better option would be for mypy to give an error if user incorrectly doesn't use a forward reference for some type.

The problem with this approach is that it could be tricky to detect such classes (generic in typeshed but non-generic at runtime) automatically. A possible option would be of course to just manually make a list of "prohibited" generics like we already did with ``list[int], deque[str], defaultdict[int, str]``, etc.

**Comment by srittau** [comment]
I believe this is now mostly solved by PEP 585. If there are still classes that should be made generic in the stdlib, it's most likely a better (and more consistent) approach to do so than to add an extra module, and now there is precedence for that.
