### ISSUE TITLE
More general NamedTuple

### ISSUE THREAD

**Issue by djetelina** [python/typing#426]
I have a wrapper method that returns a NamedTuple from psycopg - since I don't know  what will be passed to select, I don't know what the NamedTuple will have as names. Currently there is no way to  be 'generous' with NamedTuple. 

Perhaps this is a MyPy issue, if so I'm sorry and I'll redirect my issues there, but I'd love to type hint NamedTuple either without the `[]` 'arguments', or have an option to annotate with generics like `str`

**Comment by ilevkivskyi** [comment]
Just to clarify, you want to annotate something like this:
```
class N(NamedTuple):
    <unknown name>: <unknown type>
    <bunch of such items>
```
But why annotating this with just ``tuple`` is not enough? If you don't know attribute names, then you cannot use them anyway. If you know types and number of fields you can use ``Tuple[T1, T2, T3]``.

**Comment by iScrE4m** [comment]
In the scope of the wrapper method, I don't know either the names, nor the types. However, from the scope of a function calling it, I know what I'm going to get. Here's the code I'm talking about:

### wrapper

```
   def select(self, query: str, *args) -> NamedTuple:
        """Wrapped execute around select statement for single result"""
        with self.cursor as cur:
            cur.execute(query, args)
            result = cur.fetchone()
            log.debug("Ran select query\n'%s'\nResult: %s", _query_for_log(cur.query), result)
        return result
```
### code calling it

```
    def __load_from_db(self):
        """Loads the ingredient from the database"""
        query = """
        SELECT unit, ingredient_type, suggestion_threshold, rebuy_threshold, durability
        FROM ingredient
        WHERE id = %s
        """
        res = db.select(query, self._id)
```

**Comment by gvanrossum** [comment]
It sounds like you're expecting the static type checker to understand which fields are returned by the query. That's not currently possible, so your best bet is probably a cast.

**Comment by ilevkivskyi** [comment]
> I know what I'm going to get

The question is do you know this _statically_? If you want to have a type that depends on a value (string containing the attribute name), then this can be only done with dependent types. The latter is quite advanced concept, that might get only limited support.

**Comment by iScrE4m** [comment]
I don't need the typechecker to know these things, but I want to write a type annotation that is intuitive. I know I'll get NamedTuple of unspecified parameters, so writing `: NamedTuple, ...` without specifications makes the most sense to me  and makes annotating a lot less painful.

**Comment by ilevkivskyi** [comment]
> so writing ``: NamedTuple, ...`` without specifications makes the most sense to me and makes annotating a lot less painful

If you just want to allow writing "bare" ``NamedTuple``, then probably this should be discussed at mypy tracker. You can open an issues there and explain what are the compatibility rules for bare ``NamedTuple`` (i.e. whether ``NamedTuple`` is a subtype of ``tuple``, and all "concrete" named tuples are subtypes of the bare one etc.)

**Comment by gvanrossum** [comment]
Well, we could debate the design here too, since NamedTuple is part of PEP 484.

**Comment by iScrE4m** [comment]
I personally probably won't have too much to add, as I don't understand typing that well. Just that it's a common occurance for me when annotating, that there isn't really one obvious way to do it, I keep browsing docs a lot and wondering. Another example would be how to annotate uninitiated class - builtin object doesn't have `__name__` - perhaps typing could try and go towards more 'friendlier' approach :)

**Comment by ilevkivskyi** [comment]
@iScrE4m 
Sorry for my ignorance, but what is "uninitiated class"? Could you please elaborate more on this?

**Comment by iScrE4m** [comment]
Sure, here's my error handler:

```python
class DoesNotExist(Exception):
    """When something does not exist"""

    def __init__(self, what: object, identifier: str = '-', add_info: Union[None, str] = None) -> None:
        """
        :param what:            The wanted object (uninitiated)
        :param identifier:      The identifier (primary key) for the object
        :param add_info:        Additional info
        """
        # We care about the name of the class itself
        self.what: str = what.__name__
        self.identifier: str = identifier
        self.add_info: Union[None, str] = add_info

    def __str__(self):
        message = f'Error: {self.what} identified by {self.identifier} does not exist. '
        if self.add_info is not None:
            message += self.add_info
        return message
```

the 'what' parameter is a class (not an instance), e.g. 

```python
class Ingredient:
    pass
```

**Comment by ilevkivskyi** [comment]
If I understand you correctly, you should use ``what: Type[object]`` (or ``Type[Any]``, or ``Type[BaseClass]``, etc. depending on your needs) see the [docs](https://docs.python.org/3/library/typing.html#typing.Type).

**Comment by ilevkivskyi** [comment]
@iScrE4m 
Also I noticed you are using ``Union[None, str]`` in few places. It is better to use ``Optional[str]`` (which is shorter, and probably more readable).

**Comment by srittau** [comment]
This seems out of scope for static type checking.
