### ISSUE TITLE
Referencing objects before their assignment

### ISSUE THREAD

**Issue by iScrE4m** [python/typing#428]
I have a single file with two objects, `A` and `B`. `A` is a category for `B`. 

* `B.category` returns `A`, which can be type hinted just fine.
* `A` has a method `A.list()` that returns list of `B` in that category. This is problematic

In order to type hint the return of `A.list` I have to either split objects into separate files and crossimport, or define a parent class for `B`, which has all of it's attributes and methods but no implementation and type hint that `def list() -> List[BMeta]`. I don't like either of the approaches.

Why are type hints being processed at import time? Is there a better solution and am I just missing something? Somehow I feel that whatever I chose I'm not really being pythonic.

**Comment by gvanrossum** [comment]
I presume you're looking for a forward reference. Just put the type annotation in quotes.

**Comment by iScrE4m** [comment]
Oh my bad, it's at the very bottom of the documentation, very easy to miss, sorry!
