### ISSUE TITLE
Document GenericMeta

### ISSUE THREAD

**Issue by gvanrossum** [python/typing#430]
There are some use cases where GenericMeta is essential (e.g. when combining Generic[T] with a custom metaclass). We should document that it exist, and what you can safely override (the implementation looks a bit brittle if people were to start subclassing this with impunity).

**Comment by ilevkivskyi** [comment]
Possible solution is to re-use docstrings https://github.com/python/typing/blob/master/src/typing.py#L927-L947 that already mention several restrictions. Maybe we should also add a warning like "Any use of GenericMeta except explicitly documented here is subject to breakage without warning."

**Comment by gvanrossum** [comment]
I think we should also provide several examples.

**Comment by JelleZijlstra** [comment]
`GenericMeta` no longer exists, so we shouldn't document it.
