### ISSUE TITLE
Coroutine functions should return Coroutine, not Awaitable

### ISSUE THREAD

**Issue by jpochyla** [python/typing#441]
```python
async def coro_func() -> None:
    pass
c = coro_func()
reveal_type(c)  # prints typing.Awaitable[builtins.None]
```

`c` above has all fields of `typing.Coroutine`, you can `send` and `throw` on it, but the type doesn't reflect that. Why?

**Comment by JelleZijlstra** [comment]
This seems like a mypy issue, not a typing issue. I agree though that Coroutine makes more sense, but I'm not deeply familiar with the async-related type hierarchy.

**Comment by ilevkivskyi** [comment]
Yes, I just checked, and it looks like all examples in typing docs and in PEP 484 are correct. So that this is a purely mypy issue. @jpochyla could you please close this one and open anew one at mypy tracker?

**Comment by gvanrossum** [comment]
But you can't iterate over it right?

**Comment by ethanhs** [comment]
@gvanrossum I'm not sure what you mean by "it", but AFAIK coroutines aren't iterable, unless I'm mistaken. If you were asking about the given function, no you cannot iterate over it.

**Comment by gvanrossum** [comment]
I should not respond while on vacation from a phone. I was thinking of regular generators. Sorry!

**Comment by jpochyla** [comment]
Thank you, didn't realize this is in fact mypy issue. Closing in favor of python/mypy#3569
