### ISSUE TITLE
Add possibility of runtime type checking in a similar fashion to asserts

### ISSUE THREAD

**Issue by Yajo** [python/typing#442]
AFAICS by reading the docs, the typing module is just for type hints.

However it would be awesome to have runtime type checking by [following a similar logic to how `assert` works](https://docs.python.org/3/reference/simple_stmts.html#grammar-token-assert_stmt).

This is just a very simplified version of the idea for a couple of decorators that could do this:

```python
def enforced(method):
  """Enforces type hints at runtime when developing."""
  if __debug__:
    return checked_always(method)
  return method

def enforced_always(method):
  """Enforces type hints at runtime always."""
  def wrapper(*args, **kwargs):
    if not hasattr(method, "__annotations__"):
      return method(*args, **kwargs)
    ... # Arg type enforcement happens here, TypeError in mismatches
    result = method(*args, **kwargs)
    ... # result type enforcement happens here, TypeError in mismatches
    return result
  return wrapper
```

The decorators should be smart enough to detect if they decorate a class or a function and [act like `no_type_check`](https://docs.python.org/3/library/typing.html#typing.no_type_check).

Of course, if a method or class has no annotations, the wrapper would do nothing.

With `enforced`, developers can typecheck their code in development machines while adding second to none overhead in production, with optimized code deployed; or they can avoid doing manual type checkings in any methods that actually require them and just leverage that work to the `enforced_always` decorator.

**Comment by JukkaL** [comment]
The typing module won't include runtime checking, but this can be supported by third party modules. For example, https://github.com/agronholm/typeguard seems to be pretty close to what you are proposing.

**Comment by Michael0x2a** [comment]
It sounds like you're not aware of this (correct me if I'm wrong!), but we can use typecheckers like [mypy](http://mypy-lang.org) or Pycharm's built-in type checker to analyze Python code that uses type hints (without running the code!).

Type hints, and the `typing` module, aren't really meant to be used by themselves. You can certainly use them to document your code, but you'll gain the most benefit if you also actually check your hints using one of the programs I mentioned above. 

But if you really do want runtime type checking, I guess you can use libraries like [enforce.py](https://github.com/RussBaz/enforce), though I understand libraries that do runtime type checking aren't as mature and don't necessarily support all of PEP 484 yet.

**Comment by Yajo** [comment]
Oh OK, well I was more or less aware of that, but thank your for the links and explanations!

Python is known to have batteries included, so my proposal was more on that philosophy; I feel it would be good to have a reference implementation in the core python itself. Just a couple of decorators and the usefulness of this module increases to a much wider range of use cases.

But if it's not the purpose of this module, feel free to close this 😋

**Comment by ilevkivskyi** [comment]
@Yajo 
> Python is known to have batteries included, so my proposal was more on that philosophy; I feel it would be good to have a reference implementation in the core python itself.

The point is that it is _very_ difficult to make a complete and reliable runtime type checking system. There are some simple case that are easy like ``isinstance(x, int)`` etc., but when you start adding generic classes, generic functions, covariance and contravariance, etc. (also in nested and mixed ways) things quickly become complicated. This will make the ``typing`` module bulky and very slow (some people already complain that it should be faster).

Therefore it is better to implement the runtime type checks as a third-party package a la ``enforce``, ``typeguard``, ``typecheck-decorator``, etc.

**Comment by gtrak** [comment]
I think [pydantic](https://pydantic-docs.helpmanual.io/) also does runtime type checks with standard python annotations.

**Comment by Foadsf** [comment]
here are some of the available libraries using type hints for runtime type checking:

* [Typeguard](https://typeguard.readthedocs.io/en/latest/)
* [typesentry](https://github.com/h2oai/typesentry)
*[Enforce.py](https://github.com/RussBaz/enforce)
* [pydantic](https://pydantic-docs.helpmanual.io/)
* [sphinx-autodoc-typehints](https://github.com/agronholm/sphinx-autodoc-typehints)
