### ISSUE TITLE
Keep PEP 484 synced with released versions of typing.py

### ISSUE THREAD

**Issue by mihaic** [python/typing#447]
PEP 484, as displayed at python.org, includes features not present in released versions of typing.py on PyPI (e.g., NoReturn). This is confusing.

**Comment by ilevkivskyi** [comment]
> This is confusing.

Maybe, but it was always like this also with other PEPs. PEP stays for Python enhancement _proposal_, i.e. it reflects the desired state (unless the status is ``Final`` which is not the case for PEP 484). The [official docs](https://docs.python.org) on the contrary reflect the _actual_ state. If there is something in the docs that is not implemented or something implemented but not in the docs, then this is a bug that should be reported at https://bugs.python.org.

(Also the next release will hopefully happen within few days.)
