### ISSUE TITLE
Mapping.get(k, v) should accept key types not supported by Mapping[k]

### ISSUE THREAD

**Issue by gvanrossum** [python/typing#448]
This code fails with `mypy --strict-optional`:
```py
a = {1: ''}
def f(k: Optional[int]) -> str:
  return a.get(k, '')  # error: Argument 1 to "get" of "Mapping" has incompatible type "Optional[int]"; expected "int"
```
It's clearly going to work and return a string when called as `f(None)` so this should IMO be supported. In general the argument of get() should be allowed to have a wider type as the declared key type as long as there's overlap (the special case here is important but not the only use case).

I can't decide whether to file this under mypy or typeshed. Maybe it could be solved by adding an extra argument type to typeshed? E.g.
```py
    @overload
    def get(self, k: Union[_KT, object]) -> Optional[_VT_co]: ...
    @overload
    def get(self, k: _Union[_KT, object], default: Union[_VT_co, _T]) -> Union[_VT_co, _T]: ...
```

**Comment by ilevkivskyi** [comment]
``Union[_KT, object]`` is just ``object``. Also, this is a backward incompatible change. If someone has a subclass of ``Mapping`` that overrides ``get``, then it will start emitting "Incompatible with supertype ..." errors (due to the contravariant behaviour in argument types).

**Comment by gvanrossum** [comment]
Hm, that's unfortunate but true. I wonder if a mypy plugin could do something like forcing the type to the type of the `default` argument (or its default) when the type of the first argument doesn't overlap with the key type.

**Comment by ilevkivskyi** [comment]
I think this issue rather belongs to mypy and/or typeshed, so I am closing it here.
