### ISSUE TITLE
Provide wheel distribution on PyPI

### ISSUE THREAD

**Issue by edmorley** [python/typing#450]
Hi!

Please could the PyPI package also by made available as a wheel?
https://pypi.python.org/pypi/typing/3.6.1

Wheels have the following advantages:
* Faster installation time
* Allows the wheel cache to work even when using the new pip hash-checking mode
* Allows tools to statically inspect the package metadata without having to execute untrusted code.

Since typing uses different source directories for Python 2 vs 3, I'm presuming separate wheels will have to be generated for each, per:
 https://packaging.python.org/tutorials/distributing-packages/#pure-python-wheels

The Python packaging guide recommends using [Twine](https://github.com/pypa/twine) to upload packages:
https://packaging.python.org/tutorials/distributing-packages/#uploading-your-project-to-pypi

As such, the steps for building/uploading a new release are then:

```bash
$ pip2 install -U twine setuptools wheel
$ pip3 install -U setuptools wheel
$ rm -rf dist/ build/
$ python2 setup.py sdist bdist_wheel
# Work around https://bitbucket.org/pypa/wheel/issues/147/bdist_wheel-should-start-by-cleaning-up
$ rm -rf build/
$ python3 setup.py bdist_wheel
$ twine upload dist/*
```

The PyPI package listing will then display three entries for the new release, one with type "Source" and two of type "Python Wheel" (one for each of Python 2 and 3).

Many thanks :-)

Note:
distutils doesn't support the `bdist_wheel` command, so the distutils usage in `setup.py` will also need switching to setuptools.

**Comment by ilevkivskyi** [comment]
I think this is a good idea. By the way, it is probably time to release ``typing 3.6.2``, so that we can test this.
@gvanrossum @ambv what do you think?

**Comment by gvanrossum** [comment]
Yes, sounds like a good idea.

**Comment by ilevkivskyi** [comment]
> Yes, sounds like a good idea.

You, @JukkaL, @ambv, and @vlasovskikh have PyPI push permissions. Who would like to make the release?

**Comment by gvanrossum** [comment]
I can do it. Is there anything left to do in the repo before I release these?

**Comment by gvanrossum** [comment]
FWIW I plan to tag 74bc3ee as 3.6.2, as that's the last commit that touched anything and at that point typing.py is the same as it is in the CPython 3.6.2 release. However test_typing.py at that commit is *not* the same as in CPython 3.6.2 -- here we use `collections_abc.Sequence` etc., while CPython 3.6.2 uses `collections.Sequence`. It's been fixed in CPython's master branch, so I think it's okay this way.

**Comment by gvanrossum** [comment]
(Actually I need to branch from there to bump the version in setup.py to 3.6.2.)

**Comment by gvanrossum** [comment]
Can someone please look at the strange setup issues I ran into, in #453? Maybe @graingert ?

**Comment by ilevkivskyi** [comment]
> It's been fixed in CPython's master branch, so I think it's okay this way.

So ``cpython/amster`` and ``typing/master`` are now in sync? I remember I manually copied one of Serhiy's commit where he replaced ``collections.X`` with ``collections.abc.X`` (in preparation to deprecate re-export of ABCs to ``collections``).

**Comment by gvanrossum** [comment]
Almost -- typing/master's 2b6932a85a3b5e2f334c596035d7abefdcbbb0d7 is not yet copied into cpython/master.

**Comment by edmorley** [comment]
Note - when generating separate Python 2 and 3 wheels, wheel doesn't clean out the `build/` directory itself ([see here](https://bitbucket.org/pypa/wheel/issues/147/bdist_wheel-should-start-by-cleaning-up)), so I've updated the instructions in the OP to include an additional `rm -rf build/`.
