### ISSUE TITLE
`Type[None]` should return `NoneType`, not `Type[NoneType]`

### ISSUE THREAD

**Issue by ambv** [python/typing#451]
Title says all.

Otherwise there is no other way to alias `NoneType` on Python 3 (it's no longer in types). mypy doesn't understand that `void = type(None)` is an alias, and thus `void` is an invalid type. The only way to do this currently is to write `void = Union[None]` which is a hack.

**Comment by ethanhs** [comment]
On MyPy 0.511 and 0.530 (git) with:
```python
void = type(None)
reveal_type(void)
```

I get `main.py:2: error: Revealed type is 'Type[builtins.None]'`. 

Additionally there is an open issue https://github.com/python/mypy/issues/640 about it.

**Comment by ilevkivskyi** [comment]
There is also https://github.com/python/mypy/issues/3269

I think we should just fix mypy instead of tweaking PEP 484, especially that I had a fix somewhere on a local branch, I will make a PR shortly.

**Comment by ilevkivskyi** [comment]
@ambv Sorry, was distracted, here is the PR https://github.com/python/mypy/pull/3754
