### ISSUE TITLE
typing.NamedTuple should add annotations to its constructor (__new__) parameters.

### ISSUE THREAD

**Issue by anntzer** [python/typing#454]
Currently, the fields, types and defaults used to define a typing.NamedTuple need to be retrieved from three different attributes: `_fields`, `_field_types`, and `_field_defaults` (the first two are combined in `__annotations__`, but that still misses the defaults).

However, there is a place where all this information can be naturally combined: in the Signature of the constructor (as returned by `inspect.signature(cls)`).  Currently, the Parameter objects in the signature have the information about the parameter names and defaults, but their annotation is not set.

Thus, I would like to propose setting the annotation of the Parameters in the Signature object as well.

(Initially posted as http://bugs.python.org/issue31006.)

**Comment by psarka** [comment]
Some screen shots from jupyter notebook showing why this idea is nice:
https://github.com/ipython/ipykernel/issues/305
