### ISSUE TITLE
TypeError: Cannot re-parameterize tuple

### ISSUE THREAD

**Issue by jhance** [python/typing#456]
I am not sure how to reproduce in a smaller file, whats weird here is that it doesn't crash on the first use of the type....

https://github.com/JukkaL/mypyc/blob/151f7c23ab361b413375575f9c31d6c48d992a1b/mypyc/analysis.py

Trying to run tests here fails with

```
_________________ ERROR collecting mypyc/test/test_analysis.py _________________
mypyc/test/test_analysis.py:16: in <module>
    from mypyc import analysis
mypyc/analysis.py:134: in <module>
    initial_defined: Set[Register]) -> AnalysisResult[Register]:
/usr/lib/python3.5/typing.py:700: in __getitem__
    raise TypeError("Cannot re-parameterize %r" % (self,))
E   TypeError: Cannot re-parameterize typing.Tuple[typing.Dict<~KT, ~VT>[typing.Tuple[<function NewType.<locals>.new_type at 0x7fc1f9772400>, int], typing.Set<~T>[~T]<~T>]<~T>, typing.Dict<~KT, ~VT>[typing.Tuple[<function NewType.<locals>.new_type at 0x7fc1f9772400>, int], typing.Set<~T>[~T]<~T>]<~T>]
```

but the file typechecks with mypy.

**Comment by ilevkivskyi** [comment]
Thanks for reporting! This is because you are using an old version of ``typing``. This has been already fixed (around half year ago, so I would guess in 3.5.3).
