### ISSUE TITLE
TypeError: duplicate base class Sequence

### ISSUE THREAD

**Issue by mitar** [python/typing#457]
There is a difference between Python 3.5 (where it does not fail) and Python 3.6:

```python
type('foo', (typing.Sequence[typing.T_co], typing.Sequence), {})
abc.foo<+T_co>
```

```python
type('foo', (typing.Sequence[typing.T_co], typing.Sequence), {})
TypeError: duplicate base class Sequence
```

**Comment by ethanhs** [comment]
This seems to be due to using an older version of 3.5 and thus typing. I just tested on 3.5.4 and got the `TypeError`, as expected.

**Comment by mitar** [comment]
I am on 3.5.2. This is expected? Hm. Because it is not really true that they are equal:

```
typing.Sequence[typing.T_co] == typing.Sequence
False
```

**Comment by ilevkivskyi** [comment]
This should be (and is, in both latest versions of 3.5 and 3.6) treated as duplicate bases, since generics are erased at runtime (see PEP 484).

**Comment by mitar** [comment]
The question is, how to detect/prevent that before passing it in, because equality returns false. Where is this check being done.

**Comment by ilevkivskyi** [comment]
You could use ``typing_inspect`` for this, namely ``typing_inspect.get_origin(base)``, if this will be frequently asked, some functionality from ``typing_inspect`` will be added to ``typing`` in future versions.
