### ISSUE TITLE
isinstance and issubclass should return NotImplemented instead of throwing an exception

### ISSUE THREAD

**Issue by mitar** [python/typing#465]
If I want to check if function argument matches expected type, for most values I can just do:

```
isinstance(argument, argument_type)
```

The issue is that if user specified `argument_type` as a parameterized generics, this throws an exception. A very general TypeError. This is problematic because:
* I can try to check if `argument_type` is something which will throw an exception if I call `isinstance` on it, but that would mean I would have to repeat test code inside `__subclasscheck__`, DRY
* I can call it and see if there is a `TypeError`, but then it is tricky to know why call is raising a `TypeError` (maybe a subclass of `TypeError` would be better)

So I think maybe returning `NotImplemented`, like `__eq__` does would be better, because then I could try a different way to check if input value matches the argument type by checking the return value.

**Comment by ilevkivskyi** [comment]
The [docs](https://docs.python.org/3/library/functions.html?highlight=isinstance#isinstance) explicitly specify that ``isinstance`` and ``issublcass`` should always return ``True`` or ``False`` or raise a ``TypeError``, so that this is not only about ``typing``. Instead, you should use ``typing_inspect.get_origin`` to get the unsubscripted version and check against it.

**Comment by mitar** [comment]
I am not sure how can `typing_inspect.get_origin` help me know if I have to do custom check, or if I can use `isinstance`. Even if I do `isinstance(argument, typing_inspect.get_origin(argument_type))` I still do not know if I have to parameters or not.

**Comment by mitar** [comment]
Also, in doc it is written:

> If classinfo is not a type or tuple of types and such tuples, a TypeError exception is raised.

This does not prevent raising some other exception when called on a subscripted version of a type. (Because that is still a type, so it does not match a condition in docs.)

**Comment by ilevkivskyi** [comment]
> I still do not know if I have to check parameters or not.

There are other functions that will give you actual parameters, can check if it is actually a generic etc.
In general, I think defining a special exception class for this is an overkill. This is a case where LBYL is probably better than EAFP.

**Comment by gvanrossum** [comment]
Let's close this. If something is not a valid class it should not be used as the second argument of isinstance() or issubclass().
