### ISSUE TITLE
Release typing_extensions to PyPI

### ISSUE THREAD

**Issue by gvanrossum** [python/typing#467]
@JukkaL and I were discussing steps towards rolling out Protocols. An important step is releasing the typing_extensions package to PyPI. @ilevkivskyi are you interested in taking on this task? It's not hard -- create a PyPI account, and use twine (`pip install twine`) to upload it.

**Comment by ilevkivskyi** [comment]
Yes, I first need to finish few remaining issues found in CR of #464 (hopefully before the end of this week). I already have an account on PyPI (I published ``typing_inspect``). The account name is the same as my GitHub account name.

**Comment by episodeyang** [comment]
Looking forward to seeing this on PyPI!

**Comment by ilevkivskyi** [comment]
OK, the package is now on PyPI!
