### ISSUE TITLE
Source dist only contains source for one Python version

### ISSUE THREAD

**Issue by gvanrossum** [python/typing#475]
The source distribution (built with `python setup.py sdist`, and uploaded to PyPI as `typing_extensions-3.6.2.tar.gz`) only contains the source for the Python version used to run `setup.py`. It so happens that the file on PyPI has only the `src_py2` subdirectory.

This breaks installation of typing_extensions with the `--no-binary :all:` flag (which we happen to use at Dropbox because we don't trust externally built wheels).

I'm not sure how to fix this but IIRC we had a similar issue with mypy and we solved it with some setup.cfg or setup.py magic. Or a `MANIFEST.in`. (I don't recall, sorry.)

**Comment by ilevkivskyi** [comment]
I have added ``MANIFEST.in``, this seems to fix the problem. I have released typing-extensions 3.6.2.1 on PyPI. Could please test that it works?

**Comment by gvanrossum** [comment]
Yup, it works!

The src_py3 directory has spurious egg info, but it doesn't seem to hurt anything.
