### ISSUE TITLE
TypeError: Parameterized generics cannot be used with class or instance checks

### ISSUE THREAD

**Issue by daegontaven** [python/typing#477]
I'm using pytest to run my tests on travis. However, I'm getting this error during one of the tests.

```python3.5.3
../../../virtualenv/python3.5.3/lib/python3.5/_collections_abc.py:773: in update
    if isinstance(other, Mapping):
../../../virtualenv/python3.5.3/lib/python3.5/abc.py:191: in __instancecheck__
    return cls.__subclasscheck__(subclass)
../../../virtualenv/python3.5.3/lib/python3.5/abc.py:226: in __subclasscheck__
    if issubclass(subclass, scls):
../../../virtualenv/python3.5.3/lib/python3.5/abc.py:207: in __subclasscheck__
    ok = cls.__subclasshook__(subclass)
/opt/python/3.5.3/lib/python3.5/typing.py:860: in __extrahook__
    if issubclass(subclass, scls):
../../../virtualenv/python3.5.3/lib/python3.5/abc.py:207: in __subclasscheck__
    ok = cls.__subclasshook__(subclass)
/opt/python/3.5.3/lib/python3.5/typing.py:851: in __extrahook__
    _valid_for_check(cls)
/opt/python/3.5.3/lib/python3.5/typing.py:837: in _valid_for_check
    raise TypeError("Parameterized generics cannot be used with class "
E   TypeError: Parameterized generics cannot be used with class or instance checks
```
[View Travis Log](https://travis-ci.org/AlphaHooks/AlphaHooks/jobs/282167097#L602)

I'm not sure where the problem occurs in my code because I'm not directly using the typing module. And I don't believe any of the dependencies are either. So it could be because I'm using `getattr()` in my code the wrong way(inside a decorated function). [This](https://github.com/AlphaHooks/AlphaHooks/blob/11f8a80dbd5dd2de7e431e7bff4a22a0bb710df1/tests/windows/settings/test_root.py#L30) is where I use the function.

I'm not sure if this is the result of a bug in python since it occurs in `3.5` and not in `3.6`.

**Comment by ilevkivskyi** [comment]
Hm, strange, I though this was fixed in Python 3.5.3. Could you please try this on 3.5.4?

**Comment by daegontaven** [comment]
@ilevkivskyi Okay, so the tests [passed](https://travis-ci.org/AlphaHooks/AlphaHooks/jobs/282198655) for `3.5.4`. I guess it must be just 3.5.3 then.

**Comment by ilevkivskyi** [comment]
Then you need to switch to ``3.5.4``, there is no way we can fix this in ``3.5.3`` (it is already released).

**Comment by thundergolfer** [comment]
Seeing this issue on Python 3.6.10

```
/nix/store/qi1ck7cwybdqk3llpad23yxwbji2azi9-python3-3.6.10/lib/python3.6/typing.py:1162: in __instancecheck__
    return issubclass(instance.__class__, self)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = typing.List[search.solr_ltr.src.model_serde.serialize.Feature]
cls = <class 'list'>

    def __subclasscheck__(self, cls):
        if self.__origin__ is not None:
            if sys._getframe(1).f_globals['__name__'] not in ['abc', 'functools']:
>               raise TypeError("Parameterized generics cannot be used with class "
                                "or instance checks")
E               TypeError: Parameterized generics cannot be used with class or instance checks
```

**Comment by gvanrossum** [comment]
@thundergolfer I doubt that what you are seeing is the same thing as the (very old, and fixed) problem originally reported in this issue. Trust the message.

**Comment by thundergolfer** [comment]
Fair point. I've too strongly pattern matched against the error string here. 

I was attempting to compare a `Field.type` from a `dataclass`  against the object returned from running `type` or `isinstance` on the field's value. 

From more reading around and more thinking, the `Field.type`'s information is not compatible with simple `isinstance` checking.

**Comment by Mastermind-U** [comment]
> Fair point. I've too strongly pattern matched against the error string here.
> 
> I was attempting to compare a `Field.type` from a `dataclass` against the object returned from running `type` or `isinstance` on the field's value.
> 
> From more reading around and more thinking, the `Field.type`'s information is not compatible with simple `isinstance` checking.

Found a solution on StackOverflow, using `__extra__` (3.7<) or `__origin__` (3.7+) attribute:
```python3
for field in dataclasses.fields(obj):
    original_type = getattr(field.type, '__extra__', field.type)  # native types has no this attr
    if not isinstance(value, original_type):
        print('hello')
```
