### ISSUE TITLE
mypy doesn't like typevars with other typevars in the constraints

### ISSUE THREAD

**Issue by daboross** [python/typing#479]
I'm trying to get this code to work, here's a simplified version:

```python
from typing import *

T = TypeVar('T')
C = TypeVar('C', bound=Sequence[T])

def for_fach(list: C, callback: Callable[[T], None]) -> C:
    for item in list:
        callback(item)
    return list
```

This code is of course useless, but it's the simplest version of what I'm trying to do that I could come up with.

This errors with:
```
mypytest.py:4: error: Invalid type "mypytest.T"
mypytest.py:7: error: Need type annotation for variable
```

I'm looking to clarify whether this is a supported usage of typing in python (and this is thus a bug) or if it's intended behavior to not be able to nest TypeVars.

**Comment by ethanhs** [comment]
In the first sentence of "Type Variables with an Upper Bound" PEP 484 [says](https://www.python.org/dev/peps/pep-0484/#id25):

>A type variable may specify an upper bound using bound=\<type> **(note: \<type> itself cannot be parametrized by type variables).**

(Emphasis mine)
So no, you cannot do this. I think you just want `C = Sequence[T]`.

**Comment by ilevkivskyi** [comment]
There are proposals to allow something like this, see for example https://github.com/python/mypy/issues/2756. I think this actually might be useful, also for things like generic self-types.

**Comment by daboross** [comment]
ah ok, this makes sense. I guess it's just annoying how easy complex structures are to model in Python but hard to in Python w/ typing.
