### ISSUE TITLE
Require an argument to implement multiple mixins

### ISSUE THREAD

**Issue by mitar** [python/typing#483]
I have a base class an a set of mixins we are using to combine when defining new classes. The issue is that it seems currently there is no way to define that an argument should inherit from a list of base classes, and not just one:

```
def fun(argument: [BaseClass, CanBeSampledMixin, DescriptionMixin]) -> None:
    ...
```

So this would be that `argument` has to have all of the listed classes somewhere in its inheritance chain. In some way, it is similar to `Union`, maybe an `Intersection`? ;-)

**Comment by ethanhs** [comment]
I believe this is a duplicate of https://github.com/python/typing/issues/213.

**Comment by mitar** [comment]
True! I literally named it the same. :-)
