### ISSUE TITLE
Python vulnerabilities - Violations of the Liskov substitution rule

### ISSUE THREAD

**Issue by stephenmichell49** [python/typing#487]
This is the second issue. Here is the text from the main document (TR 24772-1)

6.42 Violations of the Liskov substitution principle or the contract model  [BLP]

6.42.1 Description of application vulnerability
Object orientation typically allows polymorphic variables containing values of subclasses of the declared class of the variable. Methods of the declared class of a receiving object can be invoked and the caller has the right to expect that the semantics of the interface called upon are observed regardless of the precise nature of the value of the receiving object. Similarly, the existence of accessed components of the declared class needs to be ensured. Instances of subclasses thus need to be both technically and logically specialized instances of the parent class. This is the basis of the Liskov principle. 
The Liskov Principle states that an instance of a subclass is always an instance of the superclass as well if one ignores the added specializations. It implies that inheritance is used only if there is a logical “is-a”-relationship between the subclass and the superclass. Moreover, preconditions of methods can at most be weakened and never strengthened as they are redefined for a subclass. Inversely, postconditions can at most be strengthened and never be weakened by such a redefinition. The caller of an interface needs to guarantee only the preconditions of the interface and is allowed to rely on its postconditions. The rules stated make sure of this property which is also known as the Contract Model.
Violations of the Liskov Principle or the Contract Model can result in system malfunctions as additional preconditions of redefinitions or promised postconditions of interfaces are not met. 
An alternative inheritance semantics is that of “has-a”-relationships, usually appearing in programs in languages with multiple inheritance, where the paradigm is sometimes referred to as a “mix-in”. It is in stark conflict with the Liskow Principle: A polymorphic variable motor of class engine should not be able to hold a car, merely because the subclass car was created by a mix-in of the class engine to the class vehicle. 
The principles stated above apply to implicit as well as explicit preconditions and postconditions. Explicit conditions permit formal reasoning tools to be applied.

6.42.2 Cross reference
CWE: (cwe)
JSF AV Rules: 89, 91, 92, 93 
CERT C++ guidelines: (Clive??)
Ada Quality and Style Guidenone)

6.42.3 Mechanism of failure
When a client calls the method of a class which redispatches to the implementation of a subclass with a strengthened precondition, the client has mechanism to know about the added preconditions to be satisfied. Hence the call may fail on a violated precondition. Similarly, if the called implementation has a weaker postcondition, the postcondition asserted to the client might not be satisfied. As a consequence, the client may fail. Failing to meet preconditions or to guarantee postconditions is bound to cause exceptions or system failures. The specific scenarios are extensive and range from faults that happen to be handled by the system to complete loss of security and safety.
Using visible inheritance to implement a “has-a”-relationships deteriorates class design and thereby may be the cause of consequential errors. There is no immediate failure mode, however. 

6.42.4 Applicable language characteristics
This vulnerability description is intended to be applicable to languages with the following characteristics:
   •	Languages that have polymorphic variables, particularly object-oriented languages.
   •	Languages that provide inheritance among classes.

6.42.5 Avoiding the vulnerability or mitigating its effects
Software developers can avoid the vulnerability or mitigate its ill effects in the following ways:
   •	Obey all preconditions and postconditions of each method, whether they are specified in the language or not.
   •	Prohibit the strengthening of preconditions (specified or not) by redefinitions of methods.
   •	Prohibit the weakening of postconditions (specified or not) by redefinitions of methods. 
   •	Prohibit the use of visible inheritance for “has-a” relationships. Use components of the respective class for “has-a”-relationships instead.
   •	Use static analysis tools that identify misuse of inheritance in the contract model.

6.42.6 Implications for language design and evolution
In future language design and evolution activities, the following items should be considered:
Provide language mechanisms to formally specify preconditions and postconditions.

**Comment by stephenmichell49** [comment]
The python Part is silent on this issue (Violations of the Liskov substitution principle)right now. Valid responses are:

- This vulnerability is not applicable to Python because (explain). 
   I believe that all OO languages have this vulnerability, so this choice is almost certainly void.
- Python exhibits the behaviour as described in TR 24772-1 clause 6.42. The avoidance mechanisms of TR 24772-1 clause 6.42.5 are applicable to Python.
- Python mitigates the vulnerability by (explain)
Thank you in advance.

**Comment by gvanrossum** [comment]
Since you're in the typing tracker I should mention that the mypy checker
does mitigate this by flagging Liskov violations as errors. I don't have
the time to carefully read your legalese and respond in kind, sorry.

**Comment by ilevkivskyi** [comment]
Yes, I think the third bullet
> Python mitigates the vulnerability by ...

is applicable here, [mypy type checker](https://github.com/python/mypy) detects and prohibits Liskov violations with very few exceptions (like incompatible ``__init__`` method signatures). So I guess the last bullet in 6.42.5:
> Use static analysis tools that identify misuse of inheritance in the contract model.

is applicable.

**Comment by markshannon** [comment]
@stephenmichell49 Could you fill in some background information, please.

Who is the target audience of ISO/IEC NP TR 24772-1?
Why use the term "vulnerability"? In software, "vulnerability" is usually taken to mean vulnerability to malicious action and is already covered very well by Mitre (https://cwe.mitre.org) and owasp (https://www.owasp.org).

Why is the ISO producing this document? I would have thought an organisation like IEEE would be better placed to produce such an engineering guide.

I also note:
```
6.42.6 Implications for language design and evolution
In future language design and evolution activities, the following items should be considered:
Provide language mechanisms to formally specify preconditions and postconditions.
```
This sounds like an opinion piece. It doesn't belong in a standards document.

**Comment by stephenmichell49** [comment]
Thank you folks, that is quite helpful. 
For this section, I have drafted the following:
6.42 Violations of the Liskov Substitution  Principle or the Contract Model  [BLP]
Python is subject to violations of the Liskov substitution rule as documented in TR 24772-1 clause 6.42. The Python community provides static analysis tools for Python, such as “mypy” which detect a large class of such violations.
6.42.1 Applicability to language
Follow the guidelines of TR 24772-1 clause 6.42.5. In particular, use static analysis tools such as “mypy” to detect such violations.
This will be reviewed by the committee at our November meeting.

In reply to Mark, ISO/IEC/JTC 1/SC 22/WG 23 Programming Language Vulnerabilities has been doing this work since 2006. We published ISO IEC TR 24772 first in 2010 and revised it in 2013. Our approach to documenting programming language vulnerabilities is well accepted by the international community. 

I will close this thread after a couple of days, in case there is more comment.
Thank you. You have been quite helpful.

**Comment by gvanrossum** [comment]
You haven't answered the question about audience. I don't know anyone who
would attempt to becomes a better programmer by reading such a document. So
who does? Who is this "international community"?

**Comment by stephenmichell49** [comment]
The audience is intended to be the senior developers/team leads, etc. that create project-specific coding standards. The document has a plethora of recommendations, and developers need to look at how the programmed system integrates into larger systems, risks, threat levels, attack vectors, etc. and decide for the project what is appropriate in that context. I would certainly hope that the senior developers read such documents before setting pen to paper, or fingers to keyboard, to create the coding standards. 

The international community is all of the ISO and IEC national bodies of JTC 1, our parent's parent. Our immediate parent is JTC 1 subcommittee 22 Programming Languages. All international standards, technical specifications and technical reports are approved by the ISO IEC National Bodies in formal ballots.
