### ISSUE TITLE
Non-`@runtime` protocols cannot be used in a `typing.Union`

### ISSUE THREAD

**Issue by erikwright** [python/typing#488]
Code such as the following:

```python
In [1]: import typing

In [2]: import typing_extensions

In [3]: class P(typing_extensions.Protocol):
   ...:     def f(self, s: str) -> str: ...
   ...:     

In [4]: p_or_callable = typing.Union[P, typing.Callable]
```

Leads to the following exception:

```python
../../../../.pyenv/versions/3.6.2/lib/python3.6/typing.py:682: in inner
    return func(*args, **kwds)
../../../../.pyenv/versions/3.6.2/lib/python3.6/typing.py:803: in __getitem__
    return self.__class__(parameters, origin=self, _root=True)
../../../../.pyenv/versions/3.6.2/lib/python3.6/typing.py:743: in __new__
    parameters = _remove_dups_flatten(parameters)
../../../../.pyenv/versions/3.6.2/lib/python3.6/typing.py:647: in _remove_dups_flatten
    for t2 in all_params - {t1}
../../../../.pyenv/versions/3.6.2/lib/python3.6/typing.py:649: in <genexpr>
    t2.__origin__ is not None)):
../../../../.pyenv/virtualenvs/crucible/3.6.2/lib/python3.6/site-packages/typing_extensions.py:833: in __subclasscheck__
    raise TypeError("Instance and class checks can only be used with"
E   TypeError: Instance and class checks can only be used with @runtime protocols
```

Decorating the `Protocol` subclass with `@runtime` works around the problem.

cc @ilevkivskyi

**Comment by ilevkivskyi** [comment]
At first glance there are two ways to fix this: using a ``sys._getframe`` hack in ``typing_extensions`` (quick fix), or directly in ``typing`` (more long term fix, will be effective only for newer ``typing`` versions). I tend to do something closer to the first option. Later, when ``Protocol`` will be in ``typing``, we can apply a clean long-term fix.

**Comment by ilevkivskyi** [comment]
After some thinking it seems to me that we should apply _both_ fixes:
* have a ``sys._getframe`` hack to be sure that ``typing_extensions`` will work with older versions of ``typing`` (some people simply can't upgrade yet).
* Remove the code in ``typing`` that simplifies unions. Currently, ``Union[B, C]`` returns just ``C`` if it is a subclass of ``B``, but this code is fragile and should be probably left for type checkers.

@gvanrossum If you agree, then I will make a PR with the corresponding changes.

**Comment by gvanrossum** [comment]
I'm always wary of `sys._getframe` hacks (that underscore means "danger") but given the recent trends I'm all for doing less, so not simplifying `Union`s sounds like a good idea. Even `Union[A, A]` can stay like that, and so can `Union[A, Union[B, C]]`.

**Comment by msullivan** [comment]
As of typing 3.7.4, this has returned:
```
from typing import Protocol, Union

class A(Protocol): pass
class B(Protocol): pass

C = Union[A, B]
```
fails with `TypeError: Instance and class checks can only be used with @runtime_checkable protocols`

**Comment by ilevkivskyi** [comment]
OMG, check indentation here https://github.com/python/typing/blob/master/python2/test_typing.py#L991 Test that is not a test :-)

**Comment by ilevkivskyi** [comment]
It looks like this is only a problem with the backport, Python 3.8 works correctly (also the test there has correct indentation).
