### ISSUE TITLE
When was be added module type_extensions?

### ISSUE THREAD

**Issue by lk-geimfari** [python/typing#489]
I mean version of Python interpreter. I have found information that it was be added in Python 3.5. Is it true? 
If it's true, then which is micro version of Python 3.5? 

I ask, because i want to use `Protocol`, but i have not this module in my Python 3.5.2 which is default on Ubuntu 16.04.

![](https://i.imgur.com/GXklYQB.png)

**Comment by Michael0x2a** [comment]
I'm not quite sure what you're asking, but the `typing_extensions` is currently [available on PyPi](https://pypi.python.org/pypi/typing-extensions/3.6.2.1) as a 3rd party library (so, just run `pip install typing_extensions`).

Here is a [full list of all the backported types](https://github.com/python/typing/tree/master/typing_extensions) and related details.

The `Protocol` type in particular has been backported to all Python versions *except* specifically 3.5.0. (So, you can use Protocol in Python 3.4.x, or in 3.5.1+).

**Comment by lk-geimfari** [comment]
@Michael0x2a I thought that this module is included in the standard Python library. Sorry.

**Comment by ilevkivskyi** [comment]
``Protocol`` and ``runtime`` are planned to be added to ``typing`` in Python 3.7beta1 (in few months). Currently you indeed to manually ``pip install typing_extensions``.

**Comment by vlasovskikh** [comment]
@lk-geimfari BTW https://youtrack.jetbrains.com/issue/PY-26628.
