### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by chantisnake** [python/typing#491]
Here is my code:
```python
    # add sub-lists(segment) to final list
    segments_of_text_list = _cut_with_overlap(input_list=text_list,
                                              norm_seg_size=seg_size,
                                              overlap=overlap,
                                              last_prop=last_prop)

    # join characters in each sublist
    segment_list = _join_sublist_string(input_list=segments_of_text_list)

    return segment_list
```
```python
def _join_sublist_string(input_list: List[List[str]]) -> List[str]: ...
```
```python
def _cut_with_overlap(input_list: List[T], norm_seg_size: int, overlap: int,
                      last_prop: float) -> List[List[T]]: ...
```
I got an error message on the second line of the first code snippet: `segment_list = _join_sublist_string(input_list=segments_of_text_list)`.
The message is ` Incompatible types in assignment (expression has type List[str], variable has type List[List[Any]])`

I really don't know what the `expression` and `variable` in this error message is referred to. 

Can you guys help?
Thanks!

**Comment by gvanrossum** [comment]
What's the heading of the function in which the error occurs? And is there another assignment to `segment_list`?

**Comment by JelleZijlstra** [comment]
This probably means you previously initialized `segment_list` as a `List[List[str]]` (in code you didn't share here).

**Comment by chantisnake** [comment]
Oh! That solves it. Thanks.

I used the same variable twice
