### ISSUE TITLE
easier syntex for union

### ISSUE THREAD

**Issue by chantisnake** [python/typing#497]
in many other languages, the union type is expressed like `Type1 | Type2` or `Type1 | Type2`

since `Union` is used a lot, can we make a easier syntax for it?

maybe `Type1 or Type2`?

**Comment by gvanrossum** [comment]
This was debated at length when PEP 484 was first proposed.

**Comment by chantisnake** [comment]
Is it possible that you can point me to the place where this debate happens? I am very interested to know the reason for current union syntax.
