### ISSUE TITLE
Inspect typehint in the runtime

### ISSUE THREAD

**Issue by bagrat** [python/typing#499]
I would like to inspect typehints (class variables, function arguments) in the runtime, in order to collect some metadata. I was not able to find any documentation how to do that, so started to dig into the `typing` classes in the REPL. So far, what I was able to accomplish is the following, but I would like to check whether it is a safe and reliable way.

So for example, I want to detect if the typehint is a `List[something]`, I do:

```
is_list = issubclass(typehint, List)

if is_list:
    item_typehint = typehint.__args__[0]
```

**Comment by bagrat** [comment]
Looking at the [typeguard code](https://github.com/agronholm/typeguard/blob/master/typeguard.py#L369-L374) though now I see that they make use of the `__origin__`. Is it the correct way?

**Comment by JelleZijlstra** [comment]
You would probably be interested in the https://github.com/ilevkivskyi/typing_inspect project. In general, `typing` itself doesn't aim to provide runtime introspection support.

**Comment by bagrat** [comment]
Ideally I would avoid additional dependencies, but looks like they also use the same approach. Thanks @JelleZijlstra

**Comment by ilevkivskyi** [comment]
Eventually, some helpers from ``typing_inspect`` may be moved to ``typing``. We already have a b.p.o issue for this, so I don't think we need to keep this one open.

**Comment by bagrat** [comment]
That's great news @ilevkivskyi, thanks for the update!
