### ISSUE TITLE
Missing call to super?

### ISSUE THREAD

**Issue by danpascu** [python/typing#500]
https://github.com/python/typing/blob/98db8a423486f471d0520392b445875d59a8d84b/src/typing.py#L140

Why is `__init__` of this metaclass not calling `super().__init__`?

This resulted in failure when defining a class that inherited both Generic[Type] and some other class that has its own metaclass (let's call it MyMeta). In order to make the multiple inheritance possible I had to define a new metaclass that is a subclass of all the metaclasses of all the bases. When defining this new metaclass, if I place MyMeta after GenericMeta (like below), `MyMeta.__init__` is never called.

`class CompositeMeta(GenericMeta, MyMeta):
    pass
`

**Comment by gvanrossum** [comment]
Does the obvious work-around (putting `GenericMeta` last) not work for you?

**Comment by danpascu** [comment]
As of right now, no. That was my initial attempt, but the metaclass in question complained about the extra arguments to __init__, so I hoped that by placing it last, GenericMeta would take out its extra arguments and call super with just the standard (name, bases, namespace). This is when I ran into the problem I mentioned (that metaclass is not part of the code I'm writing, so modifying it to accept extra arguments wasn't my first choice).

The reason why I opened the issue was because I noticed what I thought was an oversight/mistake and thought there would be interest in fixing it so it works without workarounds. Is there a reason I'm missing why GenericMeta.__init__ is not calling super? (your answer kinda suggests that is the case and you wish to preserve the current behavior)

**Comment by gvanrossum** [comment]
Yeah, I think it's foolish to expect (meta)classes that aren't part of the
same framework to be capable of working together using cooperative
inheritance. E.g. who says that GenericMeta.__init__ should remove any
arguments from *args/**kwds?

**Comment by danpascu** [comment]
So no answer about what the reason is for not calling `super.__init__`? I'm really curious about the motivation for deliberately doing it like this.

**Comment by gvanrossum** [comment]
Maybe next year I'll have time to explain.

**Comment by danpascu** [comment]
I do not think the resolution to this issue is satisfactory. Having two core components of the language (typing and metaclasses) at odds with each other is not a good thing. Suggesting a workaround to deal with the issue is not enough. Workarounds are error prone and break easily with future code changes, they are at most a short term solution.

Having GenericMeta not call `super.__init__` breaks the expectation that all metaclasses will be properly initialized. If that cannot be changed for whatever technical reason, then it needs to be properly documented and explained so people can be aware of what the issue is and make a decision about the proper way to deal with it. This is only made worse by the fact that multiple inheritance is required for the metaclass in a case like this, there is no way around it.

Typing loses it usefulness if it cannot be consistently applied throughout the code because it breaks or is problematic to define in non-trivial cases. Right now if I try to use typing by defining types that inherit Generic[T], I'm immediately at odds with any class that has a metaclass.

**Comment by gvanrossum** [comment]
Why don't you propose a PR, including a unit test, covering both Python 2
and Python 3? That's much more productive than continuing to argue.

**Comment by danpascu** [comment]
I would, but apparently I have to wait a year to get some insight into the matter.

**Comment by ilevkivskyi** [comment]
@danpascu This may be relevant only to the backported version, since PEP 560 is likely to be accepted for Python 3.7.

**Comment by danpascu** [comment]
That is good to know. I was not aware of PEP 560, thanks for the heads up. Indeed, with that it will only be relevant for the backported version.

P.S. I noticed the metaclass conflict section in PEP 560 talks about mixing-in GenericMeta, but the order in the example (with GenericMeta first and LibraryMeta second), is exactly the form that doesn't work.

**Comment by gvanrossum** [comment]
> P.S. I noticed the metaclass conflict section in PEP 560 talks about mixing-in GenericMeta, but the order in the example (with GenericMeta first and LibraryMeta second), is exactly the form that doesn't work.

Then this provides a backwards compatibility reason not to change this behavior: in order to make this work one would have to write something like this:
```py
class MergedMeta(GenericMeta, LibraryMeta):
  def __init__(self):
    GenericMeta.__init__(self)
    LibraryMeta.__init__(self)
```
(In the olden days, before `super`, this is really how multiple inheritance had to be done!) If we were to change `GenericMeta.__init__()` to call `super().__init__()`, `LibraryMeta.__init__()` would be called twice.

I presume one reason that this hasn't come up more is that it's quite possible to write a metaclass without `__init__()`. If you do all the work in `__new__()` the issue never comes up (since that *does* call `super().__new__()`).
