### ISSUE TITLE
GenericMeta conflicts with __init_subclass__

### ISSUE THREAD

**Issue by Kentzo** [python/typing#506]
https://bugs.python.org/issue32162

When superclass inherits from Generic, attributes set for a subclass are incorrectly propagated to its superclass.

Without Generic attribute access raises an exception:

```python
    class X:
        def __init_subclass__(cls, **kwargs):
            super().__init_subclass__(**kwargs)
            cls.attr = 42

    class Y(X):
        pass

    Y.attr  # 42
    X.attr  # AttributeError
```

With Generic it does not:

```python
    import typing

    T = typing.TypeVar('T')

    class X(typing.Generic[T]):
        def __init_subclass__(cls, **kwargs):
            super().__init_subclass__(**kwargs)
            cls.attr = 42

    class Y(X):
        pass

    Y.attr  # 42
    X.attr  # 42
```

**Comment by Kentzo** [comment]
Looks like `cls._grog` is not yet set properly by the time `__init_subclass__` is called. As a result`Generic.__setattr__` will modify wrong class.

**Comment by ilevkivskyi** [comment]
In 3.7 this should be fixed by PEP 560. But for Python 3.6 the fix could be put in 3.6.4, so this is quite urgent (rc1 is in less than a week) so I will try to do this today.

**Comment by Kentzo** [comment]
@ilevkivskyi Could you leave a comment regarding the fix I use now? How unsafe is it?

**Comment by ilevkivskyi** [comment]
Setting ``_gorg`` manually is not future proof, since ``_gorg`` is an internal API and will be removed soon. But on the other hand this is not necessary now with #507 merged (you only need to take care that ``X[int]`` is an actual subclass of ``X`` in all versions before 3.7).

**Comment by GreatFruit-Bot-Andy** [comment]
@ilevkivskyi In my case I might have a hierarchy that passes generic parameters:

```python
T = typing.TypeVar(...)

class Y(X[T]):
    pass

class Z(Y[T]):
   pass
```

and each subclass may override `__init_subclass__` and try to set same attributes. How well #507 will work in this case?

**Comment by Kentzo** [comment]
@ilevkivskyi In my case I might have a hierarchy that passes generic parameters:

```python
T = typing.TypeVar(...)

class Y(X[T]):
    pass

class Z(Y[T]):
   pass
```

and each subclass may override `__init_subclass__` and try to set same attributes. How well #507 will work in this case?

**Comment by ilevkivskyi** [comment]
> How well #507 will work in this case?

The easiest way to is just to test it, you can just install from git master (somehow my understanding was that you already tried it).
