### ISSUE TITLE
get_type_hints() always raises on forward references

### ISSUE THREAD

**Issue by ilevkivskyi** [python/typing#508]
https://github.com/ericvsmith/dataclasses/issues/92#issuecomment-348829024 raised an important question (this existing problem is also mentioned in PEP 563). Currently, ``get_type_hints`` will raise a ``NameError`` in situations where it might not be the desired behaviour (e.g. if used by a class decorator). For example:
```python
def modify(cls):
    types = get_type_hints(cls)
    # do something with 'cls' and 'types'
    return cls

@modify
class C:
    linked: 'C'
```
It looks like it will be useful to have an option to keep forward references that are currently undefined. For example:
```python
class C:
    x: 'ClassVar[B]'

assert get_type_hints(C, allow_forward=True) == {'x': ClassVar['B']}

class B:
    ...

assert get_type_hints(C, allow_forward=True) == {'x': ClassVar[B]}
```

**Comment by gvanrossum** [comment]
If it's easy to fix, go ahead!

**Comment by djrochford** [comment]
I take it this was *not* easy to fix? I, for one, would be very glad to see this fixed, but I gather that's unlikely to happen soon...

**Comment by ilevkivskyi** [comment]
This is not easy, but not too hard either. I just didn't have time for this, sorry.

**Comment by djrochford** [comment]
Oh, no need to apologise! I commented only in the hope of bumping this slightly higher the priority list, but I'll survive, and life is short.

**Comment by 5t4cktr4c3** [comment]
Is there any chance to get this fixed in the near future?

**Comment by 5t4cktr4c3** [comment]
You can temporarily fix this issue by passing a dict as parameter with the needed classes to the function.

**Comment by The-Compiler** [comment]
A somewhat related Python bug I've opened about this a couple of weeks ago (before finding this issue): [Issue 43463: typing.get_type_hints with TYPE_CHECKING imports / getting hints for single argument - Python tracker](https://bugs.python.org/issue43463)

**Comment by srittau** [comment]
Please report this bug to bugs.python.org if it still exists.
