### ISSUE TITLE
Do we need SupportsIndex?

### ISSUE THREAD

**Issue by ilevkivskyi** [python/typing#515]
We only provide ``SupportsInt``, but it recently appeared on python-dev, that there are certain situations where ``__index__`` is more preferred than ``__int__``. Do we also need to provide ``SupportsIndex``?

**Comment by shoyer** [comment]
I suppose it depends on the status of PEP 544, which I think would subsume this use case. In practice, typing is not yet supported by NumPy, so the most widely used types implementing a `__index__` method are not going to be checked either way.

**Comment by gvanrossum** [comment]
Remind me how PEP 544 would remove the need? How would you declare a
function that takes an argument that supports `__index__`? You can't inline
protocol definitions.

**Comment by shoyer** [comment]
That was too strong. It just makes it easy to write `SupportsIndex`, even outside the `typing` module:
```python
class SupportsIndex(Protocol):
    def __index__(self) -> int: ...
```

Arguably this protocol is simple enough (like the `SupportsClose` example from PEP 544) that it isn't worth including in `typing`.

I would certainly use `SupportsIndex` when typing numeric code, but I would be about as happy rewriting it myself as to import it from typing.

**Comment by gvanrossum** [comment]
Yeah, the same is true for the other SupportsXXX protocols. Maybe we should just deprecate those and take the stance that we're not adding any new ones.

**Comment by JukkaL** [comment]
I'd be happy to stop adding new SupportsXXX protocols to `typing`. I doubt they would be widely useful, and they could unnecessarily complicate the API and cause incompatibility issues between different `typing` versions. 

If a stub needs to use a protocol not currently defined in `typing` for something like `__index__`, it can just define a private protocol in the stub (name prefixed with `_`).

**Comment by ilevkivskyi** [comment]
> Yeah, the same is true for the other SupportsXXX protocols. Maybe we should just deprecate those and take the stance that we're not adding any new ones.

Some of those are used by ``builtins.pyi``, IIRC ``int()`` takes ``SupportsInt``. I think we can close this issue at least. We can open another one if deprecation of existing ones is desirable.
