### ISSUE TITLE
Accessing type arguments inside __init__

### ISSUE THREAD

**Issue by mitar** [python/typing#519]
It seems this is not possible?

Example:

```python
import typing

T = typing.TypeVar('T')

class Foo(typing.Generic[T]):
    def __init__(self):
        print(type(self).__args__)

A = Foo[int]
A()
```

I would expect that this prints out `int` as `__args__`, but it does not. It seems because runtime class is `Foo`, not `Foo[int]`.

**Comment by ilevkivskyi** [comment]
> It seems because runtime class is ``Foo``, not ``Foo[int]``.

Yes, and this is intentional. The original class is stored in ``__orig_class__`` this is however not an official API. Or you can better use ``typing_inspect.get_generic_type(obj)`` which is a thin wrapper around this API.

**Comment by mitar** [comment]
Oh, thank you for quick response.
