### ISSUE TITLE
Allow specifying type arguments which cannot be inferred

### ISSUE THREAD

**Issue by rgabbard** [python/typing#521]
Is there a way to specify at a function's call-site a type which cannot be inferred? For example, in Java, if a static method of a class has a type variable which does not appear as the type of an argument (e.g. `static <T> MyClass.Builder<T> builder()`) you can specify it like this `MyClass.<Foo>builder())`.

**Comment by ilevkivskyi** [comment]
Could you please add some more details and example code? Do you want something like this?
```python
T = TypeVar('T')

def fun(x: T, y: T) -> T:
    ...

fun[float](1, 2)
```

Such syntax currently does not work for functions, only for classes. Allowing this would require changes to core Python. Alternatively, we can add a special function (identity function at runtime), for example:
```python
bind(fun, T=float)(1, 2)
```
or
```python
bind(fun, [float])(1, 2)
```

**Comment by rgabbard** [comment]
@ilevkivskyi : Here is the case which motivated me to ask:

```
class MyGenericClass(Generic[T]):
   @staticmethod
   def builder(self) -> 'MyGenericClass.Builder[T]':
      return MyGenericClass.Builder[T]

    ...
    class Builder(Generic[T2]):
         def add(self: SelfType, item: T2) -> SelfType:
              ...
              return self
     
        def build(self) -> MyGenericClass[T2]:
             ...
            return MyGenericClass(....)

# mypy/PyCharm know that foo is `MyGenericClass` but don't know
# the type variable binding for it
foo = MyGenericClass.builder().add(...).build()
```

I was interested in some way to hint that the call to `MyGenericClass.builder()` should return `MyGenericClass.Builder[X]` for some specified `X`.

**Comment by gvanrossum** [comment]
That example can be solved by removing `T` from the static method and breaking up the builder instantiation at the end, e.g.:
```py
b: MyGenericClass.Builder[int] = MyGenericClass.builder()
foo = b.add(12).build()
```
Perhaps OT, you seem to be trying to write Java in Python. Things will go better if you adopt a more Pythonic API.

**Comment by ilevkivskyi** [comment]
@rgabbard 
Note that static methods should not use type variables of the generic class, since type variables only apply to _instances_, not to classes. (I think we already have an issue to e4xplicitely prohibit using bound type variables in static methods,)

**Comment by rgabbard** [comment]
@ilevkivskyi : thanks for catching the typo; I have corrected the example above (or perhaps better to say pseudo-example of what my desired behavior would be).

@gvanrossum : Closing this issue as "the suggested use case isn't very Pythonic and introducing an intermediate variable is a good enough solution" is fine.
