### ISSUE TITLE
Wrappers for generic types

### ISSUE THREAD

**Issue by mitar** [python/typing#522]
I am trying to define a wrapper for a generic type:

```python
import typing

T = typing.TypeVar('T')

class List(typing.List[T]):
    pass

class ImmutableList(List):
    def __init__(self, mutable_list) -> None:
        pass
```

So the idea is that you can pass a mutable list to `ImmutableList` constructor and you would get an instance of `ImmutableList` sharing all elements of the mutable list, but one could not change them.

The question is how to define types here. How to make it so that it is clear that elements of `ImmutableList` instance are the same as `mutable_list` argument had as type of elements.

**Comment by dmoisset** [comment]
This can be done with mypy, you should define both `List` and `ImmutableList` as `Generic[T]`. Then you can define `mutable_list: List[T]` and you'll get an `ImmutableList[int]` if you pass a `List[int]` to the constructor, and an `ImmutableList[Foo]` if you pass a `List[Foo]`

**Comment by mitar** [comment]
Hm, I would not have to provide `int` to the class definition? Isn't what you are saying equivalent to:

```python
import typing

T = typing.TypeVar('T')

class List(typing.List[T]):
    pass

class ImmutableList(List[T]):
    def __init__(self, mutable_list: List[T]) -> None:
        pass
```

Both `List` and `ImmutableList` implicitly inherit from `Generic[T]`, no? But it is not true that if I do `ImmutableList(mutable_list=List[int](1, 2, 3))`, type of elements of `ImmutableList` is `Any`, not `int`, no?

**Comment by ilevkivskyi** [comment]
This is a question about using types, not about runtime behavior of the `typing` module, so closing it. (Btw, I am happy with the answer provided.)
