### ISSUE TITLE
How it can be determined that variable is an Union?

### ISSUE THREAD

**Issue by Pitometsu** [python/typing#528]
```python
>>> v = Union[int, str]
>>> type(v)
typing.Union
>>> type(v) == Union
False
>>> v is Union
False
>>> issubclass(v, Union)
*** TypeError: Unions cannot be used with issubclass().
>>> isinstance(v, Union)
*** TypeError: Unions cannot be used with isinstance().
```

**Comment by dmoisset** [comment]
There's no official/documented way, although `type(v) is type(Union)` will work with the current implementation.

**Comment by Pitometsu** [comment]
Oh, thank you, @dmoisset, that's a nice workaround (better than mine)!
Keep issue open in case maintainers would implement a documented way.

**Comment by ilevkivskyi** [comment]
The "official" way is to use ``typing_inspect`` package on PyPI. I am maintaining it, so that ``is_union_type`` should always work. If not, you can file a bug here https://github.com/ilevkivskyi/typing_inspect

**Comment by Pitometsu** [comment]
@ilevkivskyi thank you!
