### ISSUE TITLE
Compare two stub files to detect interface changes?

### ISSUE THREAD

**Issue by henryJack** [python/typing#531]
Hi,

I'm looking to create a tool to compare interface differences between the public parts of a module in its current state vs a previously released state. With this tool, it should be possible to determine whether or not you've made a breaking change, added a feature or just made a bug fix (i.e no interface changes) to the module with respect to a previous version of it.

My thinking for this was to generate the stubs for the OLD version of a module and a NEW version of the module and compare these to identify differences in the public interface. This feels good because I can just use [stubgen](https://github.com/python/mypy/blob/master/mypy/stubgen.py) for this...

The next step in this process would be to compare the functions and classes in the NEW and OLD version of the module. However, the usual way to [inspect.getmembers](https://docs.python.org/3.5/library/inspect.html#inspect.getmembers) and [inspect.signature](https://docs.python.org/3/library/inspect.html#inspect.signature) do not work as the functions and classes in the stubs are `.pyi` files and not `.py` files. 

Do you have any ideas what would be the best way to compare stub files? The most useful similar tool i've found is a feature of googles [pytype](https://github.com/google/pytype):

pytype has an option to test a .pyi file against the .py implementation:

`pytype --check file.py:file.pyi`

It won't do everything, but it will find:

- Methods,classes or constants declared in the .pyi, but missing in the .py.
- Argument types in the .pyi that cause type errors in the .py.
- Methods returning values incompatible with what is declared in the .pyi.

However, this doesn't compare 2 `.pyi` files and you need python 2.7 to run it...

Do you have any ideas what would be the best way to compare stub files?

**Comment by gvanrossum** [comment]
Maybe you could add a flag to stubgen to spit out JSON instead of a .pyi file, so you can write a tool that compares two such JSON files?

**Comment by henryJack** [comment]
Hmm, I think perhaps (after digging around in the mypy source code) I could make use of the `compare_symbol_table_snapshots` function in the [astdiff.py](https://github.com/python/mypy/blob/master/mypy/server/astdiff.py#L193) file

**Comment by henryJack** [comment]
Then all I need to do is walk through all the modules and nested modules in a package to generate a module tree to check if anything has been added (possibly only a Minor change) or removed (definitely a breaking/major change). Then I can find if anything has been added, removed, changed to the module interfaces by generating [snapshot_symbol_tables](https://github.com/python/mypy/blob/master/mypy/test/testdiff.py#L40) as shown in this test script...

**Comment by henryJack** [comment]
Perhaps @JukkaL or @ilevkivskyi could weigh in on whether that would be a good route to pursue?

**Comment by JukkaL** [comment]
`compare_symbol_table_snapshots` is worth looking at, though it doesn't distinguish between modifications, additions and deletions. You could look up changed names using symbol tables to see if there is a deletion. Also, it will flag the addition of additional optional arguments to a function which you'd probably consider a minor change.

**Comment by henryJack** [comment]
@JukkaL - The docstring for the "snap shot symbol table" (type: Dict[str, SnapshotItem]) states "The snapshot has a representation based on nested tuples and dicts that makes it easy and fast to find differences.". So, that's a good place to start. `compare_symbol_table_snapshots` just gives us the names of the keys which have changed which is also a good starting point, but Ideally, it would give us a more verbose output of diffs which could then be used to better determine the types of changes (or, for example, to make automatic change logs for basic changes)

I'm having trouble working out how you initialise and populate `SymbolTable` class (which extends `Dict[str, SymbolTableNode]`). The only place in the tests which actually seems to use this is:

```
snapshot1 = snapshot_symbol_table(prefix, files1['__main__'].names)
snapshot2 = snapshot_symbol_table(prefix, files2['__main__'].names)
```
We know `files1['__main__'].names` must be of type 'SymbolTable'. and `files1` is of type `MypyFile`. But I have no idea what getting ['__main__'] on a `MypyFile` object should do. Would happily add a break point whilst a test is running but the unit tests don't seem to be hitting that part of the code :(

**Comment by henryJack** [comment]
Also, out of interest, why did you implement your own testing framework?

**Comment by JukkaL** [comment]
To actually use `snapshot_symbol_table` you'll need to use internal mypy APIs, such as `mypy.build.build`. Then you can find the symbol table through a `MypyFile` object (accessible via `BuildResult.files`). Note that these APIs are undocumented and subject to change at any time -- you are mostly on your own. You can ask specific questions on Gitter (this is getting off-topic for this issue tracker).

> Also, out of interest, why did you implement your own testing framework?

It's a long story. Mypy was originally a new language and couldn't access the Python stdlib, so I couldn't just use pytest or unittest.

**Comment by henryJack** [comment]
I use as much from Mypy as possible to begin with (don't want to write a load of the ast and [types ast](https://github.com/python/typed_ast) stuff myself)

**Comment by henryJack** [comment]
If that's True, then we can create a flattened and fully qualified representation for every module (recursively) in a package. e.g. 

```python
class FlatMypyTree(Dict[str, MypyFile]):
    """
    Dict value is a MypyFile -> The abstract syntax tree of a single source file.
    Dict key is the fully qualified name for the source file with respect to package root
    """
    def __init__(self, directory: str):
        super().__init__()
        # then populate dictionary! i.e. self["package.subpackage.module_a"] = MypyFile(...)
        pass
```

Getting the diffs and whatnot is then easy...

```python
def get_tree_key_diffs(a: FlatMypyTree, b: FlatMypyTree) -> Tuple[Set[str], Set[str], Set[str]]:

    a_keys: Set[str] = set(a.keys())
    b_keys: Set[str] = set((b.keys()))
    keys_added_to_b: Set[str] = b_keys - a_keys  # i.e. in b but not in a
    keys_removed_from_a: Set[str] = a_keys - b_keys  # i.e in a but not in b
    common_keys: Set[str] = a_keys & b_keys  # i.e. keys in both a and b

    return keys_added_to_b, keys_removed_from_a, common_keys
```

This is already pretty handy, because if we have non-empty been `keys_removed_from_a`, we know there are some breaking changes. For all other cases, we just need to concern ourselves with `common_keys`. (Note: `keys_added_to_b` is useful for a change log so why not keep it?)

We can can then do the exact same thing but for comparing like for like `MypyFile`'s...

```python
def get_interface_diffs(common_keys: Set[str], a: FlatMypyTree, b: FlatMypyTree):
    for key in common_keys:
        mypy_file_a: MypyFile = a[key]
        mypy_file_b: MypyFile = b[key]
        diffs = get_mypyfile_diffs(mypyfile_a=mypy_file_a, mypyfile_b=mypy_file_b)
```

The question is, what the heck does `get_mypyfile_diffs` look like? What would be useful output? How do we currently compare normal AST trees? What even is the purpose of the `MypyFile` vs `SymbolTree`? Why does the `MypyFile` extend `Node`?

**Comment by henryJack** [comment]
Actually, ignore that last spasm, I think I've worked it out...
