### ISSUE TITLE
typing release 3.6.4

### ISSUE THREAD

**Issue by gvanrossum** [python/typing#532]
I'm going to release typing version 3.6.4.

This is going to match what's in the CPython repo tagged with "v3.6.4" except for some immaterial details in test_typing.py:
- A change to the argument name for `magic_decorator()` (from https://github.com/python/cpython/commit/205dd4e14de77f9c8ed2903ddebbcf9968bbb6a9); this seems immaterial
- A bunch of places have `collections_abc.SomeClass` here but still have `collections.SomeClass` in CPython branch 3.6; here the typing repo is better, the changes were committed in https://github.com/python/typing/commit/d9e477ede48f5ec5f50213f0d9db6c7d92cc3287, which claims they came from the CPython repo, resumably they weren't backported there (and there's no reason to)

**Comment by gvanrossum** [comment]
It also seems we've skipped releasing 3.6.2 and 3.6.3. That's fine, we'll go straight to 3.6.4. (But I wonder why we skipped those, esp. given #453, which bumped the version in setup.py to 3.6.2 but apparently was never released.)

**Comment by ilevkivskyi** [comment]
3.6.2 was released in August https://pypi.org/project/typing/ we skipped only 3.6.3 I think.

**Comment by gvanrossum** [comment]
Ah, 3.6.2 was not tagged. I'll see if I can reconstruct the tag.

**Comment by gvanrossum** [comment]
It is done. On PyPI: https://pypi.python.org/pypi/typing/3.6.4.

Also see https://github.com/python/typing/releases on GitHub (which is just the tagged versions).

**Comment by gvanrossum** [comment]
Whoops, this broke Travis-CI.

**Comment by gvanrossum** [comment]
@ilevkivskyi Can you help me with the Travis-CI failures? E.g.
https://travis-ci.org/python/typing/jobs/333066899

It seems Python 3.7 and nightly don't define `GenericMeta`? And this causes `test_typing_extensions.py` to fail. There are no failures for 3.6 or earlier so I presume this is due to something that changed in 3.7 recently, presumably one of your improvements?

**Comment by ilevkivskyi** [comment]
The build fails because of PEP 560. `typing_extensions` (or rather just the tests, since PEP 560 doesn't touch much of public interface) should be updated. I can do this tomorrow morning.

**Comment by gvanrossum** [comment]
It's disturbing though. I think there may be quite a few people who are expecting `GenericMeta` to exist, even though it was never documented. (These aren't users of `typing_extensions`, just people who had a metaclass conflict and solved it by importing `GenericMeta`.)

Anyway I'll open a new issue for that.
