### ISSUE TITLE
Fix typing_extensions for PEP 560 and release a new version

### ISSUE THREAD

**Issue by gvanrossum** [python/typing#533]
See https://github.com/python/typing/issues/532#issuecomment-360328654 and those around it -- the typing Travis-CI build is currently broken due to this.

**Comment by ilevkivskyi** [comment]
After https://github.com/python/typing/pull/549 is merged we can release a new version that supports Python 3.7 and PEP 560.

**Comment by ilevkivskyi** [comment]
The new version is released and I tested it works correctly on 2.7, 3.6, and 3.7.
