### ISSUE TITLE
Missing SupportsStr

### ISSUE THREAD

**Issue by OJFord** [python/typing#540]
Is the lack of a `SupportsStr` protocol just an oversight, or due to some technical limitation?

**Comment by gvanrossum** [comment]
Given that every object supports `str()`, what use would you make of it?

**Comment by OJFord** [comment]
Many thanks for your reply.

My apologies, I'd thought that it was the solution to a problem with:
```python
var = (
    'str',
    'string',
) + tuple_of_ints + #...
```

and that I could solve it by stating `var: Tuple[SupportsStr, ...]` so that the mixed types added on were somehow 'expected.

When defining my own `SupportsStr` didn't work, I instead used:
```python
var = (
    'str',
    'string',
    *tuple_of_ints,
    #* ...
)
```
which is a style I personally much prefer anyway.

I'd never really realised that every object supports `str()`, despite of course never encountering a counter-example, (or, apparently, thinking too hard about it...) so thanks for that!
