### ISSUE TITLE
divmod does not support overloaded arithmetic (e.g., with __divmod__)

### ISSUE THREAD

**Issue by shoyer** [python/typing#541]
It is only defined on int and float:
https://github.com/python/typeshed/blob/50c71883000f14ae0bfe622906d3fc4ba1e29875/stdlib/3/builtins.pyi#L804-L805

This came up in typing NumPy, which also supports `divmod()` on numpy arrays.

I doubt it's really worth adding a `SupportsDivmod` class to typing, so let's save this until we have support for custom protocols?

**Comment by gvanrossum** [comment]
Since recently, mypy treats `divmod()` as a binary operator, checking for `__divmod__` and `__rdivmod__`. Hopefully that should be enough?

**Comment by shoyer** [comment]
Indeed, this works with the latest mypy release (0.570). I should have that checked that first!
