### ISSUE TITLE
Can't have an alias that just targets a type variable

### ISSUE THREAD

**Issue by eric-wieser** [python/typing#543]
Consider version 1 of my package, which defines

```python
T = TypeVar('T', int, float)
MyType = Union[T, List[T]]

# in the user's code
U = TypeVar('U', int, float)
def myfunc(MyType[U], U): ...
```
In version 2, I decide to drop support for passing `List[T]`. However, this causes an error on the downstream type definitions
```python
T = TypeVar('T', int, float)
MyType = Union[T]  # or Generic[T], or T - all fail

# downstream code doesn't change - I want the freedom to change `MyType` again in future
U = TypeVar('U', int, float)
def myfunc(MyType[U], U): ...  # fails due to missing __getitem__
```

Is there a way to write this? Does implementing `TypeVar.__getitem__` seem reasonable? Or should we introduce `Identity[T]`, which boxes a typevar into a generic?

**Comment by eric-wieser** [comment]
So one argument in favor of this is that the result of `Union` depends on it's arguments. This succeeds

    X = Union[T, int]
    X[U]

Yet this fails

    X = Union[T]
    X[U]

Contrast this with the equivalent C++ code, which just works:
```C++
template<typename T>
using X = union<T>;
```
```C++
template<typename T>
using X = union<T, int>;
````

**Comment by eric-wieser** [comment]
Note that I give a real application in the referenced issue above. In python 3, we have
```python
T = TypeVar('T', *AnyStr.__constraints__)
PathType = Union[T, PathLike[T]]

# use PathType[str], PathType[bytes], PathType[AnyStr], etc
```
But there is no way to specify this type on python 2, where the definition is just
```
T = TypeVar('T', *AnyStr.__constraints__)
PathType = ???[T]
```

**Comment by ilevkivskyi** [comment]
Hm, it looks like an experimental `mypy_extensions.FlexibleAlias` is exactly what can help in this case.

**Comment by JelleZijlstra** [comment]
PEP 695 addresses this. (Not on Python 2, but we don't care about that any more.)

```python
type MyType[T: (int, float)] = T

# Or
from typing_extensions import TypeAliasType, TypeVar

T = TypeVar("T", int, float)
MyType = TypeAliasType("MyType", T, type_params=(T,))

def myfunc[U: (int, float)](a: MyType[U], b: U): ...
```
