### ISSUE TITLE
Unsound generic function

### ISSUE THREAD

**Issue by nilehmann** [python/typing#544]
I was playing with mypy for the first time and realize that it allows me to write the following unsound code.

```python
from typing import List, TypeVar

T = TypeVar("T")

def listify(obj: T) -> List[T]:
    if isinstance(obj, list):
        return obj
    return [obj]

listify([1])[0].append(1)
```

**Comment by ethanhs** [comment]
I don't think mypy is doing anything wrong here.

The underlying issue is that since you declared your function returning `List[T]`, and the type of `obj` as you called it is `List[int]`, `T` == `List[int]` so `List[T]` == `List[List[int]]`. I think this is a case where overloads should be used instead of generics, so something like this would be better:

```
from typing import List, TypeVar, overload, Union, Any

T = TypeVar("T")

@overload
def listify(obj: List[T]) -> List[T]:
    pass

@overload
def listify(obj: T) -> List[T]:
    pass

def listify(obj: Any) -> Any:
    if isinstance(obj, list):
        return obj
    return [obj]

reveal_type(listify(1))  # main.py:19: error: Revealed type is 'builtins.list[builtins.int*]'
reveal_type(listify([1]))  # main.py:20: error: Revealed type is 'builtins.list[builtins.int*]'
```

Also, this belongs on the [mypy bugtracker](https://github.com/python/mypy).

**Comment by gvanrossum** [comment]
Agreed with Ethan -- the solution is to rewrite this as an overload.

To clarify, the reason mypy doesn't complain about the original code is that after `isinstance(obj, list)` the inferred type of `obj` is `List[Any]`, which is compatible with the return type `List[T]` (the `Any` is compatible with, well, *anything*).

**Comment by nilehmann** [comment]
Sorry to brings this back up. But to clarify, I'm not looking for the correct way to annotate my code, I'm complaining because mypy allows me to write unsound code in what appears to be a completely statically typed code.

As @gvanrossum clarified the problem arises because mypy is *inferring* the type `List[Any]` after the type test, but the way I see it, what mypy is actually doing is *implicitly casting* the variable to be of type `List[Any]`. While I understand the value of bypassing type system, either with `Any` or with (explicit) casts, I believe this should always be decided by the programmer and not the type system. The correct behavior for me will be to infer `List[object]`.

As I said I'm new to mypy and I'm just trying to understand it.

**Comment by gvanrossum** [comment]
If you are still trying to understand it, don't complain.

**Comment by nilehmann** [comment]
@gvanrossum you are right. I believe I prematurely gave my counterargument.

By understand I mean understand why have you historically decided this approach. I know runtime type tests have been particularly subtle in the context gradual/optional typing and any solution will have to be ad hoc. Just trying to understand the reasons behind mypy solution.

**Comment by ilevkivskyi** [comment]
Just as a random idea, there may be some potential for `--warn-return-any` flag. I think it is too special now (warning only about `Any`, but not `List[Any]` etc). You can open an issue about this on mypy tracker.

Motivation is simple, we don't want loads of errors for existing code, all strictness options (with few well discussed exceptions) are opt-in.

**Comment by JukkaL** [comment]
> The correct behavior for me will be to infer List[object].

Inferring `List[object]` is not safe either, since it allows adding arbitrary objects to the list using `append`, for example. The safe thing would be to infer an existential type `List[X]` for some `X`.
