### ISSUE TITLE
Write docs

### ISSUE THREAD

**Issue by KOLANICH** [python/typing#546]
Hello. I have tried to create a generic, marking an argument with a flag (java `final` should look like
```python
def func(a:Final[int]):
   pass
```
, it has no python counterpart, it's just for IPython shell for more clarity), but failed: I constantly get various errors and I surely don't want to dig deeply into this code. Could you create the docs on how to create own generic type annotation classes. And why they are classes.

**Comment by ilevkivskyi** [comment]
This is literary the first search result for `typing Python` https://docs.python.org/3/library/typing.html
