### ISSUE TITLE
On Python 2, typing registers bytearray as a subclass of collections.Sequence

### ISSUE THREAD

**Issue by li-dan** [python/typing#547]
It's surprising that importing typing has this side effect:

```
$ python2
Python 2.7.14 (default, Nov  2 2017, 17:39:03)
[GCC 5.3.1 20160406 (Red Hat 5.3.1-6)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import collections
>>> issubclass(bytearray, collections.Sequence)
False
>>> import typing
>>> issubclass(bytearray, collections.Sequence)
True
```

I think this is because `bytearray` is registered as a subclass of `ByteString`: https://github.com/python/typing/blob/fcb6f4c31bcc30a26d8c9a63579d9179db3cebff/python2/typing.py#L1795

**Comment by gvanrossum** [comment]
It may be surprising, but is anything harmed by this behavior?

**Comment by li-dan** [comment]
I don't use `bytearray`, so I'm not aware of any problems caused by this.

If this is deliberate, then it's probably fine to close this issue.

**Comment by ilevkivskyi** [comment]
I am not sure this is intentional. I vaguely remember that we had this on Python 3 also, but it caused problems for something/someone and we removed the register call around a year ago. Not sure however about Python 2. Is there any difference in `bytearray` API between Python 2 and 3? If not, then I would propose to remove the register call on Python 2 as well just to keep everything in sync.

**Comment by li-dan** [comment]
The difference with Python 3 is that `bytearray` is registered as a subclass of `collections.Sequence` inside `collections` itself: https://github.com/python/cpython/blob/79c3bab35cce55e6d175aff96a845bc6d932b203/Lib/_collections_abc.py#L942

**Comment by gvanrossum** [comment]
I didn't even know we had bytearray in Python 2. Must be a backport from Python 3. I'm okay with removing it.

**Comment by gvanrossum** [comment]
Hold on, Daniel's observation probably explains this, and it should
probably stay.

**Comment by ilevkivskyi** [comment]
> Hold on, Daniel's observation probably explains this, and it should
probably stay.

OK, then we can close this.
