### ISSUE TITLE
Issues with caching of equivalent but not identical generic types

### ISSUE THREAD

**Issue by mitar** [python/typing#559]
This is as expected:

```python
>>> from typing import *
>>> Union[int, None] is Union[None, int]
False
>>> Union[int, None] == Union[None, int]
True
```

When order is not the same, types are equivalent, but not identical.

But, when used inside generic, then a surprise happens:

```python
>>> from typing import *
>>> List[Union[int, None]] is List[Union[None, int]]
True
>>> List[Union[int, None]] == List[Union[None, int]]
True
```

The issue is that the first instance of `List[Union[int, None]]` is cached and returned for `List[Union[None, int]]` as well. So:

```python
>>> from typing import *
>>> A = Union[int, None]
>>> B = Union[None, int]
>>> List[A]
typing.List[typing.Union[int, NoneType]]
>>> List[B]
typing.List[typing.Union[int, NoneType]]
>>> assert List[B].__args__[0] is B
AssertionError
```

I think caching should cache only identical generic types, not equivalent generic types.

In our case this is a problem because we inspect types and generate JSON description of types. And now it is happening that JSON descriptions are changing (because order of values in `Union` is changing) depending on the order of code loading and which generic type is loaded first during runtime.

**Comment by ilevkivskyi** [comment]
I would say if your code depends on `Union[str, int]` and `Union[int, str]` being different, then there is something wrong with your code. It is standard to cache by `__eq__`/`__hash__`, I have never seen caching by `is`, also it is not something new, I believe types were cached like this since late 2016.

**Comment by mitar** [comment]
> It is standard to cache by `__eq__`/`__hash__`

Sure, but then cache also `Union[int, None]`, so that `Union[int, None] is Union[None, int]` equals `True`. I do not mind either way.

**Comment by gvanrossum** [comment]
You should not count on the caching either way.
