### ISSUE TITLE
Usage of typing_extensions.Protocol causes unbounded recursion for isinstance(obj, Mapping)

### ISSUE THREAD

**Issue by macisamuele** [python/typing#562]
Affected python versions: 3.5.1 and 3.5.2
Usage of `typing_extensions.Protocol` causes `isinstance` check of `Mapping` to fail in case the object of the comparison is not a `dict` instance.

Code that could trigger the error (on `typing-extensions==3.6.2.1`)
```python
from collections import Mapping
from typing_extensions import Protocol
assert isinstance((), Mapping) is False
```

Shortened example of traceback
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/abc.py", line 191, in __instancecheck__
    return cls.__subclasscheck__(subclass)
  File "/usr/local/lib/python3.5/abc.py", line 226, in __subclasscheck__
    if issubclass(subclass, scls):
...
RecursionError: maximum recursion depth exceeded`
```

I've tried to add some debugging statements on `lib/python3.5/abc.py` in order to extract some lead and I did found that while resolving the subclasses of `typing_extensions.ChainMap` the code gets into an infinite recursion
```
<class 'collections.ChainMap'> <class 'tuple'>
typing_extensions.ChainMap[~KT, ~VT] <class 'tuple'>
<class 'collections.ChainMap'> <class 'tuple'>
typing_extensions.ChainMap[~KT, ~VT] <class 'tuple'>
<class 'collections.ChainMap'> <class 'tuple'>
typing_extensions.ChainMap[~KT, ~VT] <class 'tuple'>
```

More details on how to reproduce and tracebacks on: https://gist.github.com/macisamuele/1575444e423469f4e37679f5010119ec

Found out that according to the [changelog](https://docs.python.org/3.5/whatsnew/changelog.html#python-3-5-3-final) some improvements were made regarding `abc` ([bpo-28556](https://bugs.python.org/issue28556))

**Comment by ilevkivskyi** [comment]
Hm, this looks bad. Sorry for this!

Could you please give some more details? I just tried to reproduce this on 3.6.5 and everything works for me. Could please check whether this is fixed when you update `typing_extensions`?

**Comment by ilevkivskyi** [comment]
(just to clarify, above I mean `typing_extensions` 3.6.5, I am on Python 3.6.0)

**Comment by ilevkivskyi** [comment]
> Could eventually be possible to add a small changelog/history for this package?

`typing_extensions` is just a staging area for features that are expected to be included in `typing`, therefore we don't have a changelog. However, as soon as `Protocol` will be moved to `typing` the changes will logged in the Python's `Misc/NEWS`.

**Comment by srittau** [comment]
I could not reproduce this in the latest `typing_extensions` version. The comments above also suggest that this has been fixed.
