### ISSUE TITLE
A different annotation for *args and **kwargs

### ISSUE THREAD

**Issue by pretodor** [python/typing#569]
I would like to ask we annotate `*args` and `**kwargs` with container types instead of element types.

Container types are already used when packing values into a variable:
```
x: int
y: int
z: List[int]
x, y, *z = [10, 20, 30, 40, 50]
```

Here is an example of how we would annotate `*args` in TypeScript:
```
function f(...args: Array<number>): void {}

let args: Array<number> = [10, 20, 30];
f(...args);
```

Here is an example of how we would annotate `*args` in Python with a container type:
```
def f(*args: Sequence[int]) -> None: ...

args1: List[int] = [10, 20, 30]
args2: Tuple[int, ...] = (10, 20, 30)

f(*args1)
f(*args2)
```

**Comment by srittau** [comment]
I disagree. Adding the container type is just unnecessary boiler-plate, which not only increases the amount to type, but (arguably) affects code readability. There is also a difference between annotating a variable `z`, like in your first example, and `*z` in function declarations, with the star implying the container.

If tuple destructuring assignments could be annotated, your first example would probably read like this:

```
x: int, y: int, *z: int = [10, 20, 30, 40, 50]
```

**Comment by gvanrossum** [comment]
I disagree too, it's several years too late to reopen this decision. Also the similarity with extended unpacking is not exact: you don't write `*z: List[int]`.

I'm also unclear on one thing. @pretodor wrote "Here is an example of how we would annotate *args in TypeScript". Is that actually how Typescript currently works, or are you also proposing to change Typescript? You use exactly the same tense ("would annotate") for your proposal to change Python type annotations.

**Comment by pretodor** [comment]
This is indeed how TypeScript works.[1] (Note, In TypeScript `Array<string>` and `string[]` can be used interchangeably.)

I was proposing we annotate `*args` (and `**kwargs`) with container types like they do in TypeScript.

> you don't write `*z: List[int]`

@gvanrossum, true, but when we annotate the example with a comment, it looks like this:
```
x, y, *z = [10, 20, 30, 40, 50]  # type: int, int, List[int]
```
It is not clear, in my opinion, whether `List[int]` refers to the container or the element type of `z` here.

Another approach I'm open to discuss is to prepend the container type of `*args` with an asterisk too. Example:
```
def f(*args: *Sequence[int]) -> None: ...
```

[1] https://www.typescriptlang.org/docs/handbook/functions.html#rest-parameters

**Comment by gvanrossum** [comment]
Then again, PEP 526 does not support annotating `x, y, *z = ...` at all.

I don't think that "this is how TypeScript does it" is a strong enough argument to break PEP 484.

You haven't given any other reason.

**Comment by pretodor** [comment]
I wanted to discuss a less ambiguous annotation of `*args` and `**kwargs`. If something like:
```
x1, y1, z1 = [10, 20, [30, 40, 50]]  # type: int, int, List[int]
x2, y2, *z2 = [10, 20, 30, 40, 50]   # type: int, int, *List[int]
```
won't be able to make its way to the type system, I'll close this issue.

**Comment by gvanrossum** [comment]
There's nothing ambiguous about the current definition.

**Comment by syrusakbary** [comment]
The current definition of `**kwargs` is a bit weak compared to other languages, as only permits one type of Element.

```python
def f(**kwargs: int) -> None: ...
```

Only allows for one type for the values of `kwargs`.

I'd like to propose back the typing by container, as it allows things like:

```python
class MyOptions(TypedDict):
    name: str
    age: int

def f(**kwargs: MyOptions) -> None: ...
```

**Comment by erictraut** [comment]
The signature `def f(**kwargs: MyOptions) -> None: ...` already has a defined meaning in today's type system. It means that each keyword argument must be of type `MyOptions`. It would be a breaking change to change the existing interpretation.

There has been some discussion of supporting some other form, perhaps reusing the `typing.Unpack` symbol introduced in the recently-accepted PEP 646.

This would take the form `def f(**kwargs: Unpack[MyOptions]) -> None: ...`.

Here are links to some related discussions in the typing-sig mailing list:
https://mail.python.org/archives/list/typing-sig@python.org/thread/IUCXT2IQT4YPRN6O56QEVKN24YJG6JSU/#IUCXT2IQT4YPRN6O56QEVKN24YJG6JSU
https://mail.python.org/archives/list/typing-sig@python.org/thread/FGXUFMMUVBT4J4O4LB4WOYRMUANOPWFS/#Z2QXL5ROAMYPEUDYJYLA5PUNEKWGKENS

**Comment by hauntsaninja** [comment]
Some discussion here as well: https://github.com/python/mypy/issues/4441
