### ISSUE TITLE
python 3.7 RecursionError when using recursive typing definition and get_type_hints

### ISSUE THREAD

**Issue by reinhrst** [python/typing#574]
The following code gives a `RecursionError` in python 3.7.0 (runs fine in 3.6.4, giving the answer `{'return': typing.Sequence[typing.Union[str, typing.Sequence[typing.Union[str, _ForwardRef('Foo')]]]]}`)

```
import typing

Foo = typing.Sequence[typing.Union[str, "Foo"]]

def a() -> Foo:
   ...

typing.get_type_hints(a)
```

**Comment by ilevkivskyi** [comment]
Thanks for reporting! I think this may be related to recent fixes to interaction between `get_type_hints` and `from __future__ import annotations`. The fix for this regression may be non-trivial, so I would prefer to wait for @ambv opinion here.

**Comment by srittau** [comment]
As the `typing` module is not part of Python, please file a bug report at bugs.python.org if this is still an issue.
