### ISSUE TITLE
Abstract class methods?

### ISSUE THREAD

**Issue by sid-kap** [python/typing#577]
This might not be the right place to put this, but is there any interest in adding a decorator for abstract class methods? (And potentially supporting it in MyPy?)

Currently, annotating a method with both `@abstractmethod` and `@classmethod` results in a runtime error. I see some suggestions on how to make this work on [StackOverflow](https://stackoverflow.com/questions/11217878/python-2-7-combine-abc-abstractmethod-and-classmethod), but of course those custom decorators would not be supported in MyPy.

I would be interested in either making using both decorators work, or adding a new decorator.

**Comment by JelleZijlstra** [comment]
This seems to work fine already:
```
class A(metaclass=ABCMeta):
   @classmethod
   @abstractmethod
   def f(cls):
       pass
```
So I don't think anything else is needed here.

**Comment by sid-kap** [comment]
Good to know that it works, thanks! It looks like my error was happening because I put `@abstractmethod` and `@classmethod` in the wrong order:

```python
from abc import ABCMeta, abstractmethod

class B:
  __metaclass__ = ABCMeta

  @abstractmethod
  @classmethod
  def f(cls):
    pass
```
Running this with python2 gives the error:
```
Traceback (most recent call last):
  File "test_abstractclassmethod.py", line 3, in <module>
    class B:
  File "test_abstractclassmethod.py", line 7, in B
    @classmethod
  File "/Users/sidharthkapur/.pyenv/versions/2.7.14/lib/python2.7/abc.py", line 32, in abstractmethod
    funcobj.__isabstractmethod__ = True
AttributeError: 'classmethod' object has no attribute '__isabstractmethod__'
```

Do we want to fix this? Or is this behavior fine?

**Comment by gvanrossum** [comment]
If that fails with Python 2 there is nothing we can do about it -- `@abstractmethod` and `@classmethod` are both defined by the stdlib, and Python 2 isn't going to fix things like this (Python 2 end of life is 1/1/2020).

**Comment by sid-kap** [comment]
Hmm, looks like a similar (not identical) error happens in python3 as well:
```
Traceback (most recent call last):
  File "test_abstractclassmethod.py", line 3, in <module>
    class B:
  File "test_abstractclassmethod.py", line 7, in B
    @classmethod
  File "/Users/sidharthkapur/.pyenv/versions/3.6.4/lib/python3.6/abc.py", line 25, in abstractmethod
    funcobj.__isabstractmethod__ = True
AttributeError: attribute '__isabstractmethod__' of 'classmethod' objects is not writable
```

**Comment by gvanrossum** [comment]
You can file a bug in the Python issue tracker -- possibly this is all we
can do and it should just be documented. Or possibly it is already
documented?

**Comment by JelleZijlstra** [comment]
Note that that error happens only with one ordering of the two decorators; it works if you swap them. Ideally that should indeed be documented though, and perhaps `@abstractmethod` should have a better error message tailored for this case.
