### ISSUE TITLE
dataclasses.asdict() mishandles dataclass attributes that are instances of subclassed typing.NamedTuple

### ISSUE THREAD

**Issue by thismachinechills** [python/typing#578]
Reproduced on Python 3.7.0 on Linux and macOS.

To reproduce:

```python
from typing import NamedTuple
from dataclasses import dataclass, asdict

class NamedTupleAttribute(NamedTuple):
    example: bool = True

@dataclass
class Data:
    attr1: bool
    attr2: NamedTupleAttribute

data = Data(True, NamedTupleAttribute(example=True))
namedtuple_attr = asdict(data)['attr2']
print(type(namedtuple_attr.example))
>>> generator
```

One would expect that the printed type would be of type bool.

Cross referenced with python.org issue tracker: https://bugs.python.org/issue34363

**Comment by ilevkivskyi** [comment]
I propose to move discussion to b.p.o., since this is more an issue with `dataclasses` than with `typing` (I left a comment there).
