### ISSUE TITLE
Prefer flat namespace over using typing.io and typing.re

### ISSUE THREAD

**Issue by srittau** [python/typing#589]
The conclusion of python/typeshed#1652 says that importing from `typing` instead of `typing.io` and `typing.re` should be encouraged. That requires changes to PEP 484 as well the standard library documentation.

**Comment by srittau** [comment]
Opened https://bugs.python.org/issue35089 for the documentation issue, python/cpython#10173 for the corresponding PR.

**Comment by srittau** [comment]
I think this is done now.

**Comment by gvanrossum** [comment]
The `io` and `re` namespaces still exist for backward compatibility, right? Could we ever start deprecating those?

**Comment by srittau** [comment]
It seems that typeshed never included those namespaces, so I guess using them in type checkers has never worked. That seems like a indication that deprecating them should not be too disrupting.

**Comment by gvanrossum** [comment]
Ah cool.
