### ISSUE TITLE
typing Match  has no attribute "group"

### ISSUE THREAD

**Issue by zsluedem** [python/typing#595]
The codes in `a.py` : 
```python
import re

def sss(f) -> str:
    a = re.search("kk", f)

    return a.group(1)
```

run `mypy a.py`
an error occured:
`error: Item "None" of "Optional[Match[Any]]" has no attribute "group"`

**Comment by ilevkivskyi** [comment]
This is not about `typing` and is actually an error, if there is no match the function returns `None`, please read the error message carefully.
