### ISSUE TITLE
Using Inference at Runtime

### ISSUE THREAD

**Issue by saulshanabrook** [python/typing#606]
I would like to be able to infer types at runtime, based on the type annotations.

For example, if I define an `identity` function and call that with an `int`, I want to know that I will get back an int:

```python
T = typing.TypeVar("T")

def identity(x: T) -> T:
    ...

y: int
x = identity(y)
reveal_type(x)
# builtins.int*
```

So, at runtime, I would like to be able to understand what type the `identity` function will return given some args. Something like this:

```python
x_type = compute_return_type(identity, int)
assert x_type == int
```

I know that this is something that MyPy does internally, so I am wondering if you think it's advisable to try to import MyPy at runtime and use it's mechanism for type inference to write something like a `compute_return_type` function.

If not, do you know of any other projects trying to do this? 

I apologize if this isn't the right venue for this discussion, I am happy to close this and move it somewhere else if that is preferred.

**Comment by ilevkivskyi** [comment]
Runtime type inference is not something well defined. What many people don't understand is that types are for expressions, not for runtime objects.

> I know that this is something that MyPy does internally

No, mypy never executes your code. It is 100% static analysis.

> if you think it's advisable to try to import MyPy at runtime and use it's mechanism for type inference to write something like a compute_return_type function.

TBH, I am not sure it is very useful, but some people may disagree. Also you might be underestimating the scale of such task (taking into account how "orthogonal" runtime types and static types are).

**Comment by saulshanabrook** [comment]
OK I can close this then. I need this, so I will implement it without depending on MyPy.

**Comment by jarble** [comment]
@saulshanabrook The [MonkeyType](https://github.com/Instagram/MonkeyType) library can generate type annotations for functions using type information at runtime.

**Comment by smheidrich** [comment]
Regarding MonkeyType, it looks like a) it requires you to run your Python code using their own `monkeytype run` CLI command (which writes traces gathered from your code's execution into an SQL database, so this would probably harm performance significantly for larger projects) and b) there is, as far as I can tell, no proper API for accessing the information from within your script at runtime, which is what this issue is about (even though it should be possible in theory). Am I missing something?
