### ISSUE TITLE
Deprecated qualifier?

### ISSUE THREAD

**Issue by jbasko** [python/typing#609]
Are there any plans or existing ways to specify a thing as deprecated apart from issuing DeprecationWarning?

```
x: Deprecated[int]

class S:
    y: Deprecated[ClassVar[int]]

def x() -> Deprecated[int]:
    return 5

class A:
    pass

class B(Deprecated[A]):
    pass
```

If it was in the language, a tool like PyCharm could benefit from it.

**Comment by ilevkivskyi** [comment]
It looks like this is a good case for `typing_extensions.Annotated`. One can define:
```python
from typing import TypeVar
from typing_extensions import Annotated

T = TypeVar('T')

Deprecated = Annotated[T, 'deprecated']
```
and then use it exactly as in your example.

**Comment by ilevkivskyi** [comment]
See https://www.python.org/dev/peps/pep-0593/ for more details.

**Comment by ilevkivskyi** [comment]
Actually I don't think we need to keep this open (now the discussion can happen per type-checker/tool whether to support the deprecated annotation).

**Comment by jbasko** [comment]
Thanks @ilevkivskyi . That's neat.
