### ISSUE TITLE
GitHub tags not up to date

### ISSUE THREAD

**Issue by jayvdb** [python/typing#618]
The last tag was 3.6.4, but PyPI is now at 3.7.2

Without a managed changelog in the repo, tags are very important for packagers to use to write up their changelog entries for the package.

**Comment by gvanrossum** [comment]
I only see typing 3.6.6 on PyPI. Presumably that tag is still in Ivan's local repo.

**Comment by jayvdb** [comment]
Ah my apologies, I meant [`typing_extensions`](https://pypi.org/project/typing-extensions/) which co-exists here.

**Comment by ilevkivskyi** [comment]
Yes, this is my fault. I will push the tags upstream.

Btw, what to do with `typing_extensions`? Since it is in the same repo, we need to invent naming scheme for the tags, so that they don't clash with `typing` versions.

**Comment by gvanrossum** [comment]
Maybe we should move typing_extensions to its own repo? That's what we did with mypy_extensions. Repos are cheap. :-)

**Comment by ilevkivskyi** [comment]
Just to clarify, you propose to split `typing_extensions` into a separate repo. Then only push the missing tags for the `typing` releases here, and in the new repo push the tags that correspond to the `typing_extensions` releases, but remove the older `typing` tags, right?

**Comment by gvanrossum** [comment]
Yeah. The releases don’t match up anyway.

**Comment by srittau** [comment]
This repository was restructured since. I think the issues should not crop up in the future.
