### ISSUE TITLE
Protocols for types with fields that can be verified

### ISSUE THREAD

**Issue by quodlibetor** [python/typing#621]
I'm not sure if this should be reported to this repo or the mypy repo, ultimately I'm sure if protocols are _supposed_ to support this, so here I am.

I have some complex objects that can be in one of several states once they have been verified, and I'd like to represent that verification as different types, but I'm having a hard time getting it to work with protocols.

I believe that something like this should work:

```python
from __future__ import annotations
from typing import NamedTuple, Protocol, Optional

class Simple:
    two: Optional[int]

    def as_simpl_verified(self) -> SimpleVerified:
        assert self.two is not None
        return self

class SimpleVerified(Protocol):
    two: int
```

```
$ pip freeze | rg mypy
mypy-extensions==0.4.1
mypy-mypyc==0.670
```

but I get this error:

```term
$ mypy example_simple.py
example_simple.py:11: error: Incompatible return value type (got "Simple", expected "SimpleVerified")
example_simple.py:11: note: Following member(s) of "Simple" have conflicts:
example_simple.py:11: note:     two: expected "int", got "Optional[int]
```

**Comment by ilevkivskyi** [comment]
This is a potentially valid feature request for type checkers. But it is not _required_ by any typing related PEP. Please open an issue for a particular type checker you are using.

**Comment by gvanrossum** [comment]
It could be seen as a request for a feature for a future PEP though. And Protocols are still under review.

**Comment by ilevkivskyi** [comment]
This has nothing to do with protocols. This behavior is caused by how conditional type binder is implemented in mypy. I hope we are not going to standardize how type binder behaves otherwise dozens issues from mypy should be moved here.

**Comment by gvanrossum** [comment]
OK, now I see. To the OP: just add a cast to fix this.

**Comment by quodlibetor** [comment]
Thanks!

In case others come run into this, this is the fix:

```python
    def as_simple_verified(self) -> SimpleVerified:
        assert self.two is not None
        return typing.cast(SimpleVerified, self)
```
