### ISSUE TITLE
Proposal: syntactic sugar/language-level support for protocols

### ISSUE THREAD

**Issue by antonagestam** [python/typing#638]
Protocols are arguably something different from other classes in Python, they have their own semantic meaning and works in different way (structural instead of nominal sub-typing). I think mirroring this in the syntax could be helpful to emphasize the fact that they are something else. In other words I think they're different enough to warrant their own keyword.

The syntax I suggest is to replace the `class` keyword with a new `protocol` keyword.

```python
protocol Point:
    x: int
    y: int
```

**Comment by ilevkivskyi** [comment]
Thanks for the proposal! TBH I don't see much value in this. It saves just 5-6 keystrokes per protocol, but you can't imagine how hard it is to get a new keyword in Python. Introducing `async` took three release cycles, and lots of effort throughout the community. So I would propose to just close this.
