### ISSUE TITLE
Combining Generic and NamedTuple

### ISSUE THREAD

**Issue by DrPyser** [python/typing#653]
Currently, in python 3.7, it seems impossible to properly compose `typing.NamedTuple` and `typing.Generic`. That is, I want to do this:

```python
import typing
T = typing.TypeVar("T")

class Test(typing.NamedTuple, typing.Generic[T]):
    a: T
```
So this works, the class can be used as a `NamedTuple`.
However:
```
x: Test[int] = Test(a=1) # TypeError: 'type' object is not subscriptable
```
Right, subclassing `NamedTuple` generates a class that inherits only from `tuple`.

Maybe this was discussed before, I've looked a bit in this repo and haven't found much, except #588, which doesn't really address this.

Is there any plan or possibility for this to be resolved? Maybe more generally, allowing `NamedTuple` to be composable with other types(I know this might be difficult because of metaclass conflicts).

Thanks!

**Comment by DrPyser** [comment]
Something of a workaround:
```
import typing
T = typing.TypeVar("T")
class Test(typing.NamedTuple):
    a: T
class Test(Test, typing.Generic[T]): pass

x: Test[int] = Test(a=1) # works fine
```

**Comment by lemon24** [comment]
It seems this is being worked on in https://github.com/python/mypy/issues/685.

**Comment by illeatmyhat** [comment]
It's also impossible to do
```
from typing import TypedDict, TypeVar, Generic

T = TypeVar('T')
class Test(TypedDict, Generic[T]):
    a: T
```

**Comment by srittau** [comment]
If a type checker doesn't support this, this seems to be more of a type checker issue than a general typing issue, so I'm closing this here.

**Comment by Gobot1234** [comment]
Typing currently bans this in mro entries

**Comment by AlexWaygood** [comment]
This is now:

- Supported at runtime in 3.11
- Supported by pyright
- and we have #1174 to discuss backports via `typing_extensions`.

So I think this feature request can be closed as "accepted"!
