### ISSUE TITLE
Type annotation of a subclass method that return an instance of the class

### ISSUE THREAD

**Issue by Andreyisakov** [python/typing#657]
I'm running into an issue when a subclass has an internal state that is not visible by the parent.  I able to explain the issue by the following concrete example: 

I have a `MeasurementBase` abstract parent class that have the following functionality: (1) public `serialize()` & `deserialize()` 

I would love to implement the common logic on the parent public methods and to define the private `_serialize()` &  `_deserialize()` abstract. 

The base class implementation is as follows:

```
import json
from abc import ABC, abstractmethod
from typing import Any, Dict, Generic, TypeVar


TMeasurement = TypeVar("TMeasurement")


class MeasurementBase(ABC, Generic[TMeasurement]):

    def serialize(self) -> str:
        properties: Dict[str, Any] = {}
        properties["measurement_name"] = self.__class__.__name__
        properties["value"] = self._serialize()
        return json.dumps(properties)

    @abstractmethod
    def _serialize(self) -> Any:
        pass  # pragma: no cover

    @classmethod
    def deserialize(cls, json_str: str) -> TMeasurement:
        try:
            properties = json.loads(json_str)
            class_name = properties["measurement_name"]
            if cls.__name__ != class_name:
                raise KeyError()

            return cls._deserialize(properties["value"])
        except KeyError:
            raise KeyError()

    @classmethod
    @abstractmethod
    def _deserialize(cls, obj: Any) -> TMeasurement:
        pass  # pragma: no cover
```

Then, I created a new subclass with internal `_val` state that implements the abstract methods: 

```
class MeasurementBaseMock(MeasurementBase["MeasurementBaseMock"]):
    def __init__(self, val: int) -> None:
        self._val = val

    def _serialize(self) -> Any:
        return self._val

    @classmethod
    def _deserialize(cls, obj: int) -> "MeasurementBaseMock":
        return MeasurementBaseMock(obj)

```

Then, when testing the above: 

```
properties = {"value": 324, "measurement_name": MeasurementBaseMock.__name__}
measurement = MeasurementBaseMock.deserialize(json.dumps(properties))
print(measurement._val)

```

I got the following error: 

`error: "TMeasurement" has no attribute "_val"` 

How do I annotate the `_deserialize` return type to support the typecker? 

Things that I tried: 
- I tried using the `TMeasurement = TypeVar("TMeasurement", bound = "MeasurementBase")` - didnt work and had much more mypy error. 
- I moved all the state's initialization to parent class - this one did work, but I prefer not using such design. 

- I tried also using cls annotations but had the same error. 

```
> mypy --version
mypy 0.660
```

**Comment by gvanrossum** [comment]
Have you tried this with mypy 0.711? I cannot repro it.

**Comment by ilevkivskyi** [comment]
I can' repro either. Moreover this has nothing to do with `typing` (also it looks like self-types is a more appropriate pattern for what you want to achieve).
