### ISSUE TITLE
"BinaryIO" has no attribute "readinto"

### ISSUE THREAD

**Issue by srittau** [python/typing#659]
Per python/typeshed#2166 and @gvanrossum's comment there.

**Comment by ianliu** [comment]
Is there a way to monkey-patch the typing or typeshed to workaround this issue?

**Comment by gvanrossum** [comment]
Just use `# type: ignore`

**Comment by ianliu** [comment]
Maybe Python could make something like TypeScript's [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). The typing definitions are updated very quickly there, but I'm just diverging here.
Thanks!

**Comment by gvanrossum** [comment]
We have that, it's called typeshed.

**Comment by gvanrossum** [comment]
Question for @srittau: why is this filed under typing? It would have to be changed in typing.pyi in typeshed, right? Or am I missing something?

**Comment by gvanrossum** [comment]
Sure, for that all we need is a PR added for CPython 3.9.

But presumably we wouldn’t get questions here if it was right in typeshed.

Or are there problems with this? Is it universally supported by all subclasses?

**Comment by srittau** [comment]
I have honestly lost a bit of track about how the different IO classes relate to each other, especially as I see the future in protocols. So I'm not sure if this issue is still relevant, or whether it should be added to typeshed only. I have no objections either way.

**Comment by gvanrossum** [comment]
I am hoping someone else is interested in sorting out this mess.

**Comment by socketpair** [comment]
`error: "IO[bytes]" has no attribute "readinto"`

The same.

**Comment by srittau** [comment]
I am closing this here. If someone still thinks this is an issue that needs to be addressed, this should probably go into the bugs.python.org issue tracker.
