### ISSUE TITLE
Please allow doing one-liners such as `a: int, b: int = 1, 2`

### ISSUE THREAD

**Issue by guillaume-chevalier** [python/typing#664]
By the way, if this is not the proper place to open the issue, could you please link to the good place or existing issue and close this one? Thx!

**Comment by gvanrossum** [comment]
That is intentionally disallowed because the priority of the comma is ambiguous.

**Comment by guillaume-chevalier** [comment]
I wouldn't have expected the commas to cause ambiguity in the order things are parsed. Eliminating any possible ambiguity, this works: 
```
    (a, b) = do_something(1, 2)
    (a), (b) = do_something(1, 2)
    ((a), (b)) = 1, 2
```

I'd love that this worked too, to avoid having to use many lines nor wrapping the function to define the return type: 
```
    ((a: int), (b: int)) = do_something(1, 2)
```

If possible, I'd prefer doing this if the priority of the `,` is fine with the priority of the `:` :  
```
    a: int, b: int = do_something(1, 2)
```
To the best of my understanding, I don't expect that `a: int, b: int` would be interpreted as `a: (int, b: int)` by the interpreter, but rather, I think it is `(a: int), (b: int)`. If I'm wrong, then I understand that enabling people to do `((a: int), (b: int)) = do_something(1, 2)` is not a priority because of the rarity of using such parentheses on the left hand side. 

I'm also supposing more complicated types than `int`, and supposing that `do_something`'s return type is unclear. This issue 2 to 4 times to me in the last weeks. I don't have anything more to add.

**Comment by ilevkivskyi** [comment]
As @JukkaL just mentioned in the other thread (and I totally agree with him) the recommended way is:
```python
a: int
b: int
a, b = do_something(1, 2)
```
This question was already discussed in PEP 526, I don't think anything changed since that time.
