### ISSUE TITLE
Maybe one-liners such as `(a: int, b: int) = do_the_thing(1, 2)` then? 

### ISSUE THREAD

**Issue by guillaume-chevalier** [python/typing#665]
I'd love it to avoid doing this: 
```
    a: int = None
    b: int = None
    a, b = do_the_thing(1, 2)
```
Supposing that the return type of the callable `do_the_thing` is unclear or too broad. The context is normal (e.g.: doing this code within the body of a function, not in a function argument list). 

Previous issue: https://github.com/python/typing/issues/664

**Comment by gvanrossum** [comment]
Please don't keep opening new issues about this. If you want to discuss it further feel free to add comments to the previous (closed) issue. We still read the discussion. But you need to come up with data showing this is a common issue.

**Comment by guillaume-chevalier** [comment]
Closing this one - I thought that removing the ambiguity with the comma (if any) would make it a radically different issue.

**Comment by JukkaL** [comment]
Note that you don't need the initializers. This works:

```py
    a: int
    b: int
    a, b = do_the_thing(1, 2)
```
