### ISSUE TITLE
Cannot create weak reference to NamedTuple

### ISSUE THREAD

**Issue by Qu4tro** [python/typing#672]
Hey there.

I'm creating this issue in the follow up of https://github.com/pydanny/cached-property/issues/168 and https://github.com/pydanny/cached-property/pull/137

As @althonos mentioned, NamedTuple doesn't have a `__weakref__` slot. My question is here, if there's any implementation detail that prohibits NamedTuple to have it or if it's just missing.

You can use this repo as an example:
https://github.com/Qu4tro/cachedproperty_immutable_classes/

Thanks in advance.

**Comment by ilevkivskyi** [comment]
This is kind of intentional, please read this email https://mail.python.org/pipermail/python-list/2005-March/346300.html

If it is not convincing, then open an issue on https://bugs.python.org and add Raymond Hettinger to nosy list.

**Comment by Qu4tro** [comment]
Thanks, that was the answer I was looking for.
