### ISSUE TITLE
Using typing with Pycharm

### ISSUE THREAD

**Issue by JackDandy** [python/typing#673]
Hi,

`typing library 3.7.4.1`
`PyCharm Pro 2019.2.1`
`Python 2.7.16`
`Win 10 x64`

I include an annotated image with a couple of issues in Pycharm,  
the image also demonstrates how to replicate the issues....

<img src="https://i.vgy.me/MzFkiC.png">

Am I doing something wrong, or are these real issues ?

Thanks.

#### test code
```
#
# a test file to highlight issues in Pycharm
#

# issue 1: in the following line `AnyStr` is grey as it regarded as unused import statement, yet `List` is fine

from typing import AnyStr, List


def test_func(test_arg=None, test_arg2=None):
    """
    Just a test func. to highlight
    1) even tho AnyStr is used here, it is classed as unused in the above import line,
    this doesn't occur for other types used solely in a docstring.

    2) the callee test_func is underlined with what seems to be a nonsense message...
    Expected Optional[List], got 'list' instead

    :param test_arg:
    :type test_arg: AnyStr or None
    :param test_arg2:
    :type test_arg2: List or None
    :return: tuple
    :rtype: tuple
    """
    return test_arg, test_arg2


save_map = []
t1, t2 = test_func(test_arg='', test_arg2=save_map)
```

**Comment by JelleZijlstra** [comment]
These sound like issues with PyCharm, not with Python typing in general. Also, the syntax you use for typing in docstrings isn't in line with the typing PEPs (although PyCharm may still support it; I don't know).

**Comment by JackDandy** [comment]
> the syntax you use for typing in docstrings isn't in line with the typing PEPs
  
That was it, thank you.
