### ISSUE TITLE
No backwards compatibility for typing attributes

### ISSUE THREAD

**Issue by nitzanst** [python/typing#676]
In Python 3.5 typing classes, e.g List had attribute __name__.
In Python 3.7 typing classes have instead attribute _name and don't have __name__ attribute.

Wouldn't it be reasonable to backwards compatible on this case
![typing_bug](https://user-images.githubusercontent.com/45848203/64591401-5da14400-d3b2-11e9-843f-ef20bb8a4011.png)
?

**Comment by gvanrossum** [comment]
No, the relevant PEP 484 was provisional, allowing us to improve the API.
