### ISSUE TITLE
Release typing_extensions 3.7.4.1

### ISSUE THREAD

**Issue by tomzx** [python/typing#682]
Hello!

I'm not sure this is the right place to ask, but here goes:

It appears a release of [`typing`](https://pypi.org/project/typing/#history) 3.7.4.1 is available on pypi. However, the associated version of [`typing_extensions`](https://pypi.org/project/typing-extensions/#history) does not appear to have been released.

Could you please make a pypi release for `typing_extensions` 3.7.4.1?

Thank you!

**Comment by ilevkivskyi** [comment]
`typing` and `typing_extensions` releases are not done in "lockstep", 3.7.4 is rather a coincidence.

Also I don't think there were any non-trivial fixes in `typing_extensions` recently, so there is no need for new release. Why do you want a new release?

**Comment by tomzx** [comment]
I'm looking specifically for https://github.com/python/typing/pull/661.

**Comment by ilevkivskyi** [comment]
OK, I see. We can probably make a release next couple of weeks (no strong guarantees however).

**Comment by chrish42** [comment]
Is there anything I can do to help? I'm kinda blocked on this currently...

**Comment by ilevkivskyi** [comment]
OK, `typing_extensions 3.7.4.1` is now live so this can be closed.
