### ISSUE TITLE
Misleading documentation when installing via `pip install -t . typing`

### ISSUE THREAD

**Issue by lingxiaoyang** [python/typing#690]
The following words are misleading because they do not hold true when installing via `pip install -t . typing`:

> NOTE: in Python 3.5 and later, the typing module lives in the stdlib,
> and installing this package has NO EFFECT.

Normally, the installation has no effect because Python standard library takes higher precedence than `site-packages`. 

However, when installing with `-t .`, `typing.py` is pulled in current directory and thus `import typing` will reach out to this library and break any Python 3.7 environment that uses `typing` with an error like:

```
AttributeError: type object 'Callable' has no attribute '_abc_registry'
Traceback (most recent call last):
  ...
  File "/var/task/sentry_sdk/_types.py", line 2, in <module>
    from typing import TYPE_CHECKING as MYPY
  File "/var/task/typing.py", line 1357, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/var/task/typing.py", line 1005, in __new__
    self._abc_registry = extra._abc_registry
```

**Comment by luzfcb** [comment]
Maybe the documentation can recommend using something like `typing;python_version<"3.5"` in the projects that still support python3.4 or lower

**Comment by gvanrossum** [comment]
I didn’t even know about pip -t .

Feel free to submit a PR with a doc update.
-- 
--Guido (mobile)
