### ISSUE TITLE
Multiple types for variable-length Tuples

### ISSUE THREAD

**Issue by rggjan** [python/typing#692]
After https://github.com/python/typing/issues/30 is supported, it would be great if variable-length Tuples would also work with multiple types.

For example, a Tuple with a string and zero or more ints inside could look like this:

Tuple[str, int, ...]

which currently can only be expressed as:

Tuple[Any, ...]

**Comment by arseniiv** [comment]
Supporting at least the subset of types of the form `Tuple[T1, T2, <some Ts>, TRest, ...]` — that is, with `...` allowed only in final position and only once and, for example, not including `Tuple[int, ..., str, bool]` or `Tuple[str, ..., int, ...]` — seems more or less reasonable to me. (Seen this kinds of types in Ceylon language, though there tuple/tuple-like types are intristically linked with callable types, and there is more reason for these that may be here.) Not including the latter kinds of types should ease typechecking, as far I understand it.

I see at least one weak use in DSL design: writing values of the allowed type `Tuple[str, List[int]]` (contrived) is a bit more tedious than writing values of `Tuple[str, int, ...]` instead. Maybe there is even a non-contrived example. :)

It can be argued that if tuple concatenation types for the tuple types postulated today, will become typable in e. g. MyPy or other major typecheckers, then the proposed kind of tuples may be a pain to cover.

**Comment by rggjan** [comment]
Thanks @arseniiv . Just to add to this, my use case is a function in a class which returns a `Tuple[Foo, Any, ...]`.
This class is meant to be subclassed and the function overridden. All subclasses have to return `Foo` as the first element in the `Tuple`, but can choose to add 0 or more additional elements, depending on the subclass usage.

**Comment by arogozhnikov** [comment]
(randomly found this issue). 

In case you know first argument is a string - make it a separate argument. *args by design are expected to be uniform container
