### ISSUE TITLE
Reversible should not be a subclass of Hashable

### ISSUE THREAD

**Issue by Zac-HD** [python/typing#694]
Because, for example, lists are reversible but not hashable.  [BPO-39046](https://bugs.python.org/issue39046) is the equivalent report for `collections.abc`.

I discovered this while working on HypothesisWorks/hypothesis#2274

**Comment by gvanrossum** [comment]
This is weird. There's no explicit relationship between Reversible and Hashable in the source code.

I suspect that whatever the reason, it's in collections.abc, not in the typing module.

**Comment by Zac-HD** [comment]
Closing this, following the BPO issue, because the behaviour of the ABCs is actually fine; the "bug" was in my own code which assumed that because Foo is Reversible and Reversible is Hashable, Foo must also be hashable.  This is true of nominal subtyping via inheritance, but need not be (and isn't) true with abstract protocols.
