### ISSUE TITLE
PEP 586: using asterisk (*) unpacking notation with Literal such as Literal[*some_list]

### ISSUE THREAD

**Issue by jeanmonet** [python/typing#697]
It appears that a syntax error is currently raised if I try to define the Literal contents via *unpacking (unless mistaken this has not been discussed elsewhere).

The use case is a list of keys for a dictionary `AllowedKeys = Literal['key1', 'key2', 'key3']` where one would want to use an existing list of those keys `keys_list = ['key1', 'key2', 'key3']` to define the `AllowedKeys = Literal[*keys_list]`.

Is there anything standing against this notation and usage, or could it be implemented in the future?
(one limitation would probably be that the `keys_list` would need to be a pre-defined list or tuple and not dynamically defined at runtime from external input)

**Comment by ilevkivskyi** [comment]
I think this is already possible using something like:
```python
from typing import Literal, get_args

AllowedKeys = Literal['key1', 'key2', 'key3']
keys = get_args(AllowedKeys)
```
Taking into account there is already a way to do it, and that the bar to new syntax is very high, I would propose to close this.

**Comment by jeanmonet** [comment]
Thanks for feedback. I suppose `get_args` won't get back-ported to `typing_extensions` so I'll have to upgrade to Python 3.8 :)

**Comment by ilevkivskyi** [comment]
> I suppose `get_args` won't get back-ported to `typing_extensions` so I'll have to upgrade to Python 3.8 :)

Actually, I think you can use `typing_inspect` that has a very similar `get_args()` that is supported back to 2.7.

**Comment by jeanmonet** [comment]
Thanks for tip, will take a closer look at `typing_inspect`.

Btw, just learned there is a hidden attribute `AllowedKeys.__args__` (although it is undocumented and may change in the future: https://stackoverflow.com/a/50101934/11750716).
