### ISSUE TITLE
Interoperability of java.Util.Arraylist with typing.List (in Jython)

### ISSUE THREAD

**Issue by gvanrossum** [python/typing#7]
This very specific case was brought up by Jim Baker. While in general typing.List is meant to be the parametrizable version of builtins.list, I am fine with having it support the registration mechanism of ABCs and registering java.util.ArrayList to be equivalent, given that Jim says that in practice it is indeed duck-substitutable (is that even a word? :-) for the built-in list type. (I assume that this means it has a sort() method.)

**Comment by ambv** [comment]
Danger, danger, Will Robinson.

The registration mechanism of ABCs is runtime-based and it's causing some headaches for type hinting. We can't be sure what implementations are going to be registered without importing the entire program first. Moreover, the import order matters. So I wonder what implementation @gvanrossum is suggesting here.

**Comment by gvanrossum** [comment]
I think it's fine if this is just hacked using some Jython-specific stub. We can have a registration mechanism using (or similar to) the one defined in collections.abc to make things work at runtime, and a stub hack to teach the type checker.

**Comment by ambv** [comment]
Requires decision on what to do with the stubs.

**Comment by gvanrossum** [comment]
Well, Jython 3.<anything> is a ways off (Jim is just about to finalize Jython 2.7.0 beta 4). I am convinced that we can provide a stub for java.Util.Arraylist that makes it an alias for or subclass of List (covariance be damned :-). Details of where that stub should live and how exactly it should be spelled needn't hold up the PEP, I think. We will do stubs, see #22.

**Comment by gvanrossum** [comment]
Closing. I presume Jython can figure something out; if they need something specific they can open an issue for mypy or typeshed.
