### ISSUE TITLE
Final qualifier for unpacked values?

### ISSUE THREAD

**Issue by Tatsh** [python/typing#705]
I looked at [PEP 591](https://www.python.org/dev/peps/pep-0591/) and saw no mention of unpacking.

Currently (AFAIK) there does not appear to be a way to make unpacked variables `Final`, either inline or by declaring variables first. Some lines which look like they might work but don't:

```python
x: Final, y: Final = True, False

(x, y): Final = True, False  # *only single target (not tuple) can be annotated  [syntax]*

x, y: Final = True, False  # syntax error, confusing

(x, y) = Final[(True, False)]  # syntax ok but x and y inferred by Mypy as Any, error at runtime
```

Of course the first is very verbose and usually you wouldn't want to have one value be final and another not when unpacking.

The second makes some sense except it would be nice to retain the optional parentheses feature.

**Comment by gvanrossum** [comment]
This is all intentional, to avoid confusion. The reason is PEP 526.

**Comment by cowlinator** [comment]
ok but what is the correct way to type these?

**Comment by JelleZijlstra** [comment]
Use multiple assignment statements.
