### ISSUE TITLE
Cannot Import Literal

### ISSUE THREAD

**Issue by sarthak212** [python/typing#707]
Python version: Python 3.7.5
Os: Kali linux 2020.1

When try to import Literal it Shows a error that Cannot import literal from typing
`ImportError: cannot import name 'Literal' from 'typing' (/usr/lib/python3.7/typing.py)`
Is literal deprecated in new python version? Because Literal is present in python2 typing.py script file but not in new typing.py script file.

**Comment by gvanrossum** [comment]
The Python 3.7 stdlib has an older version of typing.py and won't be updated.

The solution (which you can do for each of your Python versions) is `pip3 install typing_extensions` and then use `from typing_extensions import Literal`.
