### ISSUE TITLE
Cannot Import Literal

### ISSUE THREAD

**Issue by sarthak212** [python/typing#708]
Python Version: Python 3.7.5
Os: Kali Linux 2020.1

When trying to import Literal it Shows following error:
`ImportError: cannot import name 'Literal' from 'typing' (/usr/lib/python3.7/typing.py)`

Is Literal deprecated in Python3 because in Python2 typing source code Literal is present but in new typing.py it isn't?

**Comment by gvanrossum** [comment]
Duplicate. It is not deprecated. See #707

**Comment by sarthak212** [comment]
Ok, thanks @gvanrossum
