### ISSUE TITLE
Bump typing_extensions version

### ISSUE THREAD

**Issue by apadmarao** [python/typing#709]
I'm wondering if we can bump typing_extensions. I'm hoping to depend on the changes to TypedDict in #687 and #700

**Comment by ilevkivskyi** [comment]
Yeah, it has been a while since the last release. I am not sure when I will have time for this, maybe in April.

**Comment by apadmarao** [comment]
Thanks @ilevkivskyi ! I'd love to get this done quickly, and happy to contribute if it makes sense. Is this something that I could submit a PR for?

**Comment by ilevkivskyi** [comment]
Thanks, but unfortunately it is not something you can help with.

**Comment by gvanrossum** [comment]
could I help? I presumably have the pypi permissions.

**Comment by ilevkivskyi** [comment]
It would be great if you can release `typing_extensions`. The release process follows same steps as a `typing` release (don't forget to bump the version).

(I discovered that you weren't an owner of PyPI package so I just added you.)

**Comment by gvanrossum** [comment]
I've released typing 3.7.4.2 on PyPI: https://pypi.org/project/typing-extensions/#files

 I'm going to assume everything's working. Nevertheless, whoever cares please test and report here!

I've also updated the supported versions to include Python 3.8 and 3.9.

**Comment by gvanrossum** [comment]
Note: I've *not* released a new typing package, only typing_extensions. AFAIK the two have unrelated release schedules. I've also not tagged this release. I presume the git tags refer to the typing package releases only.

**Comment by ilevkivskyi** [comment]
Thank you Guido! I checked that new release installs and the expected new feature (`__required_keys__`) works correctly.

**Comment by apadmarao** [comment]
Thank you Guido! Really appreciate it.
