### ISSUE TITLE
Support isinstance check for typing.Type

### ISSUE THREAD

**Issue by penguinolog** [python/typing#710]
Currently objects like `typing.Type[type]` do not support `isinstance` check, btw it can be simple implemented as:

```python
def __instancecheck__(self, instance: Any) -> bool:
    return self.__args__[0] == instance
```

**Comment by gvanrossum** [comment]
Can you give an example where you need this? And did something like that occur to you? Or are you just proposing this for completeness? Does mypy (or some other static Python type checker) currently understand such isinstance() calls?

**Comment by penguinolog** [comment]
I propose it for completeness. I understand, that for most types full
typecheck is complex and that's why disabled, but `Type` is special case.
BTW my mistake: it should check for subclassing if follow documentation

**Comment by gvanrossum** [comment]
In that case I don't think this is important enough to keep open.
