### ISSUE TITLE
NameError on get_type_hints __init__

### ISSUE THREAD

**Issue by endremborza** [python/typing#712]
Hello, I just ran into a strange error. I haven't investigated it very deeply, but so far I couldn't find too much related info. I suppose it has something to do with the dataclass wrapper, as it works nicely without it. The NameError is still very strange though, as it throws it when the name is very much defined

```python
from typing import get_type_hints
from dataclasses import dataclass

@dataclass
class D:    
    a: "A"
        
class A:
    pass

get_type_hints(D)
```
outputs the expected
> `{'a': __main__.A}`

however
`get_type_hints(D.__init__)` raises `NameError` for A

<details>

```

/usr/lib/python3.8/typing.py in get_type_hints(obj, globalns, localns)
   1255         if isinstance(value, str):
   1256             value = ForwardRef(value)
-> 1257         value = _eval_type(value, globalns, localns)
   1258         if name in defaults and defaults[name] is None:
   1259             value = Optional[value]

/usr/lib/python3.8/typing.py in _eval_type(t, globalns, localns)
    268     """
    269     if isinstance(t, ForwardRef):
--> 270         return t._evaluate(globalns, localns)
    271     if isinstance(t, _GenericAlias):
    272         ev_args = tuple(_eval_type(a, globalns, localns) for a in t.__args__)

/usr/lib/python3.8/typing.py in _evaluate(self, globalns, localns)
    516                 localns = globalns
    517             self.__forward_value__ = _type_check(
--> 518                 eval(self.__forward_code__, globalns, localns),
    519                 "Forward references must evaluate to types.",
    520                 is_argument=self.__forward_is_argument__)

NameError: name 'A' is not defined
```
</details>

it works this way: `get_type_hints(D.__init__, globalns=globals())`

because:

`D.__init__.__globals__.keys()` is `dict_keys(['MISSING', '_HAS_DEFAULT_FACTORY', '__builtins__'])`, taken from the dataclass module.

does this behavior warrant any changes?

this is python 3.8.0 btw

**Comment by gvanrossum** [comment]
I am guessing that dataclasses.py synthesizes a __init__ function with globals that don't point to your module. Probably best to take this to book and ask ifdataclasses.py can do better.

**Comment by srittau** [comment]
This should be filed at bugs.python.org if it is still an issue as the typing module is maintained there now.
