### ISSUE TITLE
Typing decorated function ("Callable[..., Any]" has no attribute "__wrapped__")

### ISSUE THREAD

**Issue by maximderbin** [python/typing#713]
Hi, just ran into issue with typing decorated function, did some googling but no luck.

Here is the example:
```python
def my_function(
    method: Callable[..., Any],
    kwargs: Dict[str, Any],
) -> Callable[..., Any]:
    if hasattr(method, "__wrapped__"):
        return method.__wrapped__  # error: "Callable[..., Any]" has no attribute "__wrapped__"
    else:
        return method
```

What will be the best way to specify that function object may or may not be decorated aka have `__wrapped__` attribute?

**Comment by gvanrossum** [comment]
This is something that static type checkers can't know about. I'd just use a `# type: ignore`. If you think there's a bug in a specific type checker, open a bug against that checker (e.g. mypy).
