### ISSUE TITLE
typing.Type doesn't express type metaclass

### ISSUE THREAD

**Issue by wyfo** [python/typing#715]
In this example: 
```python
from typing import Type, TypeVar
T = TypeVar("T")

class Meta(type):
    some_msg: str
    def create(cls: Type[T]) -> T
        print(cls.some_msg)  # Mypy: "Type[T]" has no attribute "some_msg"
        return cls()
```
we see that it's not possible to use `typing.Type` to annotate generic return type and to keep the information that `Type[T]` will be an instance of `Meta`.

I don't really know how it could be achieved with the current syntax. The simplest solution would be to allow an optional second parameter to `Type` for the metaclass with `type` as default value.
An other simple solution could be to add a new keyword parameter to `TypeVar`, something like `type_bound` in order to bind the metaclass instead of the class.
A third and more complex solution would be to  deprecate `typing.Type` in favor of `type` in the same spirit than PEP 585, and to make metaclass generic by extension.
The example could be rewritten:
```python
from __future__ import annotations
from typing import Type, TypeVar
T = TypeVar("T")

class Meta(type): 
    some_msg: str
    def create(cls: Meta[T]) -> T
        print(cls.some_msg)  # no static check issue
        return cls()
```
Like this, `T` could be inferred and checked as an instance of  `Meta`. I think I prefer this solution to the second one (which I prefer to the first one). However, I assume that this is quite a niche issue, as for me I've used less and less metaclass since PEP 487.

**Comment by gvanrossum** [comment]
Is this solution wrong?
```
from typing import TypeVar
T = TypeVar("T", bound="Meta")

class Meta(type):
    some_msg: str
    def create(cls: T) -> T:
        print(cls.some_msg)
        return cls()
```

**Comment by wyfo** [comment]
Actually, I think this wrong. First, here is the completed original example:
```python
from typing import TypeVar
T = TypeVar("T")

class Meta(type):
    some_msg: str
    def create(cls: Type[T]) -> T:
        print(cls.some_msg)
        return cls()

class Cls(metaclass=Meta):
    pass
foo = Cls.create() # inferred type should be Cls
```
By using your solution instead for `create`, `foo` is inferred to be a type (an instance of `Meta`) instead of an instance of `Cls`.
By the way, Mypy doesn't complain about the line `return cls()` returning `T` with `cls: T` but it maybe should do so (because calling a type should return an instance of the type) and your solution would be refused by Mypy.

**Comment by gvanrossum** [comment]
Okay, I admit I am not sure what you are trying to accomplish. The code above doesn't run, as Cls has no attribute some_msg. I'm sure you have a specific example in mind -- would you mind explaining it?

**Comment by wyfo** [comment]
Indeed, my example doesn't work because I've not fill `some_msg` because I've only been worried about typing ; if you put `some_msg: str = "my message"`, the code does run, and `Cls.create()` print `my_message` before returning a `Cls` instance.
I can give you my specific example, but again, I know that it's a niche issue.
In my framework, I have a metaclass used as a global configuration manager : 
```python
from collections import Mapping
from typing import Any, Type, TypeVar
T = TypeVar("T")
class MetaConfig(type):
    @property
    def get(cls: Type[T]) -> T:
        try:
            return cls._loaded # Mypy: "Type[T]" has no attribute "_loaded"
        except AttributeError:
            raise RuntimeError("Configuration is not loaded")
    def load(cls: Type[T], config: Mapping[str, Any]):
        cls._loaded = from_data(config, cls)
def from_data(data: Any, cls: Type[T]) -> T: … # this is a stub of my lib

# In another file
from dataclasses import dataclass, field
@dataclass
class Configuration(metaclass=MetaConfig):
   some_ids: Collection[str]

# Anywhere else
# from ... import Configuration
def my_endpoint(id: str):
    if id in Configuration.get.some_ids: # `Configuration.get` is inferred as an instance of `Configuration`
        ...
```
With this (too long) example, I've realized that if I wanted my `MetaConfig.get` property to return an instance of the class `cls`, I had to loose the information of `cls` being an instance `MetaConfig`.
(Of course, in my case I could simply replace my metaclass by a simple class with some classmethods (and I did so, because Pycharm was buggy about inferred my property))

**Comment by esoma** [comment]
I just asked about this here: https://discuss.python.org/t/metaclasses-and-typing/6983

In my case I'm using `__await__` and `__or__` so I can't use class methods in the "actual" class I expose.

This is what I'm doing to work around it:

```python
from typing import Generator, Generic, Tuple, Type, TypeVar, Union

T = TypeVar('T')


class Future(Generic[T]): ...


class EventType(type):

    def __await__(cls: Type[T]) -> Generator[Future[T], None, T]: ...

    def __or__(cls: Type[MT], other: Type[ET]) -> OrEvents[Union[MT, ET]]: ... # type: ignore


class Event(metaclass=EventType): ...

MT = TypeVar('MT', bound=Event)
ET = TypeVar('ET', bound=Event)


class OrEvents(Generic[MT]):

    def __init__(self, events: Tuple[Type[MT], ...]) -> None: ...

    def __await__(self) -> Generator[Future[MT], None, MT]: ...

    def __or__(self, other: Type[ET]) -> OrEvents[Union[MT, ET]]: ...

````

Which let's me do:
```python
class Ping(Event): ...
class Pong(Event): ...
class Oops(Event): ...

async def _() -> None:
    reveal_type(await Ping) # Revealed type is 'main.Ping*'
    reveal_type(await (Ping | Pong | Oops)) # Revealed type is 'Union[main.Ping, main.Pong, main.Oops*]'
```

This works (at least in mypy), but it isn't *really* working. Everything is fine from the public API perspective, but internally there are all kinds of errors that I ignore because of some hacks (`EventType's` `__or__` for example actually uses `TypeVars` that are bound to `Event` -- it *works* because I only use `EventType` with `Event` and don't expose `EventType`, but it's certainly not *correct*).

**Comment by srittau** [comment]
Using a bound type var should work. If it doesn't that seems like a bug/missing feature to me in the type checker.
