### ISSUE TITLE
No straightforward way to get repr of Optional

### ISSUE THREAD

**Issue by Endilll** [python/typing#717]
What we're currently left with is `typing.Union[T, NoneType]` when source code is not available, which is noisy compared to `typing.Optional[T]`.

### Usecase

Consider the following: C++ library has C++ plugins, supplied by user. It provides Python wrappers for their functions, dynamically filling out their type annotations.

User asks his favorite autocompletion engine for signature of one of the wrapped functions, and all it has to generate nice human-readable string is a bunch of `typing` objects without any source code they've been generated from.

### Workaround

Of course it's possible to do some string replacements downstream, like I did in [this Jedi PR](https://github.com/davidhalter/jedi/pull/1441), but I wonder if `typing` can enable us to achieve this in a clean way.

**Comment by gvanrossum** [comment]
I suppose you could submit a PR to the CPython project to improve the repr of Unions. Is that what you are looking for?

**Comment by Endilll** [comment]
Yes.
Should I recreate this issue on bugs.python.org in order to get `bpo` number as PR template asks? But seeing a "GitHub PR" field in issue creating form there make me feel kind of stuck in a loop.

**Comment by gvanrossum** [comment]
You can create the issue and the PR in either order, and linK them later.
-- 
--Guido (mobile)

**Comment by Endilll** [comment]
Resubmitted to [bpo](https://bugs.python.org/issue40389).
Thank you.
