### ISSUE TITLE
Add `SupportsIndex` to `typing_extensions`

### ISSUE THREAD

**Issue by srittau** [python/typing#723]
Cf python/typeshed#3974.

**Comment by gvanrossum** [comment]
Can you clarify? I don’t understand the issue you link.

**Comment by JelleZijlstra** [comment]
`typing.SupportsIndex` was added only in 3.8 (https://docs.python.org/3/library/typing.html#typing.SupportsIndex), but the concept of `__index__` is much older, so we should put the ABC in `typing_extensions` so that it can be used on older versions of Python.

**Comment by gvanrossum** [comment]
Okay, fair. Just di it, I guess.
