### ISSUE TITLE
Exploring the validity of adding typings to general namespace

### ISSUE THREAD

**Issue by mahmoudajawad** [python/typing#726]
Using type-hinting is becoming the norm in python community. in fact, it is helping driving the development process of the different projects in better direction.

That said, I wanted to hear from the squad steering python development process about the validity of adding the popular typings, such as 'Dict, List, Any, ..etc', to the general namespace, without requiring importing them. I understand this is a breaking change to those using the same naming schemes, so here's my suggestion to explore:

* Plan adding the typings to the language without requiring developers to import them to upcoming python 3.9 which flags enough time to current developers to update conflicting naming scheme.
* For current python 3.8, add a CLI arg/param to get the typings available without needing to import them, such as running python with `-t` arg/param from typing (not to confuse python 2.x `-t` warning for mixed indention style).
* This will keep current project safe, while giving developers who are planning to annotate-all-things having the access to typings without manually importing them every time.

I have to say, this looks to me like a common-sense matter, and not having it means I'm missing some part of the puzzle, and for that this is more of a request to understand the limitation of not being able to implement this.

**Comment by srittau** [comment]
@mahmoudajawad You might be interested in [PEP 585](https://www.python.org/dev/peps/pep-0585/), coming in Python 3.9. This will make `Tuple`, `List`, `Dict`, `Set`, `FrozenSet`, and `Type` obsolete and it will be possible to write e.g. `list[str]`. No import necessary. Other imports from `typing`, like `Any` will still be necessary, though.

**Comment by mahmoudajawad** [comment]
I see. I missed this one. It's already accepted as I can see, which is great moving forward, however still disappointing to see the type-hinting style is changing rapidly, but that's not totally bad after all. I would like to hear more about the convention this PEP would bring to having `Any` as non-generic--Will we be able to request introducing `Any` as generic proxy to `object` so that we keep the PEP intact?

**Comment by ethanhs** [comment]
We can't (and IMO should not) make `List`, `Dict`, etc in the default namespace, because we do not want to clutter it. PEP 585 is what typing was supposed to end up looking like, but these types had to develop in `typing`.

The cutoff for changes in 3.9 has passed (the beta was released a few days ago) but they could be made for 3.10. But I also think PEP 585 removes a  lot of the work needed for importing from typing.

Also, why should `Any` be generic? I don't think that makes sense to me.

**Comment by mahmoudajawad** [comment]
To drop the necessity to make any imports at all when using type-hinting.

**Comment by gvanrossum** [comment]
> That said, I wanted to hear from the squad steering python development process about the validity of adding the popular typings, such as 'Dict, List, Any, ..etc', to the general namespace, without requiring importing them. I understand this is a breaking change to those using the same naming schemes,

And there your proposal dies. We're not going to introduce breaking changes. I have a feeling you're out of your depth regarding the rules for Python compatibility.

> so here's my suggestion to explore:
> 
>     * Plan adding the typings to the language without requiring developers to import them to upcoming python 3.9 which flags enough time to current developers to update conflicting naming scheme.

As Ethan says, per PEP 585 we're going to switch to lowercase `list`, `dict` etc., and this is already implemented in 3.9b1.

>     * For current python 3.8, add a CLI arg/param to get the typings available without needing to import them, such as running python with `-t` arg/param from typing (not to confuse python 2.x `-t` warning for mixed indention style).

Changing Python 3.8 is also off the table.

>     * This will keep current project safe, while giving developers who are planning to annotate-all-things having the access to typings without manually importing them every time.

It's too bad that you have to import those things, but there's no way we can change this now. Your best bet is to write `from typing import *` -- this may displease some linters but it is much more benign than the changes you are proposing.
 
> I have to say, this looks to me like a common-sense matter, and not having it means I'm missing some part of the puzzle, and for that this is more of a request to understand the limitation of not being able to implement this.

The piece of the puzzle you seem to be missing is that Python has millions of users and there are billions of lines of Python code in the world that we cannot afford to break.

I will close your issue; if you need more explanation of why your proposal cannot be implemented, please ask on python-list.
