### ISSUE TITLE
`typing` should have a single-method protocol for`__lt__`

### ISSUE THREAD

**Issue by ramalho** [python/typing#728]
On `typeshed` there are several issues that can be fixed with a protocol like this:

```
class _Sortable(Protocol):
        def __lt__(self, other) -> bool: ...
_SortableT = TypeVar("_SortableT", bound=_Sortable)
```

That protocol is already defined _ad hoc_ in [`statistics.pyi`](https://github.com/python/typeshed/blob/6575bd06bb8c8f3f0a45f878e5766be57beb939e/stdlib/3/statistics.pyi#L12), to solve a couple of cases there, but it can also be used in `builtins.pyi` for `max()`, `min()` `sorted()`, `list.sort()` or any other function that depends on sorting items to do its job.

For many user-defined functions that use one of these functions internally, a protocol like `_Sortable` is needed to provide accurate type hints. That's the case of `statistics.median_high` and `median_low`: the use cases that prompted the definition of `_Sortable` in `statistics.pyi`.

I'm not sure what its name should be. A few options:

- `Sortable` is OK by me.
- PEP 484 has an [example](https://www.python.org/dev/peps/pep-0484/#type-variables-with-an-upper-bound) ABC named `Comparable` that defines `__lt__`—but the text suggests the other comparison operators would be part of that ABC.
- `typing` has a bunch of `SupportsXyz` protocols, so maybe `SupportsLessThan`?

**Comment by srittau** [comment]
See also python/typeshed#4131 for a suggestion to add such protocols to typeshed for now and then possibly transferring them to typing if they prove to be used.

**Comment by gvanrossum** [comment]
This should probably be an issue (and preferably a PR) for typeshed.
