### ISSUE TITLE
Type variable based on type variable for another generic

### ISSUE THREAD

**Issue by barisione** [python/typing#736]
I cannot find a way to specify a type based on the type used by another `Generic`.
I'm not even sure what this concept is called, but looking at the docs for mypy and typing I could find out how to express this:

```
#! /usr/bin/env python3

from typing import Generic, TypeVar


StoredT = TypeVar("StoredT")
InnerBoxT = TypeVar("InnerBoxT", bound="InnerBox")


class OuterBox(Generic[InnerBoxT]):
    def __init__(self, inner: InnerBoxT) -> None:
        self.inner = inner

    def get_value(self) -> StoredT:
        return self.inner.value


class InnerBox(Generic[StoredT]):
    def __init__(self, value: StoredT):
        self.value = value


def main() -> None:
    value_before = 42
    inner = InnerBox(value_before)
    outer = OuterBox(inner)

    # mypy cannot guess the type for value_after but, if outer.inner.value were accessed directly,
    # it could.
    value_after = outer.get_value()
    value_after.should_not_work()  # No complaints about this method not existing on ints.


if __name__ == "__main__":
    main()
```

The code above is extremely simplified to the point of being silly, but it looks like there should be a way to say (inside `OuterBox`'s definition) that `StoredT` is the type used by `InnerBox`.
I know the same end result can be achieved by having `class OuterBox(Generic[InnerBoxT, StoredT]): ...` and then specify `outer = OuterBox[InnerBox, int](inner)` but, to me, it looks like that's the wrong place where to do it.
Is this possible in any way? If not, does it make sense for it to be possible?

If it helps, my use case is a more complicated version of the above where `StoredT` is `TypeVar(..., bound=SomeClass)`. `Outer` deals with several instances of `SomeClass` (or a derived type), but doesn't care about the type, apart from what's offered by the base `SomeClass` class.
On the other hand, the calling code needs to access all the methods provided by the classes derived by `SomeClass`.

**Comment by suutari** [comment]
Can you just use StoredT as the generic argument for the OuterBox and then defining the type references to InnerBox some other way, e.g. a protocol?

Something like this:
```python
class HasValue(Protocol[T]):
    @property
    def value(self) -> T: ...


class OuterBox(Generic[StoredT]):
    def __init__(self, inner: HasValue[StoredT]):
        self.inner = inner

    def get_value(self) -> StoredT:
        return self.inner.value
```

Don't know if that'll affect the relevance of the original question, but maybe it could at least solve the problem at hand?

**Comment by barisione** [comment]
@suutari It doesn't work in my original, and more complicated, code.
In the real code `OuterBox` doesn't know anything about the stored type and it really treats it as an opaque object.
But the opaque objects gets returned by `OuterBox` to the user which needs to get the correct type.

**Comment by suutari** [comment]
> In the real code OuterBox doesn't know anything about the stored type and it really treats it as an opaque object.

This wasn't true in your example, since in the example OuterBox clearly knew that the stored object `inner` has a property named `value` which returns `StoredT`. That was the info that I tried to encapsulate to the HasValue protocol.

> But the opaque objects gets returned by OuterBox to the user which needs to get the correct type.

When you say that the object is opaque to the OuterBox, I understand it as that you make no expectations about its details at all. Which would look something like this then:
```python
class OuterBox(Generic[T]):
    def __init__(self, inner: T):
        self.inner = inner

    def get_value(self) -> T:
        return self.inner
```

So it would be a very basic templated container.

I'm afraid that I don't understand your problem anymore, unless you provide a more complete example.

**Comment by jp-larose** [comment]
Because `InnerBox` is itself a `Generic`, it should be used as such.

The revised code below gives you the results you're looking for from mypy:

```python
from __future__ import annotations
from typing import Generic, TypeVar


StoredT = TypeVar("StoredT")
# InnerBoxT = TypeVar("InnerBoxT", bound="InnerBox")


class OuterBox(Generic[StoredT]):
    def __init__(self, inner: InnerBox[StoredT]) -> None:
        self.inner = inner

    def get_value(self) -> StoredT:
        return self.inner.value


class InnerBox(Generic[StoredT]):
    def __init__(self, value: StoredT):
        self.value = value


def main() -> None:
    value_before = 42
    inner = InnerBox(value_before)
    outer = OuterBox(inner)

    # mypy cannot guess the type for value_after but, if outer.inner.value were accessed directly,
    # it could.
    value_after = outer.get_value()
    value_after.should_not_work()  # No complaints about this method not existing on ints.


if __name__ == "__main__":
    main()
```

**Comment by srittau** [comment]
I think this is resolved. If there are still questions, please use our [discussions](https://github.com/python/typing/discussions).
