### ISSUE TITLE
py3 whl for 3.7.4.2 ?

### ISSUE THREAD

**Issue by jywu-msft** [python/typing#738]
the pypi release for 3.7.4.2 seems to be missing the py3 whl? 
https://pypi.org/project/typing/#files

**Comment by gvanrossum** [comment]
That’s because it only works on Python 3.4, and I could not find a way to build a 3.4 wheel. If you have 3.4, pip should install from source does it not?

**Comment by hariharans29** [comment]
Hi @gvanrossum,

We have a Python 3.5 environment and it seems like there was a commit (https://github.com/python/typing/commit/c85016137eab6d0784b76252460235638087f468) that explicitly disallows installing the latest package on Python 3.5+ that is part of the latest release 3.7.4.2. I understand that `typing` is part of the Python stdlib from 3.5 and onwards. But, for some reasons we need to build a package for a legacy release which has `typing` as a dependency (https://github.com/onnx/onnx/blob/5af210ca8a1c73aa6bae8754c9346ec54d0a756e/setup.py#L285) and it doesn't have the `python_version < "3.5"` portion and so building the legacy release of that package on python 3.5 results in a break. Is there anything we can do without adding that portion (or pinning the typing version) and patching the legacy release ?

Thanks!

**Comment by gvanrossum** [comment]
You could pin typing to version 3.7.4.1.
