### ISSUE TITLE
Cant create a NewType from a subscriptable type

### ISSUE THREAD

**Issue by nhumrich** [python/typing#740]
I am trying to create a unique type, which is mostly just an alias for `Optional`. 
Typically, this is done with `NewType`. For example:

```python
MyType = typing.NewType('MyType', str)
```

But, this does not work on subscript-able types, because it causes a type error while python is parsing the code:
```python
MyType = typing.NewType('MyType', typing.Optional)
a: MyType[str] = 'cabbages'
```
produces:
> TypeError: 'function' object is not subscriptable

because MyType is actually a function. `<function NewType.<locals>.new_type at 0xXXXXXXXXXXX>`

Should `NewType` work for aliasing subscript able types? 

--- 
I have also tried the below, which also doesn't work, for a completely different reason.
```
K = typing.TypeVar('K')
class MyType(Optional[K]):
    pass
# TypeError: Cannot subclass <class 'typing._SpecialForm'>

**Comment by gvanrossum** [comment]
You can't do that, for several reasons. First `Optional` is not a type, it's a special form (PEP 484 couldn't introduce special syntax, so instead it introduced a few special forms). Second, `NewType` cannot be used to define generic types. So you're just going to have to spell `Optional` as, well, `Optional`. :-)
