### ISSUE TITLE
Please bump setup.py when tagging releases

### ISSUE THREAD

**Issue by alucryd** [python/typing#741]
Hi guys, could you please make sure you always bump setup.py when tagging releases? It's been really hit or miss with this repo, and when it's miss it's really annoying for packagers. Thanks in advance :)

**Comment by gvanrossum** [comment]
I apologize for releasing 3.7.4.3 with the wrong version number. It was released under less than ideal circumstances. Has this happened before? Is it necessary to release 3.7.4.4 just so the version munger matches the tag?

**Comment by alucryd** [comment]
Yes it has, and I understand the circumstances so it's okay really. I just thought I should bring it up because most people probably use pypi so it's not an issue for them, but for distros who package directly from github it does make our job a little bit harder.

Please don't go out of your way to create a new release, it's already fixed on our end. I'll just remove the fix with the next release.

**Comment by gvanrossum** [comment]
Hm, I realize something else happened. I did bump the version in my local repo but I never pushed the commit to GitHub! It seems `git push --tags` doesn't work the way I thought it worked (it seems to push the tags but not the commits?). Anyway I've pushed the commit I used to build the 3.7.4.3 release for PyPI, so you shouldn't need your workaround any more.

**Comment by alucryd** [comment]
Thanks a lot!
