### ISSUE TITLE
zip() parameters typing information is lost?

### ISSUE THREAD

**Issue by kalessin** [python/typing#744]
If I have:

```
f: Tuple[Tuple[str, float], ...] = zip(('bla', 'ble', 'blo'), (5.0, 6.0, 7.0))
```
type checking gives error:

_Incompatible types in assignment (expression has type "Tuple[Tuple[object, ...], Tuple[object, ...], Tuple[object, ...]]", variable has type "Tuple[Tuple[str, float], ...]")_

is this a problem with python or with mypy?

**Comment by gvanrossum** [comment]
With mypy, if it is a problem.

What does reveal_type(zip(...)) say?

**Comment by kalessin** [comment]
Nevermind, I just found that annotating both tuples, the issue becomes fixed.

Sorry.

**Comment by gvanrossum** [comment]
Maybe this will be easier when we have PEP 612.
