### ISSUE TITLE
[Feature request] Include typing type variables in public API

### ISSUE THREAD

**Issue by NiklasRosenstein** [python/typing#745]
**Type**: Feature Request  

```py
from typing import KT, T, T_co
```

If all you need is a `T` type variable, you have to import `TypeVar` and create a new instance. However the `typing` module already declares common type variables that could be re-used in many cases, but they are not part of the public API (according to `typing.__all__`).

This is a feature request to include the type variables defined in the `typing` module in `typing.__all__`, which will ultimately allow importing these type variables without adding `# type: ignore` if the code is checked with Mypy.

**Comment by gvanrossum** [comment]
I'm not in favor of this. I worry that typing newbies would start assuming that the only type variables in existence are those exported by `typing`, and we'd get requests to add `S`, `R`, or whatever. Also, `KT` and `T_co` are pretty arbitrary.

**Comment by JelleZijlstra** [comment]
I agree. It's also not that much work (just one line) to define a typevar yourself.

And if you want, you can build a pypi package yourself that exposes useful typevars.
