### ISSUE TITLE
Support anonymous duck-typing

### ISSUE THREAD

**Issue by ktbarrett** [python/typing#747]
Protocols were introduced in PEP 544 to support structural subtyping; however they were very much designed with ABCs in mind: they must be named, defined ahead of time, and represent abstract concepts or interfaces. This observation is reinforced by the fact the main use of Protocols in the standard library is in the typing module for defining ABCs.

This is fairly limiting in my opinion, many uses of duck-typing in Python don't involve well defined concepts that are defined ahead of time, but are totally anonymous. The fact one can only define them ahead of time and must name them is actually a detriment:

* additional names in the namespace
* type annotations rendered with Sphinx link to the Protocol class and not the expected type
* additional programming effort to write out those Protocols
* probable code duplication (once in the expected type, and again in the Protocol class)

This seems *very unpythonic*. If your wish is to support duck typing on a lot of your interfaces, you are in for a rough day. For an example, see below. Now imagine writing a dozen non-trivial implementations.

```python
class ExampleProtocol(Protocol):
    a: int
    b: str
    c: Any


@dataclass
class Example(ExampleProtocol):
    a: int
    b: str
    c: Any


def uses_examples(example: ExampleProtocol) -> None:
    pass
```

Alternatively, I'd like a syntax to describe that I would accept any type that is interface compatible with an expected type. Essentially, a structural type checking "switch" for a given variable. Instead of nominal checking objects passed to these interfaces, they would check for structural compatibility only. Much like Protocol, but without the code overhead.

```python
@dataclass
class Example:
    a: int
    b: str
    c: Any


def uses_examples(example: Interface[Example]) -> None:
    pass
```

This is a mock-up, not a suggestion, I have no idea how typing objects or static type checkers are implemented, so there might be a better way.

My need for this feature is located in [this stackoverflow question](https://stackoverflow.com/questions/63479642/reduce-overhead-induced-by-using-protocols-for-structural-type-checking?noredirect=1#comment112251291_63479642), which got a lot of attention :roll_eyes:.

**Comment by gvanrossum** [comment]
Please lay off the rhetoric.

That said, it seems you want a way to implicitly define a protocol that is "like" a given concrete class. That's not unreasonable, as long as you are willing to live with the consequences -- the derived protocol will have *all* attributes and methods of the concrete class.

I would propose to call this `Like`, so your example would use `Like[Example]`. (The thing called "Interface" that I believe exists in some other languages is more like the existing `Protocol` class.)

I believe introducing Protocol was a significant amount of work. I am guessing that this new feature could build upon that work, but it does not look like an simple feature to implement, so the best I can say is "duly noted". There are a lot of other things that haven't been implemented in any type checkers yet. (For example, mypy is still waiting for recursive type aliases, which are much more fundamental, in the sense that you can't express those *at all* currently, while you can do your job just fine as long as you're willing to write everything twice. :-)

**Comment by ktbarrett** [comment]
After some thought I realized that maybe this wasn't as useful, generally, as I has hoped. "Like" types must be supersets of the original type, which is fairly limiting outside of my use case of moving related datclasses or maybe mock objects around. Protocols allow you to name a set of requirements that are narrower than some type's interface. It does the job, it's just not super expressive.

**Comment by gvanrossum** [comment]
So I'll close this issue, we already have enough unlikely ideas. If you disagree please just ping the issue.
