### ISSUE TITLE
`SupportsIndex` missing from the 3.7.4.2 pypi release

### ISSUE THREAD

**Issue by BvB93** [python/typing#749]
The [3.7.4.2](https://github.com/python/typing/releases/tag/3.7.4.2) release of typing-extenions here on GitHub added, among other things, a backport of the `SupportsIndex` protocol, yet the same protocol appears to be absent from the [3.7.4.2](https://pypi.org/project/typing-extensions/3.7.4.2/) pypi release (see example).
Any idea what could be going here?

Examples
---------
``` shell
conda create -n test python=3.7
conda activate test
pip install typing-extensions==3.7.4.2
```
``` python
>>> from typing_extensions import SupportsIndex
Traceback (most recent call last):
  ...
ImportError: cannot import name 'SupportsIndex' from 'typing_extensions'
```

**Comment by gvanrossum** [comment]
I've done said release, see https://pypi.org/project/typing-extensions/3.7.4.3/

Please test with all Python versions and all platforms you have available (I rested 2.7 and 3.7 on MacOS).

Is there a way to disable GitHub releases? That's just not how we distribute things.

**Comment by BvB93** [comment]
Thanks Guido, some local testing (windows 3.7) suggests that everything works fine now.

I'm a bit confused though about your question regarding GitHub releases; aren't those created manually?

**Comment by gvanrossum** [comment]
I think they are automatically created when a tag is pushed? I don't recall ever creating a GitHub release, and yet there are 14 of them, one for every tag we've ever pushed. I think those are just zips of everything in the repo. Please ignore them.

**Comment by BvB93** [comment]
> I think those are just zips of everything in the repo. Please ignore them.

Good to know; I'll bear this in mind for in the future.
