### ISSUE TITLE
Syntactic Sugar for typing e.g. Union using __or__  ( | symbol)

### ISSUE THREAD

**Issue by jp-larose** [python/typing#750]
I had a thought about reducing the verbosity of the type hints.  Could we add some operators on types and `typing` classes to present a cleaner syntax for type hints?

For example:
- `str | int` would resolve to `Union[str, int]`
- `~str` would resolve to `Optional[str]` (which in turn is shorthand for `Union[str, None]`)

This could be done by defining `__or__` and `__invert__` on `type` and other typing related classes to return a `Union` 

With no optimization longer type groups would follow something like this:
- `~str | int | ArbitraryClass | Type[SomeOtherClass]`
  - = `Union[Optional[str], Union[int, Union[ArbitraryClass, Union[Type[SomeOtherClass]]]`
  - which eventually flattens to `Union[str, None, int, ArbitraryClass, Type[SomeOtherClass]]`

But to me, the syntax with | and ~ seems cleaner.  I imagine there could be something that the interpreter can do to optimize the flow (perhaps this is a similar situation to how `a < b < c` is handled to mean `a < b and b < c`?)

`|` to me is a natural choice for grouping types like this for a few reasons:
- `var: str | int | complex` literally reads as "`var` is of type `str` or `int` or `complex`"
- Use of `|` has already been extended to `set` and `dict` to return a combination of their contents.
- On a similar vein, `Union` essentially represents a *set* of types (complete with ignoring duplicate types)

`~` for `Optional` maybe a less obvious choice.  My first inclination would be to use `?`, but I didn't want to introduce a new symbol to the language.
- Of the three unary operators, `~` seems the most invoking of the idea of Optional.  I've often seen (and used) ~ when writing notes (esp. in Math) to mean "approximately".

I haven't put much thought on other ways to reduce the visual clutter of complex type hints.  Certainly `Callable` could use some sort of shorthand!  Maybe `Literal` could too.

Quick ideas as I look through the `typing` library:
- Maybe use unary `+` for `ClassVar[T]` (e.g. inside a class: `var: +int` would translate to `var: ClassVar[int]`)
- Maybe use unary `-` for `Final[T]` (e.g. `SOME_CONST: -str = 'hello'` would translate to `SOME_CONST: Final[str] = 'hello'`)

These last few ideas are thrown in more as "Let's see what else we can do!" more than actual things I want to see.

**Comment by gvanrossum** [comment]
PEP 604 introduces '|' already. We looked into '~' for Optional but decided against it, in favor of e.g. 'int|None'. The others haven't earned their chops, it's too early to provide more syntactic sugar.
