### ISSUE TITLE
how to get 'module' of `TypeVar` ?

### ISSUE THREAD

**Issue by devdoomari3** [python/typing#754]
Hello!

I'm currently working on [py_type_extractor](https://github.com/pycodegen/python-type-extractor) for getting TypeNode-ASTs at runtime (it's a py3.6+ compat-layer for codegens / runtime-type-validations / etc)

While working on the project, I couldn't get the module (or module name) of `TypeVar`s, unlike classses/functions/etc.

Is there simply no way to get 'module' of `TypeVar`s?

here's some code-examples to show what I'm hoping to extract from `TypeVar`s:

1. Source file
```python
# --------  {proj_root}/packageA/packageB/some_file.py file  --------

from typing import TypeVar, Generic

SomeTypeVarA = TypeVar('SomeTypeVarA')
...
```

2. Extractor
```python

# --------  extract_typevar.py  --------
from packageA.packageB.some_file import (
    SomeTypeVarA
)

# how to access module (or module name) of SomeTypeVarA ?
SomeTypeVarA.__module__  # points to some python-typing internals 😭 

# what I'm hoping to get:
get_module_from_typevar(SomeTypeVarA) == 'packageA.packageB.some_file'
```

Thank you!

**Comment by gvanrossum** [comment]
Sorry, there is no way.
