### ISSUE TITLE
Json type object in Python

### ISSUE THREAD

**Issue by hassanahmed95** [python/typing#755]
I have a dictionary, I converted it to a JSON object using:
`myJsonObject = json.dumps(myDictionary) `

But then If I check the type, I got `<type 'str'>`, although it is in json format, but data type is str.

How can I get the data type as Json. I know there is method  `json.loads(str)` can be utilized, but that method returns the data type as  <type dict>.

How can I get the the data type as json in python?

**Comment by gvanrossum** [comment]
Please ask on Gitter.
