### ISSUE TITLE
Backport PEP 593's `Annotated`

### ISSUE THREAD

**Issue by FFY00** [python/typing#756]
Hi! I think PEP 593 is a major improvement to the Python type system (thanks!) and was wondering if it was possible to backport `Annotated` in `typing_extensions`. I have a project that could really benefit from this (https://github.com/FFY00/dbus-objects) and would hate to have a requirement on Python 3.9.

I can work on this if needed, please let me know.

Again, many thanks :blush:

**Comment by gvanrossum** [comment]
It is already backported in `typing_extensions`: https://github.com/python/typing/blob/95d6776c0d07e7b096ca153ed6c5b1b30db738e1/typing_extensions/src_py3/typing_extensions.py#L1740

**Comment by FFY00** [comment]
Oh, my bad!
