### ISSUE TITLE
how to get 'module' of `NewType`?

### ISSUE THREAD

**Issue by devdoomari3** [python/typing#757]
is there a way to get module of a `NewType`?

example:

```
# -------- packageA/packageB/some_file.py file  --------

from typing import NewType, AnyStr

ValidatedEmail = NewType('ValidatedEmail', AnyStr)
...

    Extractor

# --------  extract_newtype.py  --------
from packageA.packageB.some_file import (
    ValidatedEmail
)

# how to access module (or module name) of SomeTypeVarA ?
ValidatedEmail.__module__  # points to 'typing'

# what I'm hoping to get:
get_module_from_typevar(ValidatedEmail) == 'packageA.packageB.some_file'
```

**Comment by gvanrossum** [comment]
There is no way, and this is not a desirable use case. (Also, you're using the term "typevar" wrong. :-)

**Comment by devdoomari3** [comment]
sorry for being sloppy ( the 'typevars' in the above example are the result of [copy-pasta](https://github.com/python/typing/issues/754)...)

my actual use case for `module` is for "generating Typescript-interface code with python project structure *nearly* intact" \
(so a `ValidatedEmail` inside `py_proj/types/user.py` will result in a nominal-type in `generated_ts_proj/types/user.ts` file)

-------
Anyway, for `there's no way`, do you mean:

1. it can't be backported ( can't do `pip install -U typing`, so this will require newer python version (py3.11+?)
2. current typing project isn't designed for this (impossible / may take big overhaul)

[in some related discussion](https://github.com/davidhalter/jedi/issues/1652#issuecomment-674493868) from other repo, there's mention of "we can probably backport..." --- is this even possible? \
(maybe they're thinking of monkey-patching the `typing` module before everything else runs?)

I'm not actually a python-person, so I'm not very familiar with the python-internals 😭

**Comment by gvanrossum** [comment]
I meant (2) it’s infeasible to add this.--
--Guido (mobile)
