### ISSUE TITLE
TypedDict(...) as function does not respect "total" when setting __required_keys__ and __optional_keys__

### ISSUE THREAD

**Issue by agronholm** [python/typing#761]
Issue on Python bug tracker: https://bugs.python.org/issue42059

**Comment by domdfcoding** [comment]
The fix has now been merged in CPython. The relevant lines that would need changing in typing_extensions are 1646 and 1654:

https://github.com/python/typing/blob/b5c0b6d66b3adba4dde3f4f4145ce83a70fd03f7/typing_extensions/src_py3/typing_extensions.py#L1645-L1654

**Comment by gvanrossum** [comment]
Do you think you can submit a PR for that?
