### ISSUE TITLE
3.9: can we add __weakref__ to `types.GenericAlias`?

### ISSUE THREAD

**Issue by Tinche** [python/typing#764]
Hi, it's me again.

This is very similar to https://github.com/python/typing/issues/345. I can't use singledispatch with the new 3.9 collection generics (`list[int]`, `dict[str, int]`) since they don't support weak references. Could we add them?

The error message mentions `*types*.GenericAlias`, not `typing`, so I don't know where this report should go exactly.

**Comment by gvanrossum** [comment]
This needs to be fixed in CPython, so can you please open an issue on bugs.python.org and close this one?

**Comment by Tinche** [comment]
Done: https://bugs.python.org/issue42332, added @gvanrossum to the nosy list
