### ISSUE TITLE
Support for shortening Union of Literals

### ISSUE THREAD

**Issue by sinback** [python/typing#765]
I have a bug that crops up when trying to do some runtime type inspection, which I bet every `typing` maintainer loves to support, right? 😀 

I'm using Python 3.9.0, although this first came to my attention when using the 3.7 typing_extensions backport as well.

PEP 586 describes two types of Literal equivalence. [One of them](https://www.python.org/dev/peps/pep-0586/#equivalence-of-two-literals) looks like this:
```
from typing import Literal

print(Literal[0] == Literal[1-1])
```
prints `True`. This makes sense to me - I would have assumed the "equivalence" spoken of in the PEP also applied to equality of the type hint itself (at runtime).

[The other type of equivalence](https://www.python.org/dev/peps/pep-0586/#shortening-unions-of-literals) looks like this:
```
from typing import Literal, Union

print(Literal['foo', 'bar'] == Union[Literal['foo'], Literal['bar']])
```
prints `False`!

I think I can work around this ok in my project, but I figured I would open an issue about it since it seems to me like a bug for two types that are supposed to be "equivalent" to not implement `__eq__` exactly as laid out in the PEP.

I am not familiar with the `typing` project source code but I have examined a bunch of the dunderfields and stuff for my aforementioned runtime library. Would this be a good first issue?

**Comment by gvanrossum** [comment]
I don't think that we should fix this. While `Literal['foo', 'bar']` and `Union[Literal['foo'], Literal['bar']]` are indeed equivalent, the objects used to implement them at runtime are quite different and I don't think we should try to bend over backwards to make them compare equal. After all, we do write "equivalent" and not "equal" -- these are subtly different concepts. I am sorry that this makes your application more complicated, but that's life.

**Comment by sinback** [comment]
I almost opened a different issue for this, but then I realized I'm pretty sure what I'm experiencing now is also due to the same internals as what caused this issue I already opened. Perhaps this case is more compelling?

I'd like to be able to make a list which is of type a Union of Literals, with members added to that list of those Literal types the list is a Union over, but the behavior is quite funky.

example.py:
```
from typing import NamedTuple, List, Union, Sequence

from typing_extensions import Literal

MyTypes = Literal['foo', 'bar']

class Example(NamedTuple):
    foo_only: Literal['foo'] = 'foo'
    bar_only: Literal['bar'] = 'bar'


if __name__ == '__main__':
    e = Example()

    okay_list: List[MyTypes] = [e.foo_only, e.bar_only]     # mypy likes this
    bad_list: List[MyTypes] = [e.foo_only] + [e.bar_only]   # mypy doesn't like this; it gives:
    # example.py:16: error: Incompatible types in assignment (expression has type "List[Literal['foo']]", variable has type "List[Union[Literal['foo'], Literal['bar']]]")
    # example.py:16: note: "List" is invariant -- see http://mypy.readthedocs.io/en/latest/common_issues.html#variance
    # example.py:16: note: Consider using "Sequence" instead, which is covariant
    # example.py:16: error: List item 0 has incompatible type "Literal['bar']"; expected "Literal['foo']"
    #
    # ...but Sequence isn't what I think we should need, nor does it even make mypy happier:
    suggested_sequence: Sequence[MyTypes] = [e.foo_only] + [e.bar_only]
    # still gives the concatenation complaint:
    # example.py:23: error: List item 0 has incompatible type "Literal['bar']"; expected "Literal['foo']"

    # right now I just work around this like this, but it isn't ideal in my more complicated use
    # case
    class ExampleButLessTypeSafe(NamedTuple):
        foo_or_bar: MyTypes = 'foo'
        bar_or_foo: MyTypes = 'bar'

    f = ExampleButLessTypeSafe()
    new_okay_list: List[MyTypes] = [f.foo_or_bar, f.bar_or_foo]
    another_new_okay_list: List[MyTypes] = [f.foo_or_bar] + [f.bar_or_foo]
```

**Comment by sinback** [comment]
^ Oh yeah, in the above case, the list comprehension `[x for x in e]` also does not work, which maybe makes sense I guess because of how list comprehensions unroll.

**Comment by sinback** [comment]
I noticed it's not too bad to "unroll" a Literal[foo, bar, ...] into a Union[Literal[foo], Literal[bar], ...] if you just pass its `__args__` into a Union. I haven't quite wrapped my head around the recursive case yet though. There's also handling of Optionals to do, which this snippet does not do on its own. I think such a representation would be usable in equivalence checks - I know it's just a start though but I'm just musing.

```
literals_extracted = tuple((_GenericAlias(Literal, t) for t in literal.__args__))
unionified = _GenericAlias(Union, literals_extracted)
```
