### ISSUE TITLE
ProtocolMeta not inheriting from abc.ABCMeta as outlined in the documentation

### ISSUE THREAD

**Issue by hamzamerzic** [python/typing#767]
When inheriting from a Protocol the methods get implemented with return None. Decorating Protocol methods with abc.abstractmethod should overcome this issue, but this raises:

Stray abc.abstractmethod decorator on method <method_name> [ignored-abstractmethod]

This fails with both:

```python
class Foo(typing_extensions.Protocol):

  @abc.abstractmethod
  def method_name(self) -> str:
    ...  
```
and explicitly inheriting from abc.ABCMeta:

```python
class Foo(typing_extensions.Protocol, metaclass=abc.ABCMeta):

  @abc.abstractmethod
  def method_name(self) -> str:
    ...  
```

The former should work as outlined in [PEP 544](https://www.python.org/dev/peps/pep-0544/#protocol-members).

Python version: 3.6.12.

**Comment by gvanrossum** [comment]
IIUC this error comes from pytype, right? It seems mypy has no problem with that code. Maybe you should report this in the pytype tracker? (CC: @rchen152)

**Comment by hamzamerzic** [comment]
Yes indeed its an issue with PyType. I think Recebecca already linked a fix for my use case. Thanks both!
