### ISSUE TITLE
python 3.10: 'typing-extensions>=3.6.4; python_version < "3.8"' distribution was not found and is required by importlib-metadata

### ISSUE THREAD

**Issue by williamjmorenor** [python/typing#771]
Running with current alpha version of python I get this error message:

pkg_resources.DistributionNotFound: The 'typing-extensions>=3.6.4; python_version < "3.8"' distribution was not found and is required by importlib-metadata

https://github.com/cacao-accounting/cacao-accounting/runs/1630729986?check_suite_focus=true

I think is related to this line:

https://github.com/cacao-accounting/cacao-accounting/blob/eba38d92e3af72c7cdffafc9b342c5707d4a903d/cacao_accounting/modulos.py#L131

**Comment by gvanrossum** [comment]
But that version exists on PyPI, and you shouldn’t be needing it with Python 3.10 alpha. I wonder if some setup script in your project is misfiring? I see nothing in *this* project that could be the cause of that.

**Comment by williamjmorenor** [comment]
Maybe it's a bad comparing versions thinking '3.10' < '3.8'

**Comment by gvanrossum** [comment]
Oh, good one! Not sure where to report that, but not here.
