### ISSUE TITLE
Inheriting from Generic causes inspect.signature to always return the signature of Generic

### ISSUE THREAD

**Issue by Andrew-Sheridan** [python/typing#772]
Happy 2021!

I noticed that inheriting from `Generic` causes `inspect.signature` to always return the signature of Generic, and not of the child class.

When using `inspect.signature` on a 'regular class, the signature is correct:
```python
import inspect 
 
class Foo: 
    def __init__(self, foo: str): 
        self.foo = foo 
 
inspect.signature(Foo)
# <Signature (foo: str)>
```

But if I create a Generic class, then it and its subclasses (and their subclasses etc) will always produce the signature of `Generic`:
```python
from typing import Generic

inspect.signature(Generic)                                                                                                              
# <Signature (*args, **kwds)>
```

```python
from typing import TypeVar 

T = TypeVar("T")                                                                                                                        

class Bar(Generic[T]): 
    def __init__(self, bar: T): 
        self.bar = bar

inspect.signature(Bar)
# <Signature (*args, **kwds)> 

class Snap(Bar[int]):
    def __init__*self, snap: int):
        self.snap = snap

inspect.signature(Snap)
# <Signature (*args, **kwds)> 
```

I'm not sure what's happening here. Am I doing something wrong? Is there a different method I should use to get the signature in this case?

Note: Getting the signature of `.__init__` _does_ work as expected:
```python

# control
inspect.signature(Foo.__init__)
# <Signature (self, foo: str)>

inspect.signature(Bar.__init__)
# <Signature (self, bar: ~T)>

inspect.signature(Snap.__init__)
# <Signature (self, snap: int)>
```

I tested this only in Python3.7 and 3.8.

**Comment by gvanrossum** [comment]
Please file this on bugs.python.org. It likely needs to be fixed in inspect. Also please check if it still occurs in Python 3.9.1. (Or, preferably, on master or 3.10a2.)

**Comment by Andrew-Sheridan** [comment]
@gvanrossum Thank you for your attention. I found https://bugs.python.org/issue40897 which tracks this. Looks like you already had eyes on it.

Thanks again :)

P.S. can confirm issue still present in 3.10a3
