### ISSUE TITLE
setup problem

### ISSUE THREAD

**Issue by timsoftgit** [python/typing#782]
from the source dir, running
`python2 setup.py install --root=$PKG`
`python3 setup.py install --root=$PKG`
where PKG contains a packaging path
installs the python2 files in the expected place, but then installs the python2 files in the python3 location, instead of installing the python3 files there. Previously these two lines worked. So I assume there is a regression in the setup.py file.
note: my system has python 3.7.2 and python 2.7.17 installed.

**Comment by JelleZijlstra** [comment]
I'm not sure this is a workflow we need to support. On Python 2 you should install typing through `pip`; on Python 3.7 you don't need to install it at all because it's in the standard library.

**Comment by timsoftgit** [comment]
I am using slackware, and to have python packages managed by the distro, they get installed to a package dir, then packaged so that they can be installed and managed by the distro package manager. 
typing-extensions is required by mypy even on python3.7.2

**Comment by timsoftgit** [comment]
the slackware package is built using https://slackbuilds.org/slackbuilds/14.2/python/typing-extensions/typing-extensions.SlackBuild
which has got broken with the latest version bump due to the change.

**Comment by timsoftgit** [comment]
it can be patched at our end, but obviously a vanilla upstream version is prefered.

**Comment by JelleZijlstra** [comment]
Oh sorry, I didn't realize you were talking about `typing_extensions` instead of `typing`. I suppose the relevant logic is https://github.com/python/typing/blob/master/typing_extensions/setup.py#L49, which hasn't changed in years.

**Comment by timsoftgit** [comment]
sorry yes, the issue tracker is the same for both. thats odd if setup.py hasn't changed. have you any suggestions?. one option is to extract the source each time before running python$x setup.py install --root=$PKG  where x is 2 then 3.  that works, but is less tidy.

**Comment by srittau** [comment]
This issue should be resolved, since the Python 2 files were removed.
