### ISSUE TITLE
`cast` type not preserved for instance variables 

### ISSUE THREAD

**Issue by Ashish-Bansal** [python/typing#783]
#### Description 

```python3
from typing import cast
from typing import Optional


def get_foo() -> Optional[int]:
    return 10


class Tests:
    def __init__(self) -> None:
        self.foo = get_foo()
        self.foo = cast(int, self.foo)

        x = self.foo + 10
        reveal_type(self.foo) # note: Revealed type is 'builtins.int'

    def test(self) -> None:
        x = self.foo + 10 # error: Unsupported operand types for + ("None" and "int")

        reveal_type(self.foo) # note: Revealed type is 'Union[builtins.int, None]'


tests = Tests()
tests.test()

```

^It's a trivial example. In the above code, using `cast` for `self.foo` works fine in the `__init__` but that information is not preserved for other member functions. 

Is it limited by the way `cast` works internally ?

**Comment by gvanrossum** [comment]
No, it’s not cast(). It’s because the first assignment sets the attribute type for the class. The subsequent assignment just narrows for the scope of the function.

To fix, use a local temporary.

**Comment by Ashish-Bansal** [comment]
@gvanrossum Thanks for the quick reply!

Is there a way to override the attribute type after the first assignment ? (Because even though local temporary variable would work in above example, but in a complex structure it would be a pain.)

**Comment by gvanrossum** [comment]
No, there isn’t — and I think in general it would be confusing if such a feature existed.

**Comment by Ashish-Bansal** [comment]
> No, there isn’t — and I think in general it would be confusing if such a feature existed.

Hm hm. Anyway, thanks for the help!
