### ISSUE TITLE
Python >3.6 is not restricted and causes accidently installation.

### ISSUE THREAD

**Issue by dciborow** [python/typing#785]
Other backport projects have pins in the setup.py that prevents this package from being installed with Python >3.6, please see an example here.
https://github.com/ericvsmith/dataclasses

The fix for this would be very simple, just add the same type of pin.

https://github.com/python/typing/pull/784

**Comment by dciborow** [comment]
I am not able to link this PR, but it has the fix for the issue.
I assume the conversation around this change may be larger then the update itself. 

https://github.com/ericvsmith/dataclasses

**Comment by Lawouach** [comment]
Hey project maintainers,

Is there a chance for a release with this change because it does mess up some installations on a very subtle ways.

Cheers

**Comment by gvanrossum** [comment]
I'm sorry, I am quite busy, and nobody else seems to be interested in
helping out either. So until that changes, you'll have to wait.

**Comment by Lawouach** [comment]
Hey Guido. No worries. I totally understand. If i can free up time next week I'll see if I could offer some help.

**Comment by JelleZijlstra** [comment]
Just released 3.10.0.0 with this change.

**Comment by Lawouach** [comment]
Thank you!
