### ISSUE TITLE
Add Annotated to typing_extensions

### ISSUE THREAD

**Issue by septatrix** [python/typing#789]
It feels like a great tool which I would like to use in older Python versions. Based on the documentation the does not seem to be a fundamental problem why it could not be included in that package.

**Comment by gvanrossum** [comment]
Sure, do you want to submit a PR? (We really need to do a release.)

**Comment by septatrix** [comment]
Well to my surprise it is actually already implemented but just not documented. I proposed a change to the readme in #790.
