### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by JelleZijlstra** [python/typing#799]
I'm hoping to cut a new release soon. Some details:

- I'd like to wait for #798 and the typing-extensions equivalent of python/cpython#25282 to make it in, so that we'll have parity with Python 3.10.0.
- I'll release both `typing` and `typing-extensions` under the same version because that seems to be tradition. We haven't had a lot of changes to `typing` recently (it's only relevant to people stuck on 2.7 or 3.4), but we should at least get #784 released.
- There is no documentation in the repo on the versioning schema, but I think the release should be called `3.10.0` to imply that it contains all the typing features that will be in Python 3.10.0. Later, if we do a release that fixes a bug but doesn't add new features, we'll call it `3.10.0.1`, but if we do a release that adds support for another new type system feature, we'll call it `3.11.0` (or whatever it ends up being). @gvanrossum is this right? I'll also add a note to the README explaining the versioning schema.

**Comment by gvanrossum** [comment]
I don’t think we’re trying semantic versioning, we should stick with 3.10.xxx until we’re tracking new typing features from Python 3.11. The rest sounds right.

THB I am actually worried that #784 might break some folks’ workflow, but I can’t think of how, so let’s release with that and then just watch for issues.

**Comment by JelleZijlstra** [comment]
I just released 3.10.0.0.

**Comment by domdfcoding** [comment]
😃 Thanks Jelle
