### ISSUE TITLE
isinstance check of runtime_checkable Protocol returns true for data-protocol if explicitly subclassed without non-method member

### ISSUE THREAD

**Issue by mwjohnson56** [python/typing#800]
Asked this question on [stackoverflow](https://stackoverflow.com/questions/67118186/why-do-explicit-protocols-in-python-not-require-attribute-implementation-for-ru) but I am copying here as this seems to be an untended results based on PEP 544. 

If a protocol is implemented with a requried attribute i.e. `name`

```
@runtime_checkable
class DuckProtocol(Protocol):
    """Protocol for a duck"""
    name: str
    @abstractmethod
    def quack(self):
        raise NotImplementedError
```

a runtime check of `isinstance` on an implicit subtype will fail if there is no `name` attribute, but an explicit one will not:

```
class Duck1(DuckProtocol):
    def quack(self):
        print('quack')
        
class Duck2:
    def quack(self):
        print('quack')

class Duck3:
    def __init__(self):
        self.name = 'duck3'
    def quack(self):
        print('quack')

print(isinstance(Duck1(), DuckProtocol))
print(isinstance(Duck2(), DuckProtocol))
print(isinstance(Duck3(), DuckProtocol))
```

Output

```
True
False
True
```

The issue seems to be caused by [`return super().__instancecheck__(instance)`](https://github.com/python/cpython/blob/1f2e3088f3c097b5bde69bbd63dfcd0852d31984/Lib/typing.py#L1113) in 
the `_ProtocolMeta` class. This points back to `_abc._abc_subclasscheck` which checks for a concrete subclass. Despite being an explicit subclass of a Protocol, if the class is not implementing all of the data-fields prescribed by the Protocol, it should not be considered an instance of the Protocol in the same way the implicit case is handled.

**Comment by gvanrossum** [comment]
Isn't this as expected? The 'name' attribute is not abstract. Also, please read PEP 544 -- perhaps it has something to say about this?

(Sorry for the non-answer, but I figure some pointers are better than nothing, and IIRC there are some issues with what you would propose as well -- e.g. what is a static type checker to do?)

**Comment by mwjohnson56** [comment]
In the PEP 544 section [@runtime_checkable decorator and narrowing types by isinstance()](https://www.python.org/dev/peps/pep-0544/#runtime-checkable-decorator-and-narrowing-types-by-isinstance), it states that a data-protocol contains at least one non-method member. The PEP also states in section [subtyping-relationships with other types](https://www.python.org/dev/peps/pep-0544/#subtyping-relationships-with-other-types)

>A concrete type X is a subtype of protocol P if and only if X implements all protocol members of P with compatible types. In other words, subtyping with respect to a protocol is always structural.

An explicit subclass of a data-protocol which does not implement all its non-method members does not meet this definition in the PEP, if an object of the child class attempts to called the attribute, an attribute error is thrown.

`AttributeError: 'Duck1' object has no attribute 'name'`

**Comment by gvanrossum** [comment]
The quoted section of the PEP is about what a static type checker would infer: if you explicitly inherit from the protocol, you inherit all the data attributes. In general a static checker cannot track whether a particular *instance* of a type that is *declared* to have a data attribute actually has the attribute. E.g. try the following in mypy (no Protocols involved):
```
class B:
    name: str
class C(B):
    pass

x = C()
print(x.name)  # No error from mypy
```
The behavior you are seeing is similar -- the runtime check is not checking whether the attribute is currently *set*, it checks whether it is *declared*. Which it is in your example.
