### ISSUE TITLE
Protocol Composition

### ISSUE THREAD

**Issue by rmorshea** [python/typing#804]
I'm encountering some situations with `Protocol` where it would be advantageous to support a form of composition. For example, one might have a `Sender` protocol and `Receiver` protocol, but need to handle an object which is both a "sender" and a "receiver". Now, I could use multiple inheritance to create a `SenderReceiver` class, but that way leads madness - the more protocols I have to juggle the larger the combinatorial explosion of subclasses need to be defined.

The solution to this problem is composition wherein one ought to be able to `Compose[Sender, Receiver]` to represent a type that is both a "sender" and a "receiver". Thus, instead of having to write:

```python
from typing import Protocol

class Sender(Protocol):
    def send(self, msg: str) -> None:
        ...

class Receiver(Protocol):
    def recv(self) -> str:
        ...

class SenderReceiver(Sender, Receiver):
    ...

def communication_loop(send_recv_obj: SenderReceiver) -> None:
    while True:
        to_send = ...
        controller.send(...)
        received = controller.recv()
        ...
```

I could write the far more extensible:

```python
from typing import Protocol, Compose

class Sender(Protocol):
    def send(self, msg: str) -> None:
        ...

class Receiver(Protocol):
    def recv(self) -> str:
        ...

def communication_loop(send_recv_obj: Compose[Sender, Receiver]) -> None:
    while True:
        to_send = ...
        controller.send(...)
        received = controller.recv()
        ...
```

One could even imagine a simplification of the composition syntax from `Compose[X, Y, ...]` to `X & Y & ...`. I think this `&` operator would contrast nicely with the relatively new `|` operator for `Union`.

**Comment by JelleZijlstra** [comment]
This is already being proposed in #213 under the name "Intersection".
