### ISSUE TITLE
How can I convert type string `"Path"` to type `pathlib.Path`?

### ISSUE THREAD

**Issue by loynoir** [python/typing#810]
# Brief
How can I convert type `"Path"` to `pathlib.Path`?
More genericly, how can I convert type from a string?

# Example
```python
from __future__ import annotations
import pathlib
from pathlib import Path
import inspect
import IPython

def fn(pathTemp: 'Path'): pass

anno = inspect.signature(fn).parameters['pathTemp'].annotation
assert(anno == 'Path')

_anno = None
IPython.embed()
assert(_anno == pathlib.Path)
```

**Comment by JelleZijlstra** [comment]
You can use `eval`, `typing.get_type_hints`, or in Python 3.10 `eval_str=True` in the call to `inspect.signature`. See https://docs.python.org/3.10/howto/annotations.html#manually-un-stringizing-stringized-annotations for some related discussion.

**Comment by loynoir** [comment]
Appreciate a lot 😘
