### ISSUE TITLE
How to get `ReturnType` of variable?

### ISSUE THREAD

**Issue by loynoir** [python/typing#811]
# Background
[google/python-fire](https://github.com/google/python-fire) is a library for automatically generating command line interfaces from a Python object.

I did a [fork](https://github.com/loynoir/python-fire), to try to it recognize annotation, and cast string (from cli args) into right type.

As a newbee, I try my best but can't get answer :(

# Design
At beginning, tried to `pre-define subset of type`, but too hardcoded. 
Implement might be more elegant, if there is a complexer `ReturnType`.

# Question
Is there something like `ReturnType`, but complexer?
`ReturnTypeCallee` is an inverse function to `ReturnType`
```python
assert(fn == ReturnTypeCallee[ReturnType[fn]])
```

# Example

```py
# cli.py
from __future__ import annotations
import fire
def cli(
    jsonData: 'ReturnType[json.loads]',
    yamlData: 'ReturnType[yaml.safe_load]',
    customizeData: 'ReturnType[__main__.customize]',
)

```

```py
# fire/anno_caster.py
from __future__ import annotations
def formatter_factory(typestr: 'str'):
    return ReturnTypeCallee(typestr)

assert(json.loads == formatter_factory('ReturnType[json.loads]'))
assert(yaml.safe_load == formatter_factory('ReturnType[yaml.safe_load]'))
```

# Minimal Reproduce
1. [actual_anno_caster.py](https://gist.github.com/loynoir/b5d17df437b2eb58239a2bc31c69a679#file-actual_anno_caster-py)
2. [expect_anno_caster.py](https://gist.github.com/loynoir/55ead49cfb2f3fb0066caa493d418680#file-expect_anno_caster-py)

**Comment by JelleZijlstra** [comment]
No, this doesn't exist. We could add a `ReturnType` primitive to typing, but it would mostly be for the benefit of static type checkers. It's probably easier to discuss your problems in https://gitter.im/python/typing since this repo is mainly for proposing changes to the type system.
