### ISSUE TITLE
Enable Discussions on this repo

### ISSUE THREAD

**Issue by JelleZijlstra** [python/typing#812]
I liked @srittau's idea in the Typing Summit earlier today to have something like a "typing school" for people to learn more about how to use typing correctly. One way to do that could be to enable GitHub's Discussions feature for this repo. The pyright repo does that and it seems to work well for them (but I'd be curious to hear if @erictraut has any thoughts).

Example use cases would be:
- Please review stubs I wrote for a third-party library
- How do I type this code correctly?
- What does this type annotation mean?

Discussion on the future of the typing ecosystem should still go to the typing-sig mailing list.

To get people to find this feature, we could refer to it in the documentation for the Python typing module, the README for typeshed, and the documentation of the various type checkers.

**Comment by srittau** [comment]
I thought about using discussion on this repo as well, but was unsure. But honestly, this is probably the lowest friction implementation to start with. We can always move this somewhere else if needed.

**Comment by erictraut** [comment]
GitHub discussions has worked really well for pyright — better than alternatives I've used in the past such as gitter.

**Comment by srittau** [comment]
For reference, here is the typing-sig thread about Type School: https://mail.python.org/archives/list/typing-sig@python.org/thread/5LFBZIQ4RTXJNP6DYB45WBAXS4KEWVLD/

**Comment by srittau** [comment]
I like that you can mark a discussion as "answered". This is great for our use case. For starters we could have three categories: "General", "Q&A" (for general typing help), "Reviews" (aka "Type School"). In addition we could add resources for maintainers to the repository. For example, a GitHub Action for checking a project with mypy.

**Comment by srittau** [comment]
@JelleZijlstra @gvanrossum I am not sure who has the necessary permissions on this repository (I haven't), but could someone enable Discussions, so we can play around with it?

**Comment by JelleZijlstra** [comment]
I don't have permission.

**Comment by gvanrossum** [comment]
I do; I enabled Discussions.

So maybe we should add some more admins to this repo?

**Comment by gvanrossum** [comment]
(I changed permissions for @JelleZijlstra, @srittau and @msullivan to Admin so from now on you can determine your own destiny. This includes inviting new admins!)

**Comment by JelleZijlstra** [comment]
Thanks Guido!
