### ISSUE TITLE
Is there a way to properly annotate decorators for both functions and methods?

### ISSUE THREAD

**Issue by lonelyenvoy** [python/typing#824]
I opened an [issue](https://github.com/python/mypy/issues/10805) about method decorators previously and it was transferred to python/mypy. Although it looks like an implementation issue in mypy, it's indeed related to the design of the typing.

For now, it seems impossible to annotate decorators that can be applied to both functions **outside** and **inside** classes (i.e. methods). Is there a workaround?

```python
def decorator(func):
    def wrapper(*args, **kwargs):
        ...
    return wrapper

@decorator
def foo(arg):
    ... 

class A:
    @decorator
    def bar(self, arg):
        ...
```

**Comment by gvanrossum** [comment]
Still seems a mypy issue. It conflates class and instance methods.

**Comment by lonelyenvoy** [comment]
> Still seems a mypy issue. It conflates class and instance methods.

@gvanrossum Can you please elaborate a little bit by commenting in the [mypy issue](https://github.com/python/mypy/issues/10805) so that they can fix it? Thank you.

**Comment by gvanrossum** [comment]
Not right now, I am about to head on vacation. All I know is that this is a longstanding mypy issue.

**Comment by lonelyenvoy** [comment]
OK, enjoy your vacation time.

**Comment by Tomaz-Vieira** [comment]
I tried it with pyright and things seem to check just right:

```python3
# pyright: strict

from typing import Callable, TypeVar
from typing_extensions import ParamSpec


_P = ParamSpec("_P")
_OUT = TypeVar("_OUT")

def decorator(func: Callable[_P, _OUT]) -> Callable[_P, _OUT]:
    def wrapper(*args: _P.args, **kwargs: _P.kwargs) -> _OUT:
        print(f"caling {func.__name__}")
        return func(*args, **kwargs)
    return wrapper

@decorator
def foo(arg: int) -> int:
    return 123

reveal_type(foo) # (arg: int) -> int

class A:
    @decorator
    def bar(self, arg: str) -> None:
        return None

reveal_type(A().bar) # (arg: str) -> None
```

But I think mypy doesn't support `ParamSpec` yet

**Comment by srittau** [comment]
I am closing this here as this seems to be a mypy issue (python/mypy#10805).
