### ISSUE TITLE
Using pipenv with python 3.8 skips installation of typing-extensions

### ISSUE THREAD

**Issue by namoscagnm** [python/typing#825]
I use pipenv as a package manager, and while installing fastapi, it installs implicitely pydantic, which in turn requires typing-extenions.

All went well for me when I was doing my Pipfile with
```
[requires]
python_version = "3.7"
```

but now that I switched to 3.8, I get the following warning during the command pipenv install:

_Ignoring typing-extensions: markers 'python_version < "3.8"' don't match your environment_

After this, when I run my code, I get the following exception:

..\..\..\..\..\.virtualenvs\tama-test-pr-112-jv6vt3rk\lib\site-packages\fastapi\params.py:4: in <module>
    from pydantic.fields import FieldInfo, Undefined
pydantic\__init__.py:2: in init pydantic.__init__
    ???
pydantic\dataclasses.py:3: in init pydantic.dataclasses
    ???
pydantic\class_validators.py:8: in init pydantic.class_validators
    ???
pydantic\errors.py:5: in init pydantic.errors
    ???
pydantic\typing.py:23: in init pydantic.typing
    ???
E   ModuleNotFoundError: No module named 'typing_extensions'

I see that my pipfile.lock was automatically generated to have this entry:
```
"typing-extensions": {
            "hashes": [
                "sha256:0ac0f89795dd19de6b97debb0c6af1c70987fd80a2d62d1958f7e56fcc31b497",
                "sha256:50b6f157849174217d0656f99dc82fe932884fb250826c18350e159ec6cdf342",
                "sha256:779383f6086d90c99ae41cf0ff39aac8a7937a9283ce0a414e5dd782f4c94a84"
            ],
            "markers": "python_version < '3.8'",
            "version": "==3.10.0.0"
        }
```

This seems to be what is block the installation, but I dont know how pipenv decided to put this marker. Is the fix to stop generating this wrong marker needed on the Pipenv side, or in typing-extenions side?

**Comment by srittau** [comment]
It looks as if pydantic depends on typing-extensions unconditionally:

```
typing-extensions>=3.7.4.3
```

I'm not sure what is going on here, but I doubt it is something that can be fixed in typing-extensions.
