### ISSUE TITLE
Confusing deprecation notice for typing.IO

### ISSUE THREAD

**Issue by rittneje** [python/typing#834]
The docs for `typing.IO`, `typing.TextIO`, and `typing.BinaryIO` include a confusing deprecation notice. https://docs.python.org/3/library/typing.html#typing.IO

> Deprecated since version 3.8, will be removed in version 3.12: These types are also in the typing.io namespace, which was never supported by type checkers and will be removed.

Are these types actually deprecated, or just the ones in `typing.io`? If it is the former, then the documentation should indicate what to use instead. And if it is the latter, then the documentation should be rephrased for clarity.

**Comment by Gobot1234** [comment]
It's just the ones in the typing.io namespace. But yeah I kind of agree that isn't very clear.

**Comment by srittau** [comment]
Rereading it, I am not too happy with the wording. I am sure that a PR to cpython with a better wording would be accepted. That said, this should be reported directly to bugs.python.org.

**Comment by gvanrossum** [comment]
@Fidget-Spinner I wonder if we can make the deprecation clearer by separately documenting `typing.io` and `typing.re` and only having deprecation notices *there*? (I know we have gone around in circles forever about this, but I have to agree with the OP that unless you read very carefully it looks like typing.IO etc. are deprecated.

**Comment by Fidget-Spinner** [comment]
@gvanrossum agreed, especially since the deprecation notice is for ``typing.IO`` (the thing that isn't going away), not ``typing.io.IO`` (the thing that *is* going away). OP has already created a bpo at https://bugs.python.org/issue44925.

**Comment by gvanrossum** [comment]
Can I trust you to guide the OP through contributing if they're so
inclined, and otherwise either you or @srittau can write a PR.

**Comment by rittneje** [comment]
For anyone who comes across this issue later, the deprecation notice was fixed in this PR. https://github.com/python/cpython/pull/28004
