### ISSUE TITLE
[meta] Can I have triage permissions for this repo please?

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/typing#837]
Some time ago I noticed a few issues weren't relevant anymore. I plan to do a spring cleaning of issues in this repo in the future. So I'd appreciate triage permissions so I can add tags/close outdated issues.

Background: I help triage issues in the upstream `typing` module in CPython.

**Comment by srittau** [comment]
Thanks for helping out, Ken, I have now granted you access.

**Comment by Fidget-Spinner** [comment]
Great, thanks Sebastian!
