### ISSUE TITLE
Publishing the docs

### ISSUE THREAD

**Issue by srittau** [python/typing#842]
There are no docs to publish, yet, but we should consider where and how to publish the docs, once there are. The docs should automatically be built and published when a PR is merged. Maybe we could start with a `github.io` sub-domain? Or try to get either a python.org subdomain like `typing.python.org` or `docs.python.org/typing`? Who would we need to approach for that?

**Comment by JelleZijlstra** [comment]
Another option is ReadTheDocs, similar to e.g. https://black.readthedocs.io/en/stable/.

To get something on python.org I suspect we'd need buyin from the SC and Ee Durbin.

**Comment by srittau** [comment]
Read the Docs sounds like a good idea.

**Comment by srittau** [comment]
https://typing.readthedocs.io/en/latest/

**Comment by hugovk** [comment]
Sebastian:

> Or try to get either a python.org subdomain like `typing.python.org` or `docs.python.org/typing`?

Jelle:

> Another option is ReadTheDocs, similar to e.g. [black.readthedocs.io/en/stable](https://black.readthedocs.io/en/stable/).

Why not both?

It's possible to use a custom domain like `typing.python.org` with RTD:

https://docs.readthedocs.com/platform/stable/custom-domains.html

Benefits: same easy workflow with PR previews and good hosting, plus a nice domain.


> To get something on python.org I suspect we'd need buyin from the SC and Ee Durbin.

👍

**Comment by JelleZijlstra** [comment]
I'd like to get typing.python.org to happen but haven't had the time or energy to push that through.

**Comment by hugovk** [comment]
> Configuring readthedocs is trivial. In fact, I've added typing.python.org as a domain to readthedocs. (Not as the canonical domain for now, though.) But naturally, this requires changes to the python.org domain, namely adding a CNAME entry from `typing` to `readthedocs.io`.

👍

> I don't know who to approach about this.

Open an issue at https://github.com/python/steering-council first to get permission to do it, then we can ask Ee about the CNAME.

**Comment by srittau** [comment]
I think it's best if the request comes from the Typing Council. @JelleZijlstra Is this something you could put on the Typing Council's agenda?

**Comment by srittau** [comment]
Let's continue discussion in #1924.
