### ISSUE TITLE
[BUG] typing.NamedTuple does not allow default values

### ISSUE THREAD

**Issue by lilyz622** [python/typing#850]
**Bug Report**
when I try to define defaults for NamedTuple, I get thrown a TypeError. I am not sure if this is expected behavior.

**To Reproduce**

(Write your steps here:)

from typing import NamedTuple
x = NamedTuple('hi', a=str, b=str, defaults=[None])

**Expected Behavior**

x = NamedTuple('hi', a=str, b=str, defaults=[None])
y = x(a='1',b=None)

c = NamedTuple('hi', a=str, b=str, defaults=['bye'])
b = c(a='1')
b # returns hi(a='1', b='bye')

**Actual Behavior**
x = NamedTuple('hi', a=str, b=str, defaults=[None])

... lib/python3.8/typing.py", line 149, in _type_check
raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: NamedTuple('Name', [(f0, t0), (f1, t1), ...]); each t must be a type Got ['hi'].

c = NamedTuple('hi', a=str, b=str, defaults=['bye'])

lib/python3.8/typing.py", line 149, in _type_check
raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: NamedTuple('Name', [(f0, t0), (f1, t1), ...]); each t must be a type Got ['bye'].

**Your Environment**

Python version used: Python 3.8.6
Operating system and version: Linux

**Comment by JelleZijlstra** [comment]
The class-based version does support defaults. Do you have any special reason not to use it?

**Comment by lilyz622** [comment]
A couple of things:
1. Needing to define a class for a simple 2-variable NamedTuple can make code reading harder when nesting NamedTuples
2. I would generally expect the typing.NamedTuple to behave similarly to the collections.namedtuple, which enables defaults. Both the collections.namedtuple and class-based NamedTuple allow for defaults, so it is not expected that this one does not.

```
class CustomCat(NamedTuple):
    litter: str
    count: int
    breed: NamedTuple( <--- it is easier to read for simple typed tuples when I don't want to define a whole class somewhere else in code
        "Breed",
        # mandatory fields
        breed=str,
        # optional fields
        color=str,
    )

class Cat(NamedTuple):
    custom_features: CustomCat = None <--- I already have a two-nested typed tuple class
 ...
```

**Comment by srittau** [comment]
I agree that this is unexpected and the behavior of `typing.NamedTuple` should probably match `collections.namedtuple`. That said, please file this over at Python's bug tracker at bugs.python.org.
