### ISSUE TITLE
typing_extensions: Drop support for Python 3.4 and 3.5

### ISSUE THREAD

**Issue by srittau** [python/typing#867]
Both Python versions have reached end of life for nearly a year or more. Tooling starts to be problematic for them, for example, GitHub Actions for Python 3.4 seems to be broken. Python 3.5 was problematic typing-wise, because it added the `typing` module in a minor version, so it's hard to test it.

Old versions of typing_extensions remain available. This means t hat users of obsolete versions can't use newer typing features, but I think that's a reasonable tradeoff.

**Comment by JelleZijlstra** [comment]
Sounds good. Once we get CI back up I'd like to do another release with just those changes; after that we can drop 3.4 and 3.5.

**Comment by srittau** [comment]
@JelleZijlstra To clarify: By another release you meant 3.10.0.2, correct? So this is ok to be merged?

**Comment by JelleZijlstra** [comment]
Yes. Though maybe we should ask in typing-sig if anyone still cares about support for 2.7, 3.4, and 3.5.

**Comment by srittau** [comment]
The announcement on typing-sig had no reactions, I think this is good to be merged.

**Comment by AA-Turner** [comment]
Hi @srittau -- I saw that you've dropped support for older versions of Python, & thought it might be a good idea to go through `typing_extensions` and remove paths that can now never be hit in a supported version.

Would you be open to a PR? For reference, the relevent branch is https://github.com/AA-Turner/typing/tree/cleanup.

No worries if not, I was just having a play around and wondered if it would be useful to merge upstream for future maintainability etc.

Thanks
Adam

**Comment by hauntsaninja** [comment]
That is likely welcome. One thing I'm confused about is whether we still support Python 2.7? Most things say yes, but e.g. `setup.cfg` says no.

**Comment by AA-Turner** [comment]
In my first commit I dropped 2.7 support (https://github.com/AA-Turner/typing/commit/965441a527007901c8f9834283593ea6b8abe391) as that's what was mentioned in the typing-sig announcement -- https://mail.python.org/archives/list/typing-sig@python.org/thread/65LVW6O6ET6QHWLD4SAFDFKMWOIPPXRK/

It'd be easy enough to revert if wanted?

A
