### ISSUE TITLE
Remove the src directory

### ISSUE THREAD

**Issue by srittau** [python/typing#877]
The `src` directory contains what later became `typing` in the stdlib, and is currently used for the Python 3 backport of `typing`. But since the last supported version of the backport was Python 3.4, which is long obsolete, I suggest we delete the `src` directory for easier maintenance and less confusion. We can keep the `python2` directory for now, which contains the backport for Python 2, although I'd personally not miss it.

**Comment by JelleZijlstra** [comment]
Sounds good. We can get rid of `typing` for Python 3 once we drop 3.4 support (#867).

I also agree that it's about time to drop support for Python 2. Maybe there's still people using the backport though.

**Comment by srittau** [comment]
The last commit to the Python 2 backport was two years ago. I believe it's safe to remove it was well. We can always restore it if a critical issues comes up.

**Comment by stefanv** [comment]
Remember to update the [README](https://github.com/python/typing/blob/master/README.md) which mentions `src`.
