### ISSUE TITLE
Add a "not None" type

### ISSUE THREAD

**Issue by KotlinIsland** [python/typing#901]
I regularly find it annoying that there is no way to type something as "anything, except None". 

In Kotlin the root type `Any` is split from `null`, and the union of those is denoted `Any?`

In TypeScript the root type `unknown` includes `null` and `undefined`, but those types are distinct from the other basal types `object`, `number` etc. `{}` can be used to refer to any type except `null`(and `undefined`)

I think a `Not` type would be overkill, but a handcrafted type that represents anything except None would based and useful.

**Comment by sobolevn** [comment]
Related #614

**Comment by srittau** [comment]
#801 already suggests a general `Not` type. I agree that either a general `Not` type or a specialized `NotNone` type would occasionally be useful, but all discussions about new typing features should go to typing-sig.
