### ISSUE TITLE
Setting interface to implemented version in parent class isn't reflected in child class

### ISSUE THREAD

**Issue by prchristie** [python/typing#914]
I'm entirely unsure if this is an expected behavior, it just seems like it could be useful, if even possible at all.

**Feature**
In a lot of cases, I want to have a parent class with an initializer that strongly implies that you should use a certain config:

```python
class IFooConfig(ABC):
    ...

class IFoo(ABC):
    def __init__(self, config: IFooConfig):
        self._config = config

class BarConfig(IFooConfig):
    ...

class Bar(IFoo):
    def __init__(self, config: BarConfig):
        super().__init__(config)
```

In this case, `self._config` will still refer to an `IFooConfig`, meaning it won't have intellisense for anything in `BarConfig`.

The way around this at the moment is to simply do

```python
def __init__(self, config: BarConfig):
    self._config = config
```

in the Bar initializer

Perhaps there is a better way to structure this code/have this kind of configuration layout to completely avoid this issue all together, or perhaps there is a code stink in what I'm doing that you can suggest a fix for. It is obviously difficult to tell what the parent __init__ is going to do, so I suspect that it simply isn't possible.

**Comment by erictraut** [comment]
This structure is fine. You can use generic types to give you the proper intellisense behavior. Here's what that might look like:

```python
from abc import ABC
from typing import Generic, TypeVar

class IFooConfig(ABC):
    ...

_TConfig = TypeVar("_TConfig", bound=IFooConfig)

class IFoo(ABC, Generic[_TConfig]):
    def __init__(self, config: _TConfig):
        self._config = config

class BarConfig(IFooConfig):
    ...

class Bar(IFoo[BarConfig]):
    def __init__(self, config: BarConfig):
        super().__init__(config)

x = Bar(BarConfig())._config
reveal_type(x)  # BarConfig
```

**Comment by srittau** [comment]
For future reference, the discussions in this repository are a better place for these types of questions.
