### ISSUE TITLE
4.0.0: License key is missing in METADATA of wheel

### ISSUE THREAD

**Issue by Mscht** [python/typing#947]
I've noticed that the "License" attribut is missing since the migration from setup.py to pyproject.toml. This field is required to automatically detect the license of the resulting wheel.

Can you please try to convince Flit to add `License: PSF` to METADATA?

**Comment by AA-Turner** [comment]
I don't think this is currently possible with [PEP 621 metadata](https://python.github.io/peps/pep-0621), although the PSF licence trove classifier is there, which could be tested for?

Flit does seem to support it in ['old style' metadata](https://flit.readthedocs.io/en/latest/pyproject_toml.html#old-style-metadata), but there is a note that this doesn't work with standards based metadata, sadly.

A

**Comment by JelleZijlstra** [comment]
I spent a bit of time looking into this and it doesn't seem like there's much more we can do. We do have the trove classifier and the LICENSE file in the wheel; @Mscht is that enough?

**Comment by Mscht** [comment]
Thank you for your efforts looking into it. I think the trove classifier offer the required information. It is just important for me that I do not have to parse a free text license file.
Just as note: If I understand it correct, e.g. poetry is one step ahead of PEP 621 because it already accepts a string value for license and refers to the SPDX defined license identifiers.
