### ISSUE TITLE
Self being a typing._SpecialForm prevents a case from PEP 673

### ISSUE THREAD

**Issue by CharString** [python/typing#964]
Among the [valid locations for Self](https://www.python.org/dev/peps/pep-0673/#valid-locations-for-self) in PEP 673 we find:
```python
TupleSelf = Tuple[Self, Self]
class Alias:
    def return_tuple(self) -> TupleSelf:
        return (self, self)
```

But `typing._type_check` regards `typing._SpecialForm` instances invalid type arguments
https://github.com/python/cpython/blob/e0f8a3e9b96bbc2597f61be96993ef0c768a19fe/Lib/typing.py#L179

So this use will result in a

    TypeError: Plain typing_extensions.Self is not valid as type argument

This also affects uses in linked lists and recursive dataclasses lke 
```python
@dataclasses.dataclass
class MenuItem:
    url: str
    title: str
    description: str = ""
    items: typing.List[typing_extensions.Self] = dataclasses.field(default_factory=list)
```

**Comment by Gobot1234** [comment]
Hi, I'm not entirely sure what can be done here until the PEP is accepted and I can change https://github.com/python/cpython/blob/e0f8a3e9b96bbc2597f61be96993ef0c768a19fe/Lib/typing.py#L176
To 
```py
    if arg in (Any, NoReturn, Final, Self):
```
If you have any suggestions for how to fix this now, I'd be more than happy to implement them.

However, if you need this to work right now you you have a few options:
- use the PEP 585 builtin versions of the types which are much more lenient than the typing versions.
- avoid the annotations actually being executed at runtime (`typing_extensions.TypeAlias` and `__future__.annotations` or stringify the types).

**Comment by JelleZijlstra** [comment]
We can probably fudge things in typing-extensions so that it's not an instance of `_SpecialForm`.

**Comment by CharString** [comment]
@Gobot1234 Yes, for my use case I'm using a string as ForwardRef now. I just [wondered if I were doing something wrong](https://stackoverflow.com/q/70083371/383793).

@JelleZijlstra Like vendoring the _SpecialForm from the cpython 3.11 codebase? Or a more elegant fudge? Namespaces are one honking great idea :-)

**Comment by JelleZijlstra** [comment]
Yes, vendoring would be the way to go. The place where this throws lets things it doesn't recognize through, so if we just make Self look like an unrelated object, it should pass.

**Comment by CharString** [comment]
Something like this?
