### ISSUE TITLE
Type hint Type[T] on user defined classmethod?

### ISSUE THREAD

**Issue by MathiasSven** [python/typing#977]
Working on making stubs for an external library and came across [this](https://github.com/neo4j-contrib/neomodel/blob/b1bc5d50b0f64f64cfcf99be7c4622f178a7325a/neomodel/util.py#L338) implementation of a `@classpropery`,
there doesn't seem to be a way to let Mypy know that a class property should take a class and not an instance.
```py
from typing import TypeVar, Protocol, Callable, Type

T = TypeVar("T")
R = TypeVar("R")

V = TypeVar("V", contravariant=True)
U = TypeVar("U", covariant=True)

class ClassProperty(Protocol[V, U]):
    def __init__(self, getter: Callable[[V], U]) -> None: ...
    def __get__(self, obj: None, type: V | None = ...) -> U: ...

def classproperty(f: Callable[[T], R]) -> ClassProperty[T, R]: ...

class NodeSet: ...

F = TypeVar('F', bound='StructuredNode')

class StructuredNode:
    @classproperty
    def nodes(cls: Type[F]) -> NodeSet: ...

class TestNode(StructuredNode): ...

assert isinstance(TestNode.nodes, NodeSet)
```
The stub above generates this error:
`main.py:22: error: The erased type of self "Type[__main__.StructuredNode]" is not a supertype of its class "__main__.StructuredNode"`
The error is caused because `cls` is implicitly given as `self` since the method is not an actual `classmethod`. Is there a way to fix this or is this a limitation?

**Comment by MathiasSven** [comment]
It seems that this is a bug as `Self`, which according to PEP 673 should be equivalent to the previous method, fixes this issue 
```py
from typing import Generic, TypeVar, Any, Optional, Protocol
from collections.abc import Callable
from typing_extensions import Self
from abc import ABC

H = TypeVar("H")
R = TypeVar("R")

V = TypeVar("V")
U = TypeVar("U")

class ClassProperty(Protocol[V, U]):
    def __init__(self, getter: Callable[[V], U]) -> None: ...
    def __get__(self, obj: None, type: type[V] | None = ...) -> U: ...

def classproperty(f: Callable[[H], R]) -> ClassProperty[H, R]: ...

T = TypeVar('T', bound='BaseItem')
K = TypeVar('K')

class ItemSet(Generic[K]):
    def get_or_none(self, **kwargs: Any) -> Optional[K]: ...

class BaseItem(ABC):
    @classproperty
    def set(cls: T) -> ItemSet[T]: ...

class BaseItemSelf(ABC):
    @classproperty
    def set(cls) -> ItemSet[Self]: ...

class FooItem(BaseItem):
    name: str

class FooItemSelf(BaseItemSelf):
    name: str

reveal_type(FooItem.set)
reveal_type(FooItemSelf.set)
```
```
41:21 - error: Cannot access member "set" for type "Type[FooItem]" (reportGeneralTypeIssues)
41:13 - info: Type of "FooItem.set" is "Unknown"
42:13 - info: Type of "FooItemSelf.set" is "ItemSet[FooItemSelf]"
```

**Comment by JelleZijlstra** [comment]
I think this is better discussed on the issue tracker for mypy or pyright for now. Support for constructs like `classproperty` is definitely often spotty at the moment, but that's primarily something to improve among individual type checkers.

**Comment by MathiasSven** [comment]
Understood, opened an issue on the respective checkers, it seems this is just a limitation due to `T` being a function scoped variable that goes out of scope once the decorator has been evaluated as explained to me in this [issue](https://github.com/microsoft/pyright/issues/2732#issuecomment-997103017).
