### ISSUE TITLE
[question] How can I compare function signatures in the `typing.Callable` syntax to `inspect.signature` syntax>

### ISSUE THREAD

**Issue by sg-s** [python/typing#990]
My ultimate goal is to enforce some sort of type for functions that are passed to arguments to other functions.

I have a function that looks like:

```python
def foo(bar: Callable[[int], int]):
```

I want to implement functionality so that it only accepts functions that look like:

```python
def bar(a: int)->int:
```

If I `inspect` bar, I get this:

```python
inspect.signature(bar)
<Signature (a: int) -> int>
```

How do I work with this and make sure it's the same as the function signature as defined in the `Callable` syntax?

**Comment by srittau** [comment]
This probably better asked over at [our discussions forum](/python/typing/discussions).
